### ISSUE TITLE
Make use of backend users profile image (TYPO3 7.x only)

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#105]
Provide a way to use the avatar image in Fluid templates. Could be a nice feature to have the blog post author profile image (avatar) next to the author name.

Need to check which 7.x version introduced the avatar image feature.

**Comment by Raphibauer** [comment]
Getting the be_users-Description would be a nice feature to. The description could be implemented at the same time?!

**Comment by fnagel** [comment]
@Raphibauer This should already work! We extend the extbase be user model, which has getters and setters for description property. https://github.com/fnagel/t3extblog/blob/master/Classes/Domain/Model/BackendUser.php#L29

````{post.author.description}```` should do the trick!

See extbase model for all available properties: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/Domain/Model/BackendUser.php

**Comment by fnagel** [comment]
Added the avatar feature in an extra branch. Not tested in 6.2 yet.
https://github.com/fnagel/t3extblog/tree/feature-author

Feedback wanted!
