### ISSUE TITLE
Use which branch for typo3 v7.6?

### ISSUE THREAD

**Issue by Renader** [fnagel/t3extblog#106]
Use master or branch typo3-7x? 

I'm asking since 7x doesnt seem up to date but master branch causes some errors for me.

but great extension so far! gitter'd be great.

**Comment by fnagel** [comment]
Please use the master branch. What errors?

**Comment by Renader** [comment]
Probably I'm just missing something..

The minimal configuration wont work.


i have to give the following typoscript in order to get it running:

module.tx_t3extblog.settings.storagePid.pid = 11
plugin.tx_t3extblog.persistence.storagePid = 11
module.tx_t3extblog.settings.blogsystem.pid = 3
plugin.tx_t3extblog.settings.blogsystem.pid = 3
module.tx_t3extblog.settings.subscriptionManager.pid = 1
plugin.tx_t3extblog.settings.subscriptionManager.pid = 1
module.tx_t3extblog.settings.subscriptionManager.admin.mailTo.email = test@test.de
plugin.tx_t3extblog.settings.subscriptionManager.admin.mailTo.email = test@test.de



if I remove the plugin lines => Frontend Blog wont work
if I remove the module line => Backend Blog Modul wont work


Typo3v7.6.0 + RealURL and DCE, no other Plugins

**Comment by fnagel** [comment]
````
if I remove the plugin lines => Frontend Blog wont work
if I remove the module line => Backend Blog Modul wont work
````

Right. That's how the TypoScript for FE and BE is supposed to work. This behavior is documented.
I suggest using the constant editor or using a TS assignment from plugin to module.

**Comment by Renader** [comment]
Sorry then for wasting your time and thanks for the help, everything is fine now. 

I missed the module.tx_t3extblog < plugin.tx_t3extblog.

Great Extension! I'm just not to experienced with Typo3 ;-)

**Comment by fnagel** [comment]
No problem. Glad I could help. Have fun with the extension and consider a donation!
