### ISSUE TITLE
JOIN across multiple tables in BackendBaseController.php leads to empty blog related pages result

### ISSUE THREAD

**Issue by pvanhemmen** [fnagel/t3extblog#107]
Sorry for coming back to this topic with some delay.

The JOIN across multiple tables in BackendBaseController.php is too restrictive, because it defines pages.deleted, post.deleted and comment.deleted to be 0 accross all tables. There are cases where all three conditions together don't match, so the result is empty. This is the case if for example all existing comments are deleted.

This gives a wrong "No Blog records found" warning on the Article Manager Page.

I will create a seperate branch with a Bugfix. Hop that helps!

**Comment by fnagel** [comment]
Looks good. Will be merged soon.

**Comment by fnagel** [comment]
Any feedback on this comment? https://github.com/fnagel/t3extblog/pull/108#commitcomment-15398316

**Comment by fnagel** [comment]
Merged and improved. See master branch.
