### ISSUE TITLE
Add the possibility to use disabled or deleted backend-user data

### ISSUE THREAD

**Issue by freshworkx** [fnagel/t3extblog#109]
Sometimes a backend user is disbled or deleted by the admin, then it´s not possible to show a post because of a missing author object.

Case 1: 
* Store the author data in your own table fields

Case 2: 
* Modified getter and setter of author in the post-model 
* initialize the BackendUserRepository with "setIgnoreEnableFields" and "setIncludeDeleted"

**Comment by fnagel** [comment]
Seems like a legit case.

I've tried just to modify the BE user repo but the relation manager seems not to use that. Seems like something like this is needed: https://gist.github.com/econic/7302684
Is that what you meant with "modified getter / setter"?

Not the cleanest solution. What about a simple fallback: creating an empty dummy user when no relation was found?

**Comment by fnagel** [comment]
I've added a fallback as proposed above.

**Comment by freshworkx** [comment]
Sorry for the late response, just getting now back to work. Personally I would prefere the "ignoreEnableFields" solution, but fallback is also ok!

**Comment by fnagel** [comment]
I'm not quite sure if displaying a deleted or disabled user is really something we want in general.

I guess it's pretty easy to add a custom query by using a class overwrite here if the described functionality is really needed.

**Comment by freshworkx** [comment]
I agree, think the fallback solution in general will work in most cases

**Comment by fnagel** [comment]
Will be part of the next release.

**Comment by fnagel** [comment]
Fixed with 2.0.1
