### ISSUE TITLE
Own templates don´t work in 7.6?

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#110]
Hi!
I´ve discovered some strange behavior: when copying the template files to fileadmin (path set via ts), the aren´t used, except of Templates/ViewHelpers/Widget/Paginate/Index.html?! 
Just copying the original files to fileadmin doesn´t change that. 
In 6.2. it works fine, after Updates to 7.6.2 it don´t work anymore. Any ideas?

**Comment by fnagel** [comment]
Are you aware of the TS change for Fluid templates? That"s not t3extblog specific but a general change for FLUID. 

Anyway, its covered by our documentation:
https://docs.typo3.org/typo3cms/extensions/t3extblog/Configuration/Index.html#overwrite-templates

ps: You should no longer use fileadmin for templates and other assets but use an extensions.

**Comment by criwe** [comment]
@fnagel omg, that was too easy... thx and have a nice christmas!

**Comment by fnagel** [comment]
Glad I could help. Have some nice holidays too!

**Comment by nebrot** [comment]
We have the same problem, our own template doesn't work with TYPO3 7.6.2 and t3extblog 2.0.0 / 2.0.1. We copied the whole Resources-directory into fileadmin/templates/ext/t3extblog and use this root-typoscript:

```
plugin.tx_t3extblog {
view {
    templateRootPath >
    templateRootPath {
        0 = EXT:t3extblog/Resources/Private/Templates/
        1 = fileadmin/templates/ext/t3extblog/Resources/Private/Templates/
    }
    partialRootPath >
    partialRootPath {
        0 = EXT:t3extblog/Resources/Private/Partials/
        1 = fileadmin/templates/ext/t3extblog/Resources/Private/Partials/
    }
    layoutRootPath >
    layoutRootPath {
        0 = EXT:t3extblog/Resources/Private/Layouts/
        1 = fileadmin/templates/ext/t3extblog/Resources/Private/Layouts/
    }
}
}
```
This is from the [docs](https://docs.typo3.org/typo3cms/extensions/t3extblog/Configuration/Index.html#configuration-overwrite-templates) (EXT:news is wrong there or?) Instead of "Path" we tried "Paths" too, but no change.


This also doesn't work
```
plugin.tx_t3extblog.view.templateRootPath =
fileadmin/templates/ext/t3extblog/Resources/Private/Templates/
plugin.tx_t3extblog.view.layoutRootPath =
fileadmin/templates/ext/t3extblog/Resources/Private/Layouts/
plugin.tx_t3extblog.view.partialRootPath =
fileadmin/templates/ext/t3extblog/Resources/Private/Partials/
```


Changing the template for example for fs_media_gallery is working:

```
plugin.tx_fsmediagallery.view.layoutRootPath = 
fileadmin/templates/ext/fs_media_gallery/Resources/Private/Layouts/
plugin.tx_fsmediagallery.view.partialRootPath = 
fileadmin/templates/ext/fs_media_gallery/Resources/Private/Partials/
plugin.tx_fsmediagallery.view.templateRootPath = 
fileadmin/templates/ext/fs_media_gallery/Resources/Private/Templates/
```


> Are you aware of the TS change for Fluid templates? That"s not t3extblog specific but a general change for FLUID. 

What do you mean with this?
Thank you for this extension and your help!

**Comment by pvanhemmen** [comment]
```
plugin.tx_t3extblog {
    view {
        templateRootPath >
        templateRootPaths {
            20 = Path/To/Your/Resources/Private/Templates/
            10 = EXT:t3extblog/Resources/Private/Templates/
        }
        partialRootPath >
        partialRootPaths {
            20 = Path/To/Your/Resources/Private/Partials/
            10 = EXT:t3extblog/Resources/Private/Partials/
        }
        layoutRootPath >
        layoutRootPaths {
            20 = Path/To/Your/Resources/Private/Layouts/
            10 = EXT:t3extblog/Resources/Private/Layouts/
        }
    }
}
```
This definitely works. Three things to pay attention to:

1. Mind the additional 's' when setting tempate paths with fallbacks.
2. The fallback path has to have a lower key number then the overwriting path
3. Paths are relative to the TYPO3 Web Root Folder (where fileadmin is located)

If that doesn't solve it you probably have errors elsewhere not related to t3extblog. Hope that helps!

**Comment by fnagel** [comment]
@pvanhemmen Seems the documentation is wrong here. I will adjust this asap https://docs.typo3.org/typo3cms/extensions/t3extblog/Configuration/Index.html#configuration-overwrite-templates

**Comment by criwe** [comment]
Maybe that should be added to the TS: 

`module.tx_t3extblog < plugin.tx_t3extblog`

(I´ve used the code from the documentation + that line in my TYPO3 7.6)

**Comment by fnagel** [comment]
Not relevant for FE context.

**Comment by nebrot** [comment]
Thank you for your help, but no success.
1: We have setup a clean TYPO3 7.6.2 installation
2: Installed t3extblog
3: Setup root
```
config {
  doctype = <!DOCTYPE html>
  htmlTag_setParams = lang="de" dir="ltr"
  doctypeSwitch = 1
  xmlprologue = none
  xhtml_cleaning = all
  renderCharset = utf-8
  additionalHeaders = Content-Type:text/html;charset=utf-8  
  language = de
  locale_all= de_DE.utf-8
  index_enable = 1
}

page.includeCSS {
  file1 = fileadmin/templates/css/layout.css
  }

page = PAGE
page.10 = FLUIDTEMPLATE
page.10 {
  file.stdWrap.cObject = CASE
  file.stdWrap.cObject {
    key.data = levelfield:-1, backend_layout_next_level, slide
    key.override.field = backend_layout
    1 = TEXT
    1.value = fileadmin/templates/html/layout.html
  }
}

lib.pageContent < styles.content.get
lib.pageContent.select.where = colPos = 0
```
4: Installed t3extblog
5: Copied whole folder Resources in web-root AND fileadmin and changed the Post-List and Post-Show
6: Constants root (save, clear cache)
```
plugin.tx_t3extblog.persistence.storagePid = 4
plugin.tx_t3extblog.settings.emailTo = info@example.com
plugin.tx_t3extblog.settings.blogsystem.pid = 1
plugin.tx_t3extblog.settings.subscriptionManager.pid = 5

plugin.tx_t3extblog {
    view {
        templateRootPath >
        templateRootPaths {
            30 = fileadmin/templates/ext/t3extblog/Resources/Private/Templates/
            20 = t3extblog/Resources/Private/Templates/
            10 = EXT:t3extblog/Resources/Private/Templates/
        }
        partialRootPath >
        partialRootPaths {
            30 = fileadmin/templates/ext/t3extblog/Resources/Private/Partials/
            20 = t3extblog/Resources/Private/Partials/
            10 = EXT:t3extblog/Resources/Private/Partials/
        }
        layoutRootPath >
        layoutRootPaths {
            30 = fileadmin/templates/ext/t3extblog/Resources/Private/Layouts/
            20 = t3extblog/Resources/Private/Layouts/
            10 = EXT:t3extblog/Resources/Private/Layouts/
        }
    }
}
```
7: Frontend-Error:
```
Sorry, the requested view was not found.
The technical reason is: No template was found. View could not be resolved for action "index" in class "TYPO3\CMS\Fluid\ViewHelpers\Widget\Controller\PaginateController".
```
Very strange is, if we have this comment between the settings and view
```
/* plugin.tx_t3extblog {
view {

}
} */
```
then we don't get this error with PaginateController.
We could send you a login to this testinstallation, if you want.

**Comment by fnagel** [comment]
Is that TS code above your constants config? If so: move to TS setup, you can not freely create constants with no assigning in TS. That's not how TS works. Are you aware of the basic concepts of TS setup and constants?

You missed the paginate setting. Error message is pretty obvious, isn't it?
````
widget.TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper.templateRootPath = {$plugin.tx_t3extblog.view.templateRootPath}
````

Seems you're missing the TS view config for emails too.
Using fileadmin for assets is no longer recommended for TYPO3, you should use custom extension.

**Comment by nebrot** [comment]
Now it works. Thank you so much for your patience.

>  Using fileadmin for assets is no longer recommended for TYPO3, you should use custom extension.

Why is it no longer recommended, are there some notes/guides about it?
So we should use the extension builder and copy all of our custom templates in /ext/myextensionname/Resources/Private/t3extblog/?

**Comment by fnagel** [comment]
Glad it now works for you!

Not sure of there is some official documentation for it but most serious projects (incl. the introduction package, etc.) and pretty much all devs I know do it that way. 

Yes, thats the recommended structure. Take a look here for getting an idea: https://github.com/benjaminkott/bootstrap_package

**Comment by fnagel** [comment]
Closed, please open a new issue if needed.
