### ISSUE TITLE
Backlink from Show/Single

### ISSUE THREAD

**Issue by Renader** [fnagel/t3extblog#111]
hey,

sorry i'm not so familiar with fluid + php yet.. is it possible to link back from a single article to the overview? E.g. when i'm on an article of page 2, i want a button to go back to page 2 of my article listing. I dont want to link just to "/blog" since it may confuse the user.

best regards!

**Comment by fnagel** [comment]
I guess the easiest way to do so would be something like recomended for the news extension:

https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/Snippets/Index.html#improved-back-links

**Comment by fnagel** [comment]
Any feedback on this issueß

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
