### ISSUE TITLE
FlashMessage cached in TYPO3 7.3 and above

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#112]
It seems that when a FE user creates a new comment the success flash message is cached until next clear cache.

Steps to reproduce:
- Open private browser tab
- Create comment
- Open another private browser tab
- Open article page the comment was created
- Success flash message is shown

This is not the case in TYPO3 6.2. Seems this is a due to a change in TYPO3's caching / flash message handling. 

Update: This is not the case for default Extbase (Model) flash message errors, as these result in `.../comment/new` instead if the article URL only.

**Comment by fnagel** [comment]
@pvanhemmen Can you confirm this issue?

**Comment by fnagel** [comment]
I think I've found the reason: https://github.com/TYPO3/TYPO3.CMS/commit/70a7ed3a9a8e4462618c81a47122d6825ab7d70f#diff-c458c84cec13de48e7fabedab0c4e47aL114

**Comment by fnagel** [comment]
Seems like this is a core issue. Discussion on Slack: https://typo3.slack.com/archives/typo3-cms-coredev/p1452592222001699 and ff

**Comment by fnagel** [comment]
@all I've added a proposed fix for this issue in master. I've already tested in 6.2 which works fine (as expected, no changes here).

I plan to release a bugfix version (2.0.1) for this issue as it's a really bad thing when using t3extblog with TYPO3 7.6.x.

Please somebody confirm the issue and the fix in TYPO3 7.6!

**Comment by fnagel** [comment]
Related core issue: https://forge.typo3.org/issues/72703

**Comment by fnagel** [comment]
Temp fix include din version 2.0.1

**Comment by pvanhemmen** [comment]
For me, unfortunately this issue still exists. As a side note, it is also impossible to have new comments displayed without clearing the cache.

TYPO3 7.6.9
php 5.6

Will try to find a solution as well.

**Comment by fnagel** [comment]
Just noticed a few days ago there is an issue on specific servers (or server configs or opcode or ???). Please try latest master (incl. 48edcb9afd20e3a7881238d33e39ff7de51d9a52), test and give feedback!

**Comment by pvanhemmen** [comment]
Seems to be fixed with the current master. Thanx!

**Comment by fnagel** [comment]
Closing this as there hasn't been any reaction to the core bug since more than six years...
