### ISSUE TITLE
Apply AMP-Support?

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#113]
Hi!
That will be a long time thing... Google started to build a tool called "AMP" (https://www.ampproject.org/how-it-works/), to provides faster results on mobile search. Could be a big thing in the future.
Wordpress has a beta-plugin ready for that. Just for discussion.
Best!
Christoph

**Comment by fnagel** [comment]
Hey Christoph, I think this is something that should be built in in TYPO3 core or a specific extension. This is something that would need to utilize multiple core functionalities like doctype, header data, assets, etc and seems not to be related to t3extblogs purpose: blogging.

You probably should open a core ticket at forge!

**Comment by criwe** [comment]
You´re right. I´ve opened a ticket at forge.

**Comment by fnagel** [comment]
Link to core issue: https://forge.typo3.org/issues/72876

**Comment by fnagel** [comment]
TYPO3 will not include AMP, see https://forge.typo3.org/issues/72876#change-417382
