### ISSUE TITLE
Create dashboard module view

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#117]
Already in master and included in next release:

![dashboard png](https://cloud.githubusercontent.com/assets/116824/12714541/b0123a28-c8d5-11e5-800b-fb6373a71ced.png)

Ideas welcome!

**Comment by fnagel** [comment]
@criwe @pvanhemmen What do you think? Looks similar but not that nice in 6.2

**Comment by criwe** [comment]
@fnagel Great Idea, very nice :-) 
Well, I think future development should be fokused on 7 LTS. If it doesnt look that great in 6.2. -> so what.
Back to the dashboard: maybe some statistics could be nice, i.e. you´ve 73 Posts, 30 comments, 10 subscribers.

**Comment by fnagel** [comment]
I already plan to release a 7.x only version (current release date: end of life for 6.2), see https://github.com/fnagel/t3extblog/milestones/TYPO3%207.x%20only%20Version

Mainly because I'm tired of testing all releases and every feature in two installations. 

Statistics -- nice one. Will do asap!

**Comment by fnagel** [comment]
@criwe Added a basic statistic module in master.
