### ISSUE TITLE
Blog-Post changes issue for non-admin users

### ISSUE THREAD

**Issue by Moongazer** [fnagel/t3extblog#118]
Hey, can someone of you please confirm the following issues? I test it on 2 different TYPO3 systems with the current stable t3extblog 2.0.0 version and a fresh master-checkout from GitHub (2016-02-10).

**Description:**
It seems that changes made by non-admin users doens't effect the frontend. For example, if a non-admin "hide" or "un-hide" a Blog-Post record, the frontend is not updated. First I thought its a cache-issue, but also if no_cache=1 is set, the same happens. Clearing the pagecache or general cache doesn't help too. And then it becomes even more strange: If the admin perform a login, the changes made my non-admin users applied to the frontend immediately! Even if the backend-admin interface is not fully loaded (or still loading), you can refresh the blog-page frontend (browser F5 if you are fast) and the changes are applied. For me it seems that the admin-login triggers an internal event which updates the frontend!

**Further infos:**
- TYPO3 v. 6.2.17
- non-admin users working LIVE
- No useful informations can be found in the backend-log

**Reproduce:**
1) Create 3 Blog-Posts as admin (you dont need to add content-elements, just a Title like "Test-article" and a Category is enough) and set all Blog-Posts visible (un-hide). The frontend shows (list-view):
- Test-article-1
- Test-article-2
- Test-article-3

2) Login as non-admin user with full permissions on all t3extblog related elements and also content-elements etc! Now hide "Test-article-2". The frontend shows:
- Test-article-1
- Test-article-3

So far, it works as expected! Now try to un-hide "Test-article-2". Result: it doens't show up! If you hide another one (i.e. "Test-article-1"), it will also removed from the frontend, but un-hide it doesn't work, it does not show up again!

3) So the current state is: all 3 Blog-Posts are set to visible and SHOULD show up in the frontend, but only "Test-article-3" is shown (because we didn't touch it).

4) Login as admin, and during the backend is loading, go fast to your frontend and refresh the page. All 3 Blog-Posts get displayed like they should!

I REALLY hope someone of you can reproduce it, because this drives me crazy! :( And the t3extblog is useless so far because I can't give full admin-access to the people which are responsible to write blog-entries.

**Comment by fnagel** [comment]
First: thanks for this proper formatted and informative ticket -- I wish every ticket looks like this!

This behavior sounds like default TYPO3 caching when working with extension records. TYPO3 does not know where records in a folder are displayed and therefore can not clear the cache with auto magic. 

Two solutions for this:
1) Working with cache tags like EXT:news does -- not implemented in EXT:t3extblog yet
2) Using `TCEMAIN.clearCacheCmd` page TS config -- this works for every extension, see [here](https://docs.typo3.org/typo3cms/TSconfigReference/PageTsconfig/TCEmain/Index.html#clearcachecmd)

I will document 2) and just added an issue for 1), see #119

Anyway, this does not explain your issue that clearing the page cache in BE does not help when not logged in as an admin. This sounds like a more general issue with your configuration. Did you tried this in a plain instance, like the default introduction package?

**Comment by Moongazer** [comment]
Oh my god! Thank you SO MUCH!!! First: for this unbelievable fast response. Second: for this really easy solution! I didn't know about the `TCEMAIN.clearCacheCmd` commands, this seems to be very useful! Thanks a lot, its working like it should now!

Before I read your response, I added `options.clearCache.pages = 1` to the TSconfig inside the backend-usergroup. So the non-admin users was able to clear the whole page-cache which solved my issue (This was the best solution for me until your response). The strange thing is, that the clear-cache command on the sysfolder (where the blog records are stored) did not help, like you wrote. Only the clear-cache command on the blog-page (where the blog-plugin is located) helped.
Anyway, now I added the `TCEMAIN.clearCacheCmd` with the related page ID and everything is perfect! :)

**Comment by fnagel** [comment]
Not always that fast, but this time you're lucky :-D

Glad this worked for you! I will add a section in the documentation soon. Would be helpful if you would prove read it and give some feedback!

**Comment by Moongazer** [comment]
Yes, for sure!

**Comment by fnagel** [comment]
Documentation available in master, see : https://github.com/fnagel/t3extblog/commit/eef411d0bf1d796594375dad09b300be5c02eb0c

**Comment by fnagel** [comment]
Thanks for the feedback. Closing this here.

FYI: Latest master includes some new cache handling: auto clear cache when editing posts and improved performance due to more specific cache clearing when a new comment is added.
