### ISSUE TITLE
Preview function for hidden blog-post

### ISSUE THREAD

**Issue by Moongazer** [fnagel/t3extblog#120]
**Feature-Request:**

Because the backend-editing looks very different from the final frontend-view of a blog-article, my customer "writes his article live". Means: he switch it to visible and adds the content elements one after another to see the final result, sometimes over days. For the website visitors this must be weird, if he stops writing on an article over night but still let it online. Especially because people get informed by RSS if a new article supposed to be published.

Maybe a simple solution could be to add 2 query parameters to the frontend blog-page, the ID of the new post and something like preview=true?! (Plus be-user permission check or so to display the hidden article). Or is there such a feature/solution already which I missed?

**Comment by fnagel** [comment]
Please, take a look in the documentation: https://docs.typo3.org/typo3cms/extensions/t3extblog/AdministratorManual/Index.html#preview-blog-posts

Make use of the default TYPO3 preview functionality.

**Comment by Moongazer** [comment]
Oh sorry I missed that!

But anyway, it doesn't work for me. I added the code from the manual (6.2, and to try also for 7.2) everywhere: in the main-template config for t3extbase, in the TSconfig of the blogpage and also in the TSconfig of the sysfolder. Even the settings.previewHiddenRecords=1 config had no effect, all hidden recordsets did not show up on the blogpage.
ONLY if I **manually** added this parameter to the blogpage: `/blog.html?tx_t3extblog_blogsystem[previewPost]=7` (where 7 is a hidden blog-post) the post showed up as single view. If I log out the be-user, an error is thrown as expected (Oops, an error occurred). So this seems to work.

Just to avoid a miss-understanding: should the hidden blog-posts also show up in the list-view (`/blog.html`) if a be-user is logged in? If not, where can the be-user get the above URL with the preview-parameter from?

**Comment by fnagel** [comment]
> should the hidden blog-posts also show up in the list-view (/blog.html) if a be-user is logged in?

No, you need to use the "save and preview" button 

This is a default TYPO3 feature for pages and could be used for extensions (if implemented). I guess this is not as clear as I thought and we should add some info in the documentation.

![image](https://cloud.githubusercontent.com/assets/116824/13206523/9dfb24be-d8ff-11e5-9adc-4cef444040e9.png)


Screenshot when editing a (hidden) blog post.

**Comment by Moongazer** [comment]
How embarrassing, I didn't thought about this function because I never use it (Insead I always force reloading with shift+F5 to avoid cache issues).

Anyway, I tried "save and preview" on a hidden blog-post, but it results in an 404 error, because the ID of my storage sys-folder is given. Both (the sys-folder and the blog-page) have `tx_t3extblog.singlePid = 8` inside the TSconfig, where ID 8 is my blog-page (I've also tried to add the >7.2 part without success).

Info: TYPO3 v6.2 with RealURL enabled

**Comment by fnagel** [comment]
Which version are you using? There was an issue in TYPO3 6.2 which is fixed in master only: https://github.com/fnagel/t3extblog/commit/ca6b19e8c9f11ced209a664fd0118425cca15344

**Comment by Moongazer** [comment]
Thank you very much for your advice, this fix solved the issue!

**Comment by fnagel** [comment]
Glad it worked for you!

Please consider a donation: http://www.felixnagel.com/donate
