### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#123]
Make sure this extension works as expected with PHP7.

http://php.net/manual/en/migration70.php

**Comment by fnagel** [comment]
@criwe @pvanhemmen @madaxel 

Any feedback on this? Did somebody already tested t3extblog with PHP7?

**Comment by fnagel** [comment]
I just tested this. Needs some fixes. I've updated dependencies accordingly.

**Comment by criwe** [comment]
@fnagel no, I haven´t a php7 environment yet. Waiting for my hoster...

**Comment by fnagel** [comment]
Adjusted some method declarations to match PHP 7.x specifications. Tested successfully in PHp 7.0 environment after that. Please re-open this issue if needed!
