### ISSUE TITLE
Feature request: comments allowed until infinity

### ISSUE THREAD

**Issue by Moongazer** [fnagel/t3extblog#129]
By default, comments will be disabled [after one month](https://github.com/fnagel/t3extblog/blob/master/Classes/Domain/Model/Post.php#L333) if TS `comments.allowedUntil` is not set.

To permanent allow comments for blog-posts, so far I need to set `comments.allowedUntil = +100 years`, but it would be better to have something like `comments.allowedUntil = 0` (0 for infinity).

Just as idea for future releases, it's not very important because the workaround is working good :-)

**Comment by fnagel** [comment]
Sounds like a good idea and shouldn't be that hard to implement. 

Thanks for you suggestion!

**Comment by fnagel** [comment]
Mhh, according to documentation (and the code, which I just checked again) using `comments.allowedUntil = 0` for disabling autoclose should already be possible.

See: https://github.com/fnagel/t3extblog/search?l=php&q=allowedUntil&utf8=%E2%9C%93

**Comment by Moongazer** [comment]
Strange, yesterday it was not working after I changed the date of an article back to 2008. Maybe I run into a caching problem as so often -.- But you're right, I just tried it again and it's working already with `allowedUntil = 0`. Sorry!
