### ISSUE TITLE
Feature request: option to adding RSS link to page-header

### ISSUE THREAD

**Issue by Moongazer** [fnagel/t3extblog#130]
As soon as the "T3Blog Extbase: RSS" plugin is placed somewhere inside the page **or** the "T3Extblog: Rss setup (t3extblog)" template is included, it would be great if the RSS link will automatically added to the page header:

```
page.headerData {
  10 = TEXT
  10.value = <link rel="alternate" type="application/rss+xml" title="{$plugin.tx_t3extblog.settings.blogName}" href="{$BASEURL}/blog/rss/" />
  # find out the correct href somehow
}
```

**Comment by fnagel** [comment]
I think you misunderstand the purpose of both the RSS plugin and the TS file. The plugin renders the XML output and needs to be used with the TS file on one page -- without anything else!

Adding headerData by PHP when the RSS plugin is used ANYWHERE in the TYPO3 instance seems unreasonable complicated considering multiple domain setups or multiple RSS feeds. This should be done by TS. It's easy by using:

`````
page.headerData {
		100 =  TEXT
		100.wrap = <link rel="alternate" type="application/rss+xml" title="Blog RSS Feed" href="|" />
		100.typolink {
			parameter = 123
			returnLast = url
			forceAbsoluteUrl = 1
		}
	}
````

**Comment by Moongazer** [comment]
Hm makes sense. Thank you for the DOC update, that's useful.
