### ISSUE TITLE
Preview not working: "Ooooops error occurred"

### ISSUE THREAD

**Issue by dsgrafiniert** [fnagel/t3extblog#134]
TYPO3: 7.6.9, t3extblog: 2.2.1

Constants on root level: 
```
plugin.tx_t3extblog.settings.blogName = ...
plugin.tx_t3extblog.persistence.storagePid = 33
plugin.tx_t3extblog.settings.emailFrom = ...
plugin.tx_t3extblog.settings.emailTo = ...
plugin.tx_t3extblog.settings.blogsystem.pid = 32
plugin.tx_t3extblog.settings.subscriptionManager.pid = 34
plugin.tx_t3extblog.settings.twitterName = ...
```

Page TSconfig in data sysfolder:
```
TCEMAIN.preview {
        tx_t3blog_post {
                previewPageId = 32
                useDefaultLanguageRecord = 1
                fieldToParameterMap {
                        uid = tx_t3extblog_blogsystem[previewPost]
                }
                additionalGetParameters {
                        tx_t3extblog_blogsystem.controller = Post
                        tx_t3extblog_blogsystem.action = preview
                }
        }
}
```

If I use the "Save and View Page" button on the post, the correct preview page opens (PID 32) but the post is not shown. Instead, their is an error message "Ooops an error occured". Even if I enable the debugging options in the Install Tool, the error message does not change.

Thanks in advance for looking into this. Keep up the great work.

**Comment by fnagel** [comment]
Hard to say what's wrong here without debugging. Try changing the TYPO3 error configuration in order to get a full stack trace what's wrong here.

Have you set the `[FE][disableNoCacheParameter]` config?

**Comment by dsgrafiniert** [comment]
Thanks for the reply. `[FE][disableNoCacheParameter]` is not set.

But I got the Debug Output now:

``
Uncaught TYPO3 Exception
Preview not allowed. 

Exception thrown in file
/var/www/html/barcamp/typo3conf/ext/t3extblog/Classes/Controller/PostController.php in line 234.

21 TYPO3\T3extblog\Controller\PostController::previewAction(4)
20 call_user_func_array(array, array)

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00281:         if (!$validationResult->hasErrors()) {
00282:             $this->emitBeforeCallActionMethodSignal($preparedArguments);
00283:             $actionResult = call_user_func_array(array($this, $this->actionMethodName), $preparedArguments);
00284:         } else {
00285:             $methodTagsValues = $this->reflectionService->getMethodTagsValues(get_class($this), $this->actionMethodName);

19 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::callActionMethod()

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00174:             $this->initializeView($this->view);
00175:         }
00176:         $this->callActionMethod();
00177:     }
00178: 

18 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::processRequest(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php:
00084:             $controller = $this->resolveController($request);
00085:             try {
00086:                 $controller->processRequest($request, $response);
00087:             } catch (\TYPO3\CMS\Extbase\Mvc\Exception\StopActionException $ignoredException) {
00088:             }

17 TYPO3\CMS\Extbase\Mvc\Dispatcher::dispatch(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php:
00067:         /** @var $response \TYPO3\CMS\Extbase\Mvc\ResponseInterface */
00068:         $response = $this->objectManager->get(\TYPO3\CMS\Extbase\Mvc\Web\Response::class);
00069:         $this->dispatcher->dispatch($request, $response);
00070:         return $response;
00071:     }

16 TYPO3\CMS\Extbase\Mvc\Web\FrontendRequestHandler::handleRequest()

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00204:         $requestHandler = $requestHandlerResolver->resolveRequestHandler();
00205: 
00206:         $response = $requestHandler->handleRequest();
00207:         // If response is NULL after handling the request we need to stop
00208:         // This happens for instance, when a USER object was converted to a USER_INT

15 TYPO3\CMS\Extbase\Core\Bootstrap::handleRequest()

/var/www/typo3_src-7.6.9/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00191:     {
00192:         $this->initialize($configuration);
00193:         return $this->handleRequest();
00194:     }
00195: 

14 TYPO3\CMS\Extbase\Core\Bootstrap::run("", array)
13 call_user_func_array(array, array)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
07314:                         $content,
07315:                         $conf
07316:                     ));
07317:                 } else {
07318:                     $this->getTimeTracker()->setTSlogMessage('Method "' . $parts[1] . '" did not exist in class "' . $parts[0] . '"', 3);

12 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::callUserFunction("TYPO3\CMS\Extbase\Core\Bootstrap->run", array, "")

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php:
00038:         }
00039:         $this->cObj->includeLibs($conf);
00040:         $tempContent = $this->cObj->callUserFunction($conf['userFunc'], $conf, '');
00041:         if ($this->cObj->doConvertToUserIntObject) {
00042:             $this->cObj->doConvertToUserIntObject = false;

11 TYPO3\CMS\Frontend\ContentObject\UserContentObject::render(array)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

10 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\UserContentObject, array)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

9 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("USER", array)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:
03564:                             break;
03565:                         case 'FUNC':
03566:                             $incContent = $INTiS_cObj->cObjGetSingle('USER', $INTiS_config[$INTiS_key]['conf']);
03567:                             break;
03568:                         case 'POSTUSERFUNC':

8 TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::INTincScript_process(array)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:
03509:             $INTiS_config = $this->config['INTincScript'];
03510:             $this->INTincScript_includeLibs($INTiS_config);
03511:             $this->INTincScript_process($INTiS_config);
03512:             // Check if there were new items added to INTincScript during the previous execution:
03513:             $INTiS_config = array_diff_assoc($this->config['INTincScript'], $INTiS_config);

7 TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::recursivelyReplaceIntPlaceholdersInContent()

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:
03475:         }
03476: 
03477:         $this->recursivelyReplaceIntPlaceholdersInContent();
03478:         $this->getTimeTracker()->push('Substitute header section');
03479:         $this->INTincScript_loadJSCode();

6 TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::INTincScript()

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Http/RequestHandler.php:
00230:         if ($this->controller->isINTincScript()) {
00231:             $this->timeTracker->push('Non-cached objects', '');
00232:             $this->controller->INTincScript();
00233:             $this->timeTracker->pull();
00234:         }

5 TYPO3\CMS\Frontend\Http\RequestHandler::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/var/www/typo3_src-7.6.9/typo3/sysext/core/Classes/Core/Bootstrap.php:
00300: 
00301:         // Execute the command which returns a Response object or NULL
00302:         $this->response = $requestHandler->handleRequest($request);
00303:         return $this;
00304:     }

4 TYPO3\CMS\Core\Core\Bootstrap::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/var/www/typo3_src-7.6.9/typo3/sysext/frontend/Classes/Http/Application.php:
00076:     public function run(callable $execute = null)
00077:     {
00078:         $this->bootstrap->handleRequest(\TYPO3\CMS\Core\Http\ServerRequestFactory::fromGlobals());
00079: 
00080:         if ($execute !== null) {

3 TYPO3\CMS\Frontend\Http\Application::run()

/var/www/typo3_src-7.6.9/index.php:
00031: call_user_func(function () {
00032:     $classLoader = require rtrim(realpath(__DIR__ . '/typo3'), '\\/') . '/../vendor/autoload.php';
00033:     (new \TYPO3\CMS\Frontend\Http\Application($classLoader))->run();
00034: });

2 {closure}()
1 call_user_func(Closure)

/var/www/typo3_src-7.6.9/index.php:
00032:     $classLoader = require rtrim(realpath(__DIR__ . '/typo3'), '\\/') . '/../vendor/autoload.php';
00033:     (new \TYPO3\CMS\Frontend\Http\Application($classLoader))->run();
00034: });
``

I am logged in to the Backend as admin, when the error occurs.

**Comment by fnagel** [comment]
`Preview not allowed.`

It seems your user is not recognized as a BE user. I've pushed a fix for non admin users a few weeks ago (tested this in 7.6 and 6.2) and just tested this again in a 7.6.9  -- should work as expected.

Not quite sure what's the issue here. How does the generated link looks like? Should be something like:

`index.php?id=PAGE_UID&no_cache=1&tx_t3extblog_blogsystem%5BpreviewPost%5D=POST_UID&tx_t3extblog_blogsystem%5Bcontroller%5D=Post&tx_t3extblog_blogsystem%5Baction%5D=preview`

**Comment by dsgrafiniert** [comment]
The link is `index.php?id=32&no_cache=1&tx_t3extblog_blogsystem%5BpreviewPost%5D=4&tx_t3extblog_blogsystem%5Bcontroller%5D=Post&tx_t3extblog_blogsystem%5Baction%5D=preview`
 - thus, it seems OK to me.

However, even with the version from Git, it does not work. I, for the moment, have commented out 
```
if (!GeneralUtility::isValidBackendUser()) {
    throw new \Exception('Preview not allowed.');
}
```
for the moment. Maybe it would be useful to have a Constant that enables the preview even if backend users are not logged in.

What comes into my mind: I have a HTTPS-connection to my website per default. Maybe the cookie with the Backend Session is not share between different tabs, because of any HTTPS security policy?!

Thanks for your help so far!

**Comment by fnagel** [comment]
There had been a configuration option in TS but it had issues with non admin users, see #127 
I fixed that (and, as mentioned before, tested it in 6.2 and 7.6) in this commit: https://github.com/fnagel/t3extblog/commit/f61354c29b1dbd90736f48927dec7927f329ab40

Wrong cookie domain config (`$GLOBALS['TYPO3_CONF_VARS']['SYS']['cookieDomain']`) could be an issue! Good idea, make sure to check this!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Comment by mrvoss** [comment]
Same problem here. The error message after "Oops, an error occurred!", in my case, is "Serialization of 'Closure' is not allowed". The culprit here is the following:

* `typo3_src-7.6.11/typo3/sysext/fluid/Classes/ViewHelpers/FormViewHelper.php:246` tries to `serialize($request->getArguments())`, of which `$post` is one
* `\TYPO3\T3extblog\Domain\Model\Post::__sleep()` is getting called
* after exiting `__sleep()`, there exception is thrown

Meaning that one or more properties of `$post` contain a closure which cannot be serialized. Interestingly, there is already code in `__sleep()` that seems to address this problem:

```
// fix to make sure we are able to use forward in controller
unset($properties['categories']);
unset($properties['subscriptions']);
```

If I add a few more properties:

```
// fix to make sure we are able to use forward in controller
unset($properties['categories']);
unset($properties['subscriptions']);
unset($properties['commentRepository']);
unset($properties['content']);
unset($properties['previewImage']);
```
the error goes away, and the preview page is shown.

There should be a better, more general way to fix this problem (do not lazy load? change the fluid templates?) - unfortunately, I couldn't figure one yet.

**Comment by mrvoss** [comment]
Looking at this again, I think that "Serialization of 'Closure' is not allowed" is a different problem than "Preview not allowed." - albeit both happen when trying to preview a hidden blog entry as a non-admin user. My diagnostics for former still apply, though.

Should there be a separate issue for "Serialization of 'Closure' is not allowed" then?

**Comment by fnagel** [comment]
Thanks for the detailed report! I agree, this seems to be another issue so creating a new issue seems the best idea. 

I'm pretty busy right now, but I will try to test this and give feedback asap. 


> both happen when trying to preview a hidden blog entry as a non-admin user

Only for non admin users? I would assume the serialization issue should occur in every case.

**Comment by fnagel** [comment]
Created a new issue for this, see #155
