### ISSUE TITLE
Add option "noindex" to tag- and categorie sites

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#135]
Hi Felix!
The tag- and categorie pages cause duplicate content (seo-issue), because the same articles can be found in different urls. 
So it would be great to add an option (i.e. constants) to active a "noindex"-metatag for that pages.
Thx!
Best,
Christoph

**Comment by fnagel** [comment]
Seems like a good idea. 

`<meta name="robots" content="noindex,follow">` for category, tag and author view. Any objections?

**Comment by criwe** [comment]
No, that should cover all "problem"-views.

**Comment by fnagel** [comment]
Reopen this as closed accidentally by pushing a non public branch.
