### ISSUE TITLE
Questions re news transfer and RSS import

### ISSUE THREAD

**Issue by kludikovsky** [fnagel/t3extblog#140]
Out of curiosity I have two questions.

1) Is there a possibility to import/transfer/copy elements from Goerg Ringer's [news-extension](https://docs.typo3.org/typo3cms/extensions/news/stable/singlehtml/Index.html#document-Index) (NOT tt_news) ?

2) Is there an option to load content from other RSS sources like with the [amt_feed_importer](https://typo3.org/extensions/repository/view/amt_feed_importer)

**Comment by fnagel** [comment]
1) No
2) Probably, when amt_feed_importer implements an interface

**Comment by kludikovsky** [comment]
thx
