### ISSUE TITLE
This page contains the following errors

### ISSUE THREAD

**Issue by typo3ua** [fnagel/t3extblog#141]
Hello, everybody!
I did all that writes at [manual...](https://docs.typo3.org/typo3cms/extensions/t3extblog/AdministratorManual/Index.html#administration-rss) but get the error...
~~
This page contains the following errors:

error on line 39 at column 102: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.

Testblog http://domain.ltd/t3/index.php?id=3 Sat, 20 Aug 2016 13:45:11 +0000 Sat, 20 Aug 2016 13:45:11 +0000 t3extblog extension for TYPO3 The standard chunk of Lorem Ipsum used since the 1500s is reproduced... Fri, 19 Aug 2016 17:34:00 +0000 http://domain.ltd/t3/index.php?id=3&tx_t3extblog_blogsystem%5Bpost%5D=9&tx_t3extblog_blogsystem%5Bday%5D=19&tx_t3extblog_blogsystem%5Bmonth%5D=08&tx_t3extblog_blogsystem%5Byear%5D=2016&tx_t3extblog_blogsystem%5Baction%5D=show&cHash=24289e8d9e5a00556a1fc831bb961f70 post-9
~~
What, I did is wrong?

**Comment by fnagel** [comment]
Seems this is about using RSS, right?

Try using EXT:realurl or escape the links within the RSS xml file.

**Comment by typo3ua** [comment]
Yes it is, I use RSS and without EXT:realurl

**Comment by fnagel** [comment]
Is this still an issue?

**Comment by typo3ua** [comment]
Thanks
