### ISSUE TITLE
Validation failed while trying to call TYPO3\T3extblog\Controller\PostController->showAction().

### ISSUE THREAD

**Issue by typo3ua** [fnagel/t3extblog#143]
I get error:

![comment_error](https://cloud.githubusercontent.com/assets/638022/17892158/893f46e8-6948-11e6-9f15-cd462260e8dd.png)

I noticed this error than when the comment is added to the post.
Where is have the comment, content of post disappears and there is only the error:
``
Validation failed while trying to call TYPO3\T3extblog\Controller\PostController->showAction().
``
![multicolumns_error_0](https://cloud.githubusercontent.com/assets/638022/17892432/ed07ea80-6949-11e6-85c7-3b61b8437a01.png)

**Comment by fnagel** [comment]
https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md

**Comment by typo3ua** [comment]
*I set up all default, without changes
**Recommended page structure
![structure_for_your_blog](https://cloud.githubusercontent.com/assets/638022/17943043/7860c874-6a42-11e6-9795-2e3a2e100d5f.png)
**Include static
![includestatic](https://cloud.githubusercontent.com/assets/638022/17943107/b81ff0fc-6a42-11e6-89de-af3560fd1a05.png)
**The Post of blog in which does not have a comments
![comment_error](https://cloud.githubusercontent.com/assets/638022/17892158/893f46e8-6948-11e6-9f15-cd462260e8dd.png)
**The Post of blog in which have a comments.
![multicolumns_error_0](https://cloud.githubusercontent.com/assets/638022/17892432/ed07ea80-6949-11e6-85c7-3b61b8437a01.png)

**Comment by fnagel** [comment]
Thanks, very detailed -- I love it :-)

Mhh, this looks like you really run into a but. I assume it could be related to having additional plugins on the page. Would you please try to disable the last comments and last posts plugins on that page? Please try if any combination works or if it works with the blogsystem plugin only at least.

**Comment by typo3ua** [comment]
At the moment I only test your EXT:t3extblog. On the page and the system installed only your EXT:t3extblog. I tried different options and combinations.

Normal Column | Right Column
------------ | -------------
T3Blog Extbase: Blogsystem | T3Blog Extbase: LatestPosts
 | T3Blog Extbase: LatestComments
 | T3Blog Extbase: Archive
 | T3Blog Extbase: Categories
------------ | -------------
T3Blog Extbase: Blog Subscription Form |

**Comment by fnagel** [comment]
What I want you to do is to disable the t3extblog plugins on the right column.

**Comment by typo3ua** [comment]
Normal Column | Right Column
------------ | -------------
T3Blog Extbase: Blogsystem | T3Blog Extbase: LatestPosts
 | 
- Title Item post blog one...<br/>
- Title Item post blog two...<br/>
- Title Item post blog three...<br/>
- Title Item post blog four...<br/> | 
 | 
 |  <== footer

**If the entries of comments are hidden (disabled), error missing. I do not see error.**

Normal Column | Right Column
------------ | -------------
T3Blog Extbase: Blogsystem | T3Blog Extbase: LatestPosts
 | 
Validation failed while trying to call TYPO3\T3extblog\Controller\PostController->showAction(). | 
 | 
 |  <== footer

**If the entries of comments are enabled, I see error.**

**Comment by fnagel** [comment]
Sorry but I hardly understand what you try to tell me here. From what I understand it seems this is some side effect of what ever. Not sure how to help here.

Can you provide me an access to the installation? With BE access? This would really help to identify the issue.

**Comment by typo3ua** [comment]
I'm sent access on your email, which I have taken from a profile.

**Comment by fnagel** [comment]
Got it. Already replied!

**Comment by typo3ua** [comment]
I set default configuration

**Comment by typo3ua** [comment]
Amazingly! After your intervention errors are not watching. Now we need to locate the problem.
----
- You are added comment with form on the frontend page - none error
- I added comment in backend - get error
----
So, the error appears when the comment added in the backend. I checked.

**Comment by fnagel** [comment]
Can you check if all DB fields are set? Perhaps post a dump of that comment row.

**Comment by typo3ua** [comment]
I'm so sorry but I do not have access to DB now.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by typo3ua** [comment]
Thanks!

**Comment by DarthRosenberg** [comment]
Hello,
I have exactly the same problem, do you have any solution yet?
Typo3 7.6.28, t3extblog 3.0.2, haven't done any configuration except Fluid-Template-Paths.
Thanks in advance!

**Comment by fnagel** [comment]
@DarthRosenberg This bug report was for the 2.x version of t3extblog. Please open a new ticket for your issue!

**Comment by DarthRosenberg** [comment]
Ok, thanks.
