### ISSUE TITLE
T3Blog Extbase: Blogsystem Fatal Error

### ISSUE THREAD

**Issue by arunspawoz** [fnagel/t3extblog#145]
I've a list and detail view for my blog. When I click on an item from the list view, I got an error like this in frontend in the detail view.

#1: PHP Catchable Fatal Error: Argument 1 passed to TYPO3\CMS\Backend\Backend\Avatar\Avatar::getImage() must be of the type array, boolean given

Any idea? Thanks.

**Comment by fnagel** [comment]
https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md

**Comment by arunspawoz** [comment]
TYPO3 version 7.6.10;
Extension version: 2.2.1

Stepsto reproduce:

- First I added the "Latest Post"' view in my list page.
- Added "Blog system" view in the detail view.

When I click on the latest post item, it redirects to detail view. There I faced this error.

Thanks.
![error](https://cloud.githubusercontent.com/assets/20816321/18201526/4d89a2c8-7128-11e6-8ccf-a94b0287c209.png)

**Comment by arunspawoz** [comment]
Issue Fixed...In backend TCA the author field was empty.

**Comment by fnagel** [comment]
Thanks for reporting what the issue was. Seems the TCA validation should be changed as an author is required. Will be changed soon!
