### ISSUE TITLE
Problem with RealURL 2.0.15??

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#146]
Hi!
I´ve just update RealURL to version 2.0.15 due to a security update.
After that, same strange behavior occured: the first article I´ve called was show on EVERY url (except categorie sites), so all articles are the same, just different urls. I´ve tried a fews things (other realurl-config, clear (realurl)cache...), but still the same. "normal" pages work.

Temporary solution: config.no_cache = 1...

Maybe someone can test it with tx_news or something, so we know its an t3extblog or realurl problem.
Best

**Comment by fnagel** [comment]
Probably related: https://github.com/dmitryd/typo3-realurl/issues/244

**Comment by fnagel** [comment]
https://twitter.com/dmitryd/status/776767782784536576
https://twitter.com/dmitryd/status/776768227061948416
https://twitter.com/dmitryd/status/776768445631361024

**Comment by fnagel** [comment]
Some info from testing different versions:

Works? | TYPO3 Version | FE cHashIncludePageId = true | RealUrl Version | Make use of `reqCHash()`
------------ | ------------- | ------------- | ------------- | -------------
No | 7.6.11 | yes | 2.0.14 | no
No | 7.6.11 | yes | 2.0.15 | no
No | 7.6.11 | yes | 2.0.15 | yes

**Comment by fnagel** [comment]
Seems `reqCHash()` is needed but admins are no longer able to display posts (see https://github.com/dmitryd/typo3-realurl/issues/244#issuecomment-245848293). Configure `pageNotFoundOnCHashError` to 0 helps (and is a little dangerous!) but initial rendering needs to be done without BE login no matter what.

**Comment by criwe** [comment]
- the problem discribed above was before the TYPO3 6.2.17/7.6.11 update (and is the same after)
- I´ve got similar problems with tx_news and TYPO3 6.2.17 (in that case a 404 error occurs when calling the detailview). I´ve tried to get RealURL and tx_news running in a 7.6-system, but RealURL refuses to creats a proper autoconfigfile...

**Comment by fnagel** [comment]
Reopen this as closed accidentally by pushing a non public branch.
