### ISSUE TITLE
Wrong language parameter in BlogSubscriberOptinMail.txt layout

### ISSUE THREAD

**Issue by mrvoss** [fnagel/t3extblog#151]
For generating links to the blog and the subscription manager, BlogSubscriberOptinMail.txt uses subscriber.sysLanguageUid, which is initialized from $GLOBALS['TSFE']->sys_language_uid. This generates links with the proper L parameter - good.

However, BlogSubscriberOptinMail.txt uses the Email.txt layout, which generates another link that uses **post**.sysLanguageUid - and post, in this context, is not set. So this generates a link with an empty == wrong L parameter - bad.

Suggested fix: not sure yet - maybe you have an idea? Thanks!

**Comment by mrvoss** [comment]
I think the cleanest way to fix this is to just remove the layout from all mail templates. The Email.txt layout only contains a - possibly wrong - link to the blog, which all mail templates already contain - with a correct link - one way or the other.

What do you think?

**Comment by fnagel** [comment]
Sorry for the late response. No time for actual testing yet. Looking at the code itself it seems you're right: as the blog post subscription isn't bound to a post, it's missing the fluid variable in that context.

> I think the cleanest way to fix this is to just remove the layout from all mail templates. The Email.txt layout only contains a - possibly wrong - link to the blog, which all mail templates already contain - with a correct link - one way or the other.

Introducing layouts for emails was done to make it easier for integrator to customize the email layout (thinking of header, content part and footer). 

So, I'm against removing the email layout but I thought about a general language variable to be used in such cases. What do you think?

**Comment by mrvoss** [comment]
A general language variable was the second option I thought about. I did not mention it because it is way harder to implement (you have to adapt all controllers) and test than just removing the link from the layout. But it would be the proper way to fix this. Go for it.

**Comment by fnagel** [comment]
Issue confirmed and fixed. Will be part of the next release. 

Thanks for reporting!

**Comment by fnagel** [comment]
Reopen this as closed accidentally by pushing a non public branch.
