### ISSUE TITLE
post limitations

### ISSUE THREAD

**Issue by eiszeit** [fnagel/t3extblog#152]
Hi, would it be possible to limit posts per page? Maybe there is a TS solution for this, so I can get individual numbers of posts per page?

Thanks

**Comment by eiszeit** [comment]
I thought 
plugin.tx_t3extblog.settings.blogsystem.posts.paginateitemsPerPage = 1
would do the trick, but it didn´t
Any ideas?

**Comment by fnagel** [comment]
Pagnination widget is a fluid default so this is more like something to be solved in general not for t3extblog in specific. Perhaps asking on slack would help.

Your idea is good. I'm using TS to configure the pagination VH, see https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Partials/Post/List.html#L5

So, you basically need to configure `itemsPerPage` based on which page you're currently using. This could be done by using TS conditions. Not sure if the widget will work like that, but it's wort a try.

Reference:
https://fluidtypo3.org/viewhelpers/fluid/7.6.0/Widget/PaginateViewHelper.html
https://docs.typo3.org/typo3cms/TyposcriptReference/Conditions/Reference/Index.html#globalvar

Please note: `t3b:widget.paginate` is just an extension to `f:widget.paginate`

**Comment by eiszeit** [comment]
Thanks for the tip, solved it with
plugin.tx_t3extblog.settings.blogsystem.posts.paginate.itemsPerPage = 1

**Comment by fnagel** [comment]
Yeah! Good to know you solved your issue.

Any chance to post your TS snippet so others could see how you solved this?

**Comment by eiszeit** [comment]
Yes, already did, TS setup:

plugin.tx_t3extblog.settings.blogsystem.posts.paginate.itemsPerPage = 1
