### ISSUE TITLE
Preview does not work: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#155]
> Taken from https://github.com/fnagel/t3extblog/issues/134#issuecomment-252597201

The culprit here is the following:
- `typo3_src-7.6.11/typo3/sysext/fluid/Classes/ViewHelpers/FormViewHelper.php:246` tries to `serialize($request->getArguments())`, of which `$post` is one
- `\TYPO3\T3extblog\Domain\Model\Post::__sleep()` is getting called
- after exiting `__sleep()`, there exception is thrown

Meaning that one or more properties of `$post` contain a closure which cannot be serialized. Interestingly, there is already code in `__sleep()` that seems to address this problem:

```
// fix to make sure we are able to use forward in controller
unset($properties['categories']);
unset($properties['subscriptions']);
```

If I add a few more properties:

```
// fix to make sure we are able to use forward in controller
unset($properties['categories']);
unset($properties['subscriptions']);
unset($properties['commentRepository']);
unset($properties['content']);
unset($properties['previewImage']);
```

the error goes away, and the preview page is shown.

There should be a better, more general way to fix this problem (do not lazy load? change the fluid templates?) - unfortunately, I couldn't figure one yet.

**Comment by fnagel** [comment]
> both happen when trying to preview a hidden blog entry as a non-admin user

Only for non admin users? I would assume the serialization issue should occur in every case.

**Comment by mrvoss** [comment]
The error also occurs for admin users.

I am using the latest GitHub version (d988af7a9e471ce2aaf5ba917663584ccd7d6a77) with some of my latest patches (which unfortunately don't seem to be available in a merged version).

By the way: you were mentioning fixes implemented in the next version a few times. Are these versions (like a 3.0.0-dev) available somewhere?

**Comment by fnagel** [comment]
Thanks for the info. 
I'm not able to reproduce this in my test setup.

You might have noticed there are no newer commits at all and there is a reason for that. Please send me an email, see http://felixnagel.com/contact.

**Comment by mrvoss** [comment]
Does the hidden post to preview in your test setup have
* preview mode: auto
* a preview image
* at least one (published) comment
* at least one content element (in my test setup, I have 6 fluid_styled_content Text & Media elements with various images, video, enlarge on click, etc.)
?

**Comment by fnagel** [comment]
> preview mode: auto
> a preview image
> at least one content element

Yes

> at least one (published) comment

IMO this does not make much sense (as preview is for testing before releasing a post) but I've tested this as well without issues.

>  6 fluid_styled_content Text & Media elements

Never tested this extension with EXT:fluid_styled_content. Might be worth to test this in depth.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
