### ISSUE TITLE
Adding plugins using TypoScript

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#158]
How to use a t3extblog plugin using TS.

**Comment by fnagel** [comment]
Something like this shoud work (untested):

````
lib.blogMenu = USER
lib.blogMenu {
	userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
	extensionName = T3extblog
	pluginName = Categories
	vendorName = TYPO3

	settings < plugin.tx_t3extblog.settings
}
````

This could be rendered in Fluid using the cObject VH: https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/CObject.html

Some more info on this topic: https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/IntegrationWithTypoScript/Index.html

**Comment by cmsprojekte** [comment]
Works for me! Thanks!

**Comment by fnagel** [comment]
I'm glad to hear :-D

Support and development is a one man project and fully donw in my free time.
Please consider a donation: http://www.felixnagel.com/donate/
