### ISSUE TITLE
how can I add a class to the blog images?

### ISSUE THREAD

**Issue by eiszeit** [fnagel/t3extblog#159]
In order to make images responsive, I would like to add a class to images like: classs="responsive". Is that possible?

**Comment by fnagel** [comment]
Depends on how your template looks like. 

Default (1) is using a TypoScript lib (2) for rendering "real" responsive images (with srcset or similar, depending on your config) by using the TYPO3 configuration for CSC images. This way we reuse what you already configured for your default TYPO3 content elements!

Take a look on what is configured for `tt_content.image.20` in TypoScript as this is reused in t3extblog's TypoScript (3).


(1) https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Partials/Post/PreviewImage.html#L6
(2) https://github.com/fnagel/t3extblog/blob/master/Configuration/TypoScript/setup.txt#L339-L361
(3) https://github.com/fnagel/t3extblog/blob/master/Configuration/TypoScript/setup.txt#L348-L351

**Comment by eiszeit** [comment]
I tried something like this:
tt_content.image.20.1.params = class = "a" but without success

I also tried to add this:
<f:case default="TRUE">
                <f:render partial="Image" arguments="{files: images, data: data, class: 'img-responsive'}"/>
            </f:case>

Other than that I have not added any own Typoscript.

**Comment by fnagel** [comment]
The correct ordering of the TS statements may be important here. Try to check within the TypoScript object browser (template module in BE).

You could also directly change the TS of the lib:
````
lib.tx_t3extblog.responsiveImage {
	...

	params = class="test-class"

	...
}
````


`<f:render partial="Image" arguments="{files: images, data: data, class: 'img-responsive'}"/>

Will definitely not work without changing the partial itself.

**Comment by eiszeit** [comment]
I have the typoscrict just on the plugin page, I think that should do it?
your suggestion is not working for me, but it´s looking okay

**Comment by fnagel** [comment]
Hard to say from what you say. Did you copy the TS? Using static template? Overwriting the static template? This seems like a TS configuration issue to me.

Anyway, there is no need to use the TS lib at all. You could go ahead and adjust the templates to use a normal image VH. Take a look at this older version: https://github.com/fnagel/t3extblog/blob/28ddeed190f74774b505aa2ea4422350bcd00ec0/Resources/Private/Partials/Post/PreviewImage.html

**Comment by eiszeit** [comment]
First of all, thank you for your patience Felix.

I just saw your hint: 

lib.tx_t3extblog.responsiveImage {
	...

	params = class="test-class"

	...
}

works fine in the list view, but not in the single post view. Any suggestions how I add the class there?

**Comment by fnagel** [comment]
Single post view depends on your template. Default (1) does not use the preview image but just renders the content elements. So all you need to do is changing the output of your content elements. This might lead to my first comment (2) and the part about reusing the CSC config.

(1) https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Templates/Post/Show.html
(2) https://github.com/fnagel/t3extblog/issues/159#issuecomment-261939830

**Comment by eiszeit** [comment]
You are right is more a general question. I found the right place where to edit the fluidtemplate, but it has no effect. 
Therefore I deceided to solve it with css:

@media (max-width: 368px) {
  .tx-t3extblog img {
  height: auto;
  width: auto;
  max-width: 100%;
  max-height: 100%;
}
  }
with different resolutions for the single view.

Works as well when defining a max width for the list view.
