### ISSUE TITLE
Error: Request parameters could not be validated

### ISSUE THREAD

**Issue by pixelbreit** [fnagel/t3extblog#160]
Hi, 
i have a problem with the End subscription link. 

here is what i am doing (logged out from backend of course): 

After i subscribe to the created blog i receive the email with the confirmation link. 
When i click on the confirmation link i am correctly redirected to the subscription page. 
Here i can choose between "End subscription" and "Logout". 
But when i click on the "End subscription for new posts" button i get an TYPO3 Error "Page Not Found - Reason: Request parameters could not be validated (&cHash comparison failed)"

I am running TYPO3 CMS 7.6.13 with realurl 2.1.5 and t3extblog 3.0.0-dev

Am i doing something wrong here or is this a bug?

**Comment by fnagel** [comment]
This is a known issue (related to latest RealUrl versions). Try adding `noCacheHash="true"` to the link action VH.

**Comment by pixelbreit** [comment]
Thanks for the quick help.
This has worked and solved the problem.
