### ISSUE TITLE
Notification emails already sent checkbox is missing

### ISSUE THREAD

**Issue by pixelbreit** [fnagel/t3extblog#161]
Hi,
in the Blog articles the "Notification emails already sent" checkbox is not visible for normal Backend users. Only for admin users. 
In the Backend usergroup the Access List > Allowed excludefields: Post the checkbox "Notification mails already sent (mails_sent)" is checked. 

I am running TYPO3 CMS 7.6.13 and t3extblog 3.0.0-dev

Does anyone have an idea what I do wrong here?

**Comment by fnagel** [comment]
Nothing wrong here, that behavior is on purpose. It's done in TCA, see https://github.com/fnagel/t3extblog/blob/master/Configuration/TCA/tx_t3blog_post.php#L358

Idea was that there is hardly a reason for a manual edit of this field. It's updated when the emails are actually sent and should only be edited in very special cases (probably when something went wrong while sending the mails).

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
