### ISSUE TITLE
no output in FE

### ISSUE THREAD

**Issue by fwerre** [fnagel/t3extblog#163]
Basic question:
How do I get t3extblog content onto FE?
The only thing I see is this:
````
<div id="c25">  
  <div class="tx-t3extblog">
    <div>
      <div>
     </div>
      <nav>
        <ul class="pagination"> 
        </ul>
      </nav>
    </div>
  </div>
</div>
````
I am using typo3 v 7.6.14 and t3extblog v 2.2.1 
Thank you for your help.
fwerre

**Comment by fnagel** [comment]
Could be caused a lot of things. Did you follow the installation instruction?

**Comment by fwerre** [comment]
Yes, I did it all as described... What other infos would you need?
thanks

**Comment by fnagel** [comment]
Did you create post records? Within the configured storage folder? TypoScript is correct and available? Using blogsystem plugin? Any other plugin renders content (latest posts)?

**Comment by fwerre** [comment]
uh, that was the hint: 

> Within the configured storage folder?

My mistake was I added some posts on the Blogsystem main page, not inside the folder.
Thank you so much.....!

**Comment by fnagel** [comment]
👍 Glad I could help :-)

**Comment by fwerre** [comment]
What I found irritating is that there is literally no output at all when nothing was posted in the dedicated folder.
Maybe a standard message like "no posts found" would help debugging, because one would know at least the extension have been installed correctly.

**Comment by fnagel** [comment]
@fwerre I've created a ticket for this, see #167
