### ISSUE TITLE
"comments" übersetzen

### ISSUE THREAD

**Issue by GSchn** [fnagel/t3extblog#165]
Wo kann ich die "comments" (die Anzahl der Kommentare) ins deutsche übersetzen?
Im Voraus vielen Dank.

**Comment by fnagel** [comment]
Backend oder Frontend? Screenshot wäre super. 

Doku sollte auch schon helfen: https://github.com/fnagel/t3extblog/blob/master/Documentation/FAQ/Index.rst#translation--localization

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
