### ISSUE TITLE
Sending e-mails to a comment subscriber is not working in multi domain environment

### ISSUE THREAD

**Issue by macsvenne** [fnagel/t3extblog#166]
I want to use the extension in a multi domain environment with two domains. It is mostly working, but sending e-mails to a comment subscriber after manually approving a comment is not working. The problem is that in that case the extension uses only the first typoscript template starting from the root level. The outcome is an e-mail with the wrong setting, e. g. sender name and comment link URL from the first domain. The typoscript on the second domain is completely ignored. It works only when the comments are automatically approved. But due to legal reasons this is not an option.

**Comment by fnagel** [comment]
Mhhh, sounds like an issue with the `settingsService`.

How is your TS included? Can you give some more info in general, see https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md#bug-reports--questions

I must confess this extension has not yet been tested in a multi-domain setup.

**Comment by macsvenne** [comment]
Ok, I use TYPO3 6.2.29 and t3extblog 2.2.1. The TS is included on domain level, but only the first TS beginning from root level is used. I tried conditions to execute the correct TS, but it also didn´t work.

For example, TS configuration of domain 1:
plugin.tx_t3extblog {
	persistence {
		storagePid = 9363
	}
	settings {
		blogName = Name of the Blog Domain 1
		blogsystem.pid = 9365
		subscriptionManager.pid = 9367
		emailFrom = info@example.org
		emailTo = admin@example.org
	}
}

And domain 2:
plugin.tx_t3extblog {
	persistence {
		storagePid = 9375
	}
	settings {
		blogName = Name of the Blog Domain 1
		blogsystem.pid = 9377
		subscriptionManager.pid = 9378
		emailFrom = info@example.org
		emailTo = admin@example.org
	}
}

**Comment by fnagel** [comment]
Including the config from the root TS template of each domain should be best, but if that doesn't work... Not sure, perhaps you could try changing the settings service to use a (generated) TSFE?

https://github.com/fnagel/t3extblog/blob/master/Classes/Service/SettingsService.php
https://github.com/fnagel/t3extblog/blob/master/Classes/Utility/GeneralUtility.php#L45

Sorry I'm not able to be more helpful here, but it seems this needs more investigation and a proper testing environment. I will need to wait for some more free time to work on this.

**Comment by bobberle101** [comment]
https://github.com/fnagel/t3extblog/blob/master/Classes/Utility/GeneralUtility.php#L45
- public static function getTsFe($pageUid = 0)

Here we would need the PID of the subscription manager instead of hard coded "0".  So far that works if I hard code it here. Sorry I am not a developer.

So far I have tried to read it from constants:
```
 use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface; 
 public function injectConfigurationManager(ConfigurationManagerInterface $configurationManager)
    {
        $subManager = $this->newsSettings = $configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS,
            'pid',
            'subscriptionManager',
            'settings',
            'tx_t3extblog',
            'plugin'
        );

        return $subManager;
    }
```

**Comment by pixelbreit** [comment]
Hi,
in my MultiDomain setup the links in the SubscriberNewPostMail.txt the are also wrong.

This is probably the same reason.

Does anyone have a solution for this?

By the way: The links in BlogSubscriberOptinMail.txt are correct.

**Comment by fnagel** [comment]
@macsvenne @pixelbreit @bobberle101 

Would you mind testing this with the 3.x release? Some relevant parts have changed there, perhaps it works for you. 

If that does not work, you could try this branch in which I modified the TS generation in BE context: 
https://github.com/fnagel/t3extblog/tree/typoscript-generation

@pixelbreit Your issue seems more like related to #164 Might be fixed in latest 2.2.x version, though.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by pixelbreit** [comment]
We had to divide the multi-domain environment into single single domain websites because of the problems and the resulting time-pressure.
Sorry, but unfortunately I could not test it anymore.

**Comment by fnagel** [comment]
Ahh ok. Understandable. I'll keep this ticket open, probably someone else will be able to provide some feedback.  

Anyway, thanks for the response.
