### ISSUE TITLE
Access for groups TCA related

### ISSUE THREAD

**Issue by Naberd** [fnagel/t3extblog#170]
If i make new forum post i want to give access to this post to some specific groups. Unfortunately it saves only one group.
thought it was typo3 bug, but then tried ordinary content element there i can save multiple groups.

Which means definition in TCA for user access groups is single and not multiple as it should.

**Comment by Naberd** [comment]
fixed issue :

**Comment by fnagel** [comment]
Seems like a bug for all `fe_group` fields. Fix is already included in private repo. Will be released asap.

Thanks for reporting!
