### ISSUE TITLE
Shorten the URL with RealURL for SEO how to configure?

### ISSUE THREAD

**Issue by thajb** [fnagel/t3extblog#172]
in the documentation is the standard configuration, which works fine.

But how can we shorten the URL for the blog and its articles? So it has less / in the URL, which seems to be better for SEO

Standard:
**_url/blog/article/year/month/day/article-name/_**

Shortened:
**url/blog/article-name/**

or even:  **url/article-name/**

**Comment by thebluprint** [comment]
yeah man, got the same Problem with this typo3 Extension. would be very great if somebody could 
help and get rid of this realurl Problem. 

at the Moment my Standard URL look like this:
URL/blog/date/month/article_name/
but it should look like this:
URL/blog/article-name/

thank you very much for your help

**Comment by fnagel** [comment]
Currently there is no proper configuration to do so but you might be able to adjust the RealUrl (auto) configuration for this extension. Might be possible that a RealUrl userFunc is the only way to do this for now. 

Easy configuration URLs is definitely something we want to have in the future. Afaik EXT:news has something we might want to adopt.

**Comment by ingeniero92** [comment]
I really like that new functionality. I also have problems with SEO and the URL with the date and it would be fine short the URL easily with a fast configuration in the extension.

**Comment by fnagel** [comment]
Configurable article links should be possible with the upcoming new version, see #185 

T3Extblog will make use of the new core speaking URL feature which makes it very easy for integrators to change URL structure. Just change this line to whatever suits your needs and you're ready to go: https://github.com/fnagel/t3extblog/blob/master/Configuration/Routes/Blogsystem.yaml#L75-L78

Any feedback to the TYPO3 9.5 release in general would be highly appreciated! Please comment here: #185

**Comment by fnagel** [comment]
Closed with release of version 5.0.0
