### ISSUE TITLE
Traslate Blog Subscription Messages

### ISSUE THREAD

**Issue by ingeniero92** [fnagel/t3extblog#175]
Hi! 

I am trying to traslate the messages of the Blog Subscription, but I dont know how to do that. The messages are the following:

- Subscription saved! Thanks, your subscription has been saved. A confirmation email has been sent.
- Error! The given subject was not a valid email address.
![prtscr capture](https://user-images.githubusercontent.com/4173150/27824410-b45aaa32-60ac-11e7-9ea0-437cde7d680c.jpg)
![ptr capture 2](https://user-images.githubusercontent.com/4173150/27824411-b45b89c0-60ac-11e7-83fa-5059ad31ec49.jpg)

I need to change the language of that messages to spanish. (And add a location to french also). How can I do that in the code? Location files doesnt work for me.

Thanks!

**Comment by fnagel** [comment]
Did you read the documentation?
https://github.com/fnagel/t3extblog/blob/master/Documentation/FAQ/Index.rst#translation--localization
https://docs.typo3.org/typo3cms/extensions/t3extblog/FAQ/Index.html#translation-localization

**Comment by fnagel** [comment]
@ingeniero92 Any feedback on this issue?

**Comment by ingeniero92** [comment]
Sorry, but I couldnt fix it. Anyway, I have disabled the Subscription Form for my blog. No problem now. Lot of thanks.
