### ISSUE TITLE
Template Blogpost

### ISSUE THREAD

**Issue by xQuai** [fnagel/t3extblog#177]
Hello,

i have got a question.

Normally you got a backend layout, a TypoScript File and a Fluid Template. The TypoScript File links the columns from your Backend Layout with the variables in your Fluid Template. So you can place your Content easily on your website.

In your Blog Extension you got the area content if you create a new blog post. All contents are displayed below each other. I have got no chance to place them in different columns. See the image below. 

Question: How can I achieve the normal way with a backend layout, a fluid template and the connection via TypoScript with your extension?

![Image of creating a new blog post](https://github.com/fnagel/t3extblog/blob/master/Documentation/Images/UserManual/createblogpost.png)

I would be very pleased to receive your answer.

**Comment by criwe** [comment]
Hi!
You could test the extension multicolumn or gridelements so you can add multicolumn elements. Not testet yet, but should work. Maybe you can give feedback.
Best
Chris

**Comment by xQuai** [comment]
Hi,

i tried it with gridelements. You can add the Grid Element to your Blog Post, but you don't see the Grid Element Layout like in the Page Module.

In the Blog Post it looks like this:
![Grid Element in a Blog Post](http://puu.sh/xwbIt/5d42483e78.png)

I don't know how it should work with gridelements. Can you explain it to me?

**Comment by fnagel** [comment]
@xQuai If you need full page layout functionality you might want to use a page based blog or one of the other blog extensions. T3extblog is record based and therefor has some limitations when it comes to layouting.

**Comment by xQuai** [comment]
Thank you for your answer.
