### ISSUE TITLE
need help with RealUrl config

### ISSUE THREAD

**Issue by Naberd** [fnagel/t3extblog#180]
have copied content of real url hook file into realUrl conf file since we don't use autoconfiguration.
category, filter by author work just fine.. 
https://nfk.nl/blog/author/iwanna-de-jonge/ changed here to lookup for realName instead of username
but the blog post is still unencoded
https://nfk.nl/blog/?tx_t3extblog_blogsystem%5Bpost%5D=1&tx_t3extblog_blogsystem%5Bday%5D=17&tx_t3extblog_blogsystem%5Bmonth%5D=11&tx_t3extblog_blogsystem%5Byear%5D=2017&cHash=a1e84e852c9d6ea455608c3cd72238bb

have the following in my conf file:
```
 'article' => array(
         array(
		'GETvar' => 'tx_t3extblog_blogsystem[post]',
			'lookUpTable' => array(
				'table' => 'tx_t3blog_post',
				'id_field' => 'uid',
				'alias_field' => 'title',
				'addWhereClause' => ' AND NOT deleted AND NOT hidden',
				'useUniqueCache' => 1,
				'useUniqueCache_conf' => array(
					'strtolower' => 1,
					'spaceCharacter' => '-',
				),
				'enable404forInvalidAlias' => 1,
				'autoUpdate' => 1,
				'expireDays' => 180,
				// language support (translated urls)
				'languageGetVar' => 'L',
				'languageExceptionUids' => '',
				'languageField' => 'sys_language_uid',
				'transOrigPointerField' => 'l18n_parent',
			),
	),
	array(
		'GETvar' => 'tx_t3extblog_blogsystem[day]',
	),
	array(
		'GETvar' => 'tx_t3extblog_blogsystem[month]',
	),
	array(
		'GETvar' => 'tx_t3extblog_blogsystem[year]',
	),
),
```
according to my experience it should work just fine, have written plenty of configs for custom extensions, but here not sure wat is wrong

**Comment by Naberd** [comment]
nvm modified templates into 

`<f:link.action controller="Post" action="show" arguments="{post: post.uid}">`

and changed realurlconf file 
```
'post' => array(
          array(
		'GETvar' => 'tx_t3extblog_blogsystem[post]',
		'lookUpTable' => array(
			'table' => 'tx_t3blog_post',
			'id_field' => 'uid',
			'alias_field' => 'title',
			'addWhereClause' => ' AND NOT deleted AND NOT hidden',
			'useUniqueCache' => 1,
			'useUniqueCache_conf' => array(
				'strtolower' => 1,
				'spaceCharacter' => '-',
			),
			'enable404forInvalidAlias' => 1,
			'autoUpdate' => 1,
			'expireDays' => 180,
			// language support (translated urls)
			'languageGetVar' => 'L',
			'languageExceptionUids' => '',
			'languageField' => 'sys_language_uid',
			'transOrigPointerField' => 'l18n_parent',
		),
	),
),
```
now have short url and also without year month day in url which suits me just fine.

**Comment by Naberd** [comment]
btw found out why it didn't work in first place article was used in tt_news config.

**Comment by fnagel** [comment]
Yes, using duplicate keys for realurl configurations does not work.

`realName` is not a core field but something custom. I struggled with this one myself some time ago :-D
