### ISSUE TITLE
"No typoscript..." when setting comment to 'approved' or 'spam'

### ISSUE THREAD

**Issue by agri17** [fnagel/t3extblog#183]
[we're using Typo3 v. 6.2.31, t3extblog v. 2.2.2]

Hi there,
there is an issue with comments: when using Blog-Module in the WEB-Menu, setting a comment to "approved" or "spam" (or back) I get "Oops ...No typoscript settings available".

![grafik](https://user-images.githubusercontent.com/30660318/33985982-76ec8a4a-e0bc-11e7-8acf-3e6f6340a347.png)
 If I reload the backend frame (e.g. by clicking "Artikel" in page tree), the error goes away and the settings are done. In frontend, the settings take effect. It's just the error that is annoying.

The Blog is added on a subpage with an extension template residing on "URZ-Blog" (id=19532).
![grafik](https://user-images.githubusercontent.com/30660318/33986189-2bc814ac-e0bd-11e7-826d-d88174af26ca.png)

**Constants:** 
\# PID of the blog sysfolder containing all blog related records
plugin.tx_t3extblog.persistence.storagePid = 19533

\# PID where the "Blogsystem" plugin is located
plugin.tx_t3extblog.settings.blogsystem.pid = 19532

\# PID where the "Subscription Manager" plugin is located
plugin.tx_t3extblog.settings.subscriptionManager.pid = 19534

\# E-mail address where notification mails were send to
plugin.tx_t3extblog.settings.subscriptionManager.admin.mailTo.email = ulrich.agricola@ku.de

**Setup:**

        plugin.tx_t3extblog {
                settings {
                        blogsystem {
                                posts {
                                        paginate {
                                                itemsPerPage = 10
                                                insertAbove = 1
                                                insertBelow = 1
                                                maximumNumberOfLinks = 50
                                        }
                                        metadata {
                                                enable = 1
                                                twitterCards {
                                                        enable = 0
                                                }
                                        }
                                }
                                comments {
                                        allowed = 1
                                        allowedUntil = +6 months
                                        approvedByDefault = 0
                                        subscribeForComments = 0
                                }
                        }
                }
        }
        module.tx_t3extblog < plugin.tx_t3extblog

Any help greatly appreciated!

Kind regards
Uli

**Comment by fnagel** [comment]
Where do you add the TS config? When selecting a page without the TS, this error might pop up. 
Try adding the TS to your root TS setup (most likely on root page)

**Comment by OliverSchloebe** [comment]
Hi there, I'm getting the same error on a TYPO3 6.2.9 installation running `t3extblog` version 2.2.2.

My TS setup has been added in an ext template that's included to the main template for the root page. Frontend runs smoothly with this, and while in the backend module it correctly states there's a comment that needs to be moderated, the error pops up on setting a comment to "approved" or "spam".

**Comment by agri17** [comment]
I added TS config in an ext Template on the starting page of the blog, i.e. id=19532, see screenshot above.

**Comment by fnagel** [comment]
@agri17 Where are you in the page tree before clicking "approved" or "spam"? Seems there is no TS available when the redirect of the action kicks in. 

You might want to try adding the TS to the root of your website.

@OliverSchloebe That really looks like a bug to me. I need to re-create my 6.2 test setup in order to test this. Do other actions work? Like edit or hide or delete?

**Comment by fnagel** [comment]
Just tested this again in 6.2 -- works definitely when added to page root TS. Would you mind to show me exactly where and what TS is added @OliverSchloebe ?

**Comment by fnagel** [comment]
@OliverSchloebe Are you using `module.tx_t3extblog` in your TS? See here: https://github.com/fnagel/t3extblog/blob/2.x/Documentation/Installation/Full.rst

**Comment by agri17** [comment]
@fnagel 
First, I had addded the *static* templates 'T3Extblog: Default setup' and 'T3Extblog: additional RealUrl config' to the **blog´s mainpage**, as stated in the users manual. Perhaps this does not apply to T3 v. 6.2.31 with RealUrl 2.2.1?
I have now added the static templates to our website root (id=1). As far as I can see, this solved the problem.

**Comment by fnagel** [comment]
Actually the docs state the following: 

> This can be done on your root-page or in an extension template places on a specific page.

Seems it some cases it's needed to add the TS on the blog root page, I'm currently investigating these issues (see https://github.com/fnagel/t3extblog/issues/166#issuecomment-361902235). Sorry for the trouble!

Please close this issue of you don't need further help, thank you!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by agri17** [comment]
On this topic, no further help is needed. 
Thank you!
