### ISSUE TITLE
Double output of posts in category view and mulitlanguage

### ISSUE THREAD

**Issue by matin73** [fnagel/t3extblog#184]
Hello,

there is a bug in function
````
  public function findByCategory($category)
    {
        $query = $this->createQuery();
        $query->getQuerySettings()->setRespectSysLanguage(false);
````
If I have setup multilanguage alle posts are show double. If i remove `$query->getQuerySettings()->setRespectSysLanguage(false);` everything is ok.

martin

**Comment by fnagel** [comment]
Please add some more info as described here: https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md

**Comment by matin73** [comment]
typo3 8.7.x
php 7.1
latest blog extension
default typoscript settings

make some blog posts and then make lokalisation for english. click in frontend on a category link so that only posts from certain category are shown. each post is shown double.

**Comment by fnagel** [comment]
@matin73 Just tested this again and it works as expected. Looks like a misconfiguration to me. Who does your categories in BE and TS looks like?

![categories-be](https://user-images.githubusercontent.com/116824/35615866-bc4a36f0-0673-11e8-858d-03fb07594247.PNG)
![categories-de](https://user-images.githubusercontent.com/116824/35615867-bc627dc8-0673-11e8-9141-430ff13d9451.PNG)
![categories-en](https://user-images.githubusercontent.com/116824/35615868-bc81176a-0673-11e8-93f4-5f9948c74d85.PNG)
![categories-filtered-de](https://user-images.githubusercontent.com/116824/35615869-bc9797ba-0673-11e8-9de3-7f8b2b90806d.PNG)
![categories-filtered-en](https://user-images.githubusercontent.com/116824/35615870-bcb801bc-0673-11e8-9c00-4e46b02ff1bf.PNG)

**Comment by fnagel** [comment]
Any feedback on this one?

**Comment by matin73** [comment]
yes look same

**Comment by fnagel** [comment]
So everything works as expected now?

**Comment by fnagel** [comment]
Any feedback in this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
