### ISSUE TITLE
German translation fails to install

### ISSUE THREAD

**Issue by agri17** [fnagel/t3extblog#186]
[T3 6.2.31, t3extblog 2.2.2, RealUrl 2.2.1]

Hi,
I try to get the german translation for t3extblog via module "Language". In fact I get "Up to date":

![grafik](https://user-images.githubusercontent.com/30660318/35674692-cabc2ff4-0745-11e8-9e30-66145c152ee9.png)

and  "Success":

![grafik](https://user-images.githubusercontent.com/30660318/35674706-e0bac05e-0745-11e8-92b8-3626cef2d2c9.png).

Nonetheless translation does not take effect. Even after clearing **all** caches, FE labels still stick to english.
So I searched for the files. Translated files should reside in typo3conf/l10n/de, shouldn't they? But: in typo3conf/l10n/de, there is no folder named t3extblog. 
Any idea, what could go wrong here? 

Regards
Uli

**Comment by fnagel** [comment]
Does it work for other extensions? This should generally work without any issues. I will try to test this asap in a local instance.

It seems there are some issues with the translation server the last few days (see slack channel). Please try again in a few days.

**Comment by fnagel** [comment]
Any feedback on this? Did it work when trying again?

**Comment by agri17** [comment]
I tried several days ago - did not work. I'll try again in a minute and give you feedback.

**Comment by agri17** [comment]
I updated languages from repository. /var/www/cms/typo3conf/l10n/de/t3extblog now contains six files: de.locallang.xlf
de.locallang.xml
de.locallang_db.xlf
de.locallang_db.xml
de.locallang_mod.xlf
de.locallang_mod.xml
all dating from 2018-02-06.

But I can't get it working, FE still shows english labels ...

**Comment by agri17** [comment]
I did some translation using plugin.tx_t3extblog._LOCAL_LANG in template setup. But ist just a makeshift ...

**Comment by fnagel** [comment]
Does it work for other extensions? Download and rendering on FE?

Do those files have content? Looks like the actual download process work. Might be a config issue but then _LOCAL_LANG should not work too. Very strange.

**Comment by agri17** [comment]
Yes, seems to work with other extensions.

Files do have content:
de.locallang.xlf 29099
de.locallang.xml 12808
de.locallang_db.xlf 15214
de.locallang_db.xml 5572
de.locallang_mod.xlf 815
de.locallang_mod.xml 358

I can even open the files via http://http://ourserver.de/typo3conf/l10n/de/t3extblog/de.locallang.xlf ect.

**Comment by fnagel** [comment]
Tried this again without issues but I need to test this again in a fresh introduction package installation. Did you tried to retrieve localization using another TYPO3 installation?

**Comment by agri17** [comment]
No, I didn't yet. I'll have a try ...

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by agri17** [comment]
No further feedback at the moment. Use of t3extblog is postponed because of planned Typo3 update to an up-to-date version.
