### ISSUE TITLE
Pagetree toolbar new post button is missing 

### ISSUE THREAD

**Issue by bnjmnhssnn** [fnagel/t3extblog#188]
I installed the extension via composer and activated it without errors. The setup wizard generated the blog pages successfully. However, the "Add new post" button as shown [here](https://docs.typo3.org/typo3cms/extensions/blog/Editors/Index.html) is missing on my installation. My typo3 version is **8.7.10**. I am not sure this is a bug, as I am new to typo3 and maybe missing some step.

[EDIT]: After a lot of page refreshes/navigating around, the button appeared and is working. It's display size is smaller than it should (16x16 instead of 32x32px) but it works for me now! If you still want to investigate this issue I can try to repeat the steps and provide more info.

**Comment by fnagel** [comment]
Wrong blog extension. This tracker is for EXT:t3extblog, not EXT:blog

See here: https://extensions.typo3.org/extension/blog/
