### ISSUE TITLE
Current Master

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#191]
Hi Felix,
I´ve tried to used the current master (renamed old t3extblog directory, uploaded the new), but two errors occured:

1.  Backend: When I try to clear cache: "An error occurred while clearing the cache. It is likely not all caches were cleared as expected."

1.  Frontend: Fatal error: Class 'FelixNagel\T3extblog\Controller\AbstractController' not found in /typo3conf/ext/t3extblog/Classes/Controller/PostController.php on line 39

TYPO3 8.7.10

Best,
Christoph

**Comment by fnagel** [comment]
Hey Christoph,

sounds like a namespace / autoloading issue. I need some more info: are you using composer for installing? Or classic EM installation?

Please try to re-install the extension manager. That might already to the trick.

Yours
Felix

**Comment by criwe** [comment]
Hi Felix,
classic EM.

Another try (deinstall old version via EM, copy new files  via sFTP from master, install via EM) leads to a dead backend, display errors on said:

Uncaught Error: Class 'FelixNagel\T3extblog\Configuration\BackendConfigurationManager' not found in typo3_src-8.7.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php:3905 Stack trace: #0 [internal function]: TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extba...') #1 typo3_src-8.7.1/typo3/sysext/extbase/Classes/Object/Container/Container.php(209): call_user_func_array(Array, Array) #2 typo3_src-8.7.1/typo3/sysext/extbase/Classes/Object/Container/Container.php(181): TYPO3\CMS\Extbase\Object\Container\Container->instanciateObject(Object(TYPO3\CMS\Extbase\Object\Container\ClassInfo), Array) #3 typo3_src-8.7.1/typo3/sysext/extbase/Classes/Object/Container/Container.php(126): TYPO3\CMS\Extbase\Object\Container\Container->getInstanceInternal('TYPO3\\CMS\\Extba...', Arra in typo3_src-8.7.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3905

Best,
Christoph

**Comment by fnagel** [comment]
@criwe Did you cleared all caches? Try using "Clear all cache" and "Dump Autoload Information" in the install tool (I needed to do this twice). I just had the same issue after testing this in a EM instance when updating t3extblog to master.

**Comment by criwe** [comment]
Hi Felix,
ok, that does the trick. 
Looks fine so far, everything is working like expected :-)

On thing is a bit annoying (but I don´t know how to solve that or if it even make sense to try it) -> after updating I need to go through all my own templates and look what changes are made etc. to get it running. That not a big thing, but it sucks. Maybe its the price of updating ;-)
Best
Christoph

**Comment by fnagel** [comment]
Hey Christopher, 

> I need to go through all my own templates and look what changes are made etc. to get it running.

not much I can do about this. Using versioning might help to ease up the process.

Yours 
Felix
