### ISSUE TITLE
Links will not get rendered if used in Lists ul / ol

### ISSUE THREAD

**Issue by bobberle101** [fnagel/t3extblog#194]
unfortunately links remain in linkhandler notation href="t3://page?uid=123" if set within a ordered/unordered list within a post

using current version 3.0.2 current Typo3 8 LTS

seems to be an issue in the viewhelper  <t3b:frontend.renderContent contentElements="{post.content}" /> in
typo3conf/ext/t3extblog/Classes/ViewHelpers/Frontend/RenderContentViewHelper.php

**Comment by fnagel** [comment]
Can you give me a step by step guide how to reproduce this? I'm not quite sure if I did understand what you're struggling with. 

You try to reference a blog post within another blog post, right? A screenshot might help too!
Can you post your configuration please?

Please see https://docs.typo3.org/typo3cms/extensions/t3extblog/FAQ/Index.html#link-handler-configuration

**Comment by bobberle101** [comment]
sorry for my late reply. Seems to work now and I cannot reproduce this. Thank you! Please close.

**Comment by fnagel** [comment]
Glad it works for you! Closed.
