### ISSUE TITLE
SQL error: 'Incorrect integer value: '' for column 'parent_id' 

### ISSUE THREAD

**Issue by Web-Macher** [fnagel/t3extblog#196]
Fresh TYPO3 8.7.15 / PHP 7.0 / MySQL 5.7
T3ExtBlog 3.0.2
It is not possible to add a category.

ext_tables.sql (142):
> parent_id int(11) DEFAULT '0' NOT NULL,

0 seems to be NULL 

![auswahl_024](https://user-images.githubusercontent.com/18402154/41203867-7fc1f0c6-6cdd-11e8-9c4f-97dd787e5275.png)

**Comment by fnagel** [comment]
I'm not able to reproduce this error. 

Any specific configuration you are using? Some specific SQL modes? Where did you try this? Fresh TYPO3 instance or a existing installation?

**Comment by fnagel** [comment]
Please check your SQL mode. 

I'm not able to reproduce this error. Anybody else?

**Comment by Xippo** [comment]
I have the same bug on TYPO3 8.7.16 in composer mode

**Comment by fnagel** [comment]
So this seems more like a MySQL configuration issue as TYPO3 itself is not compatible with mentioned modes:

https://forge.typo3.org/issues/54883
https://git.typo3.org/Packages/TYPO3.CMS.git/blob/HEAD:/INSTALL.md#l305

Anyway, if somebody is able to come up with a fix for this I would really like to merge it!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Comment by fnagel** [comment]
See PR #235
