### ISSUE TITLE
Invalid use of NULL value

### ISSUE THREAD

**Issue by Web-Macher** [fnagel/t3extblog#197]
TYPO3 8.7.15 / PHP 7.0 / MySQL 5.7
T3ExtBlog 3.0.2

By default it is not possible to add the main blog plugin to a page.

ext_tables.sql (275)
> irre_parenttable tinytext NOT NULL,

**Comment by fnagel** [comment]
I'm not able to reproduce this error.

Any specific configuration you are using? Some specific SQL modes? Where did you try this? Fresh TYPO3 instance or a existing installation? What is the PID of the page you're adding the plugin? Are you sure "compare DB" in the install tools  doesn't show any issues?

**Comment by fnagel** [comment]
Please check your SQL mode. 

I'm not able to reproduce this error. Anybody else?

**Comment by fnagel** [comment]
Seems like this is due to wrong SQL mode, see #196

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
