### ISSUE TITLE
Validation failed while trying to call TYPO3\T3extblog\Controller\PostController->showAction().

### ISSUE THREAD

**Issue by DarthRosenberg** [fnagel/t3extblog#200]
Hello,
I am trying to configure t3extblog (upgrade from the old t3blog) version 3.0.2 (Typo3 7.6.28). I am getting several errors (like issue #143):
In the Blogsystem-Plugin if clicking on a blog post (to get to detail view) without comments for the first time, there are several error messages `An error occurred while trying to call TYPO3\T3extblog\Controller\PostController->showAction()`, but at least the blog post is shown, also the comment form below.
![screenshot1](https://user-images.githubusercontent.com/40351936/41536943-4f079604-7307-11e8-9f9e-9123277277e5.PNG)

If the same post is called a second time, the error messages are gone!

If you want to see the detail page of a post with comments there is only an error message
`Validation failed while trying to call TYPO3\T3extblog\Controller\PostController->showAction().` (nothing else is shown). It doesn't matter if called from the list of the Blogsystem-Plugin or from the Archive-Plugin.
![screenshot2](https://user-images.githubusercontent.com/40351936/41537101-c0f30f32-7307-11e8-9f94-f66a7cb2188e.PNG)

There also seems to be a problem with the cHash with the Latest-Comment-Plugin. If I insert this on a page, then I get the error message 'Page not found. Reason: Request parameters could not be validated (&cHash empty)'
![screenshot4](https://user-images.githubusercontent.com/40351936/41537312-618126a0-7308-11e8-8482-1d2d61492c83.PNG)

I haven't done any configuration except for basic configuration as stated in the manual and also added own Fluid-Templates (which are working).

Thanks in advance!

**Comment by DarthRosenberg** [comment]
- I have removed my own setup completely, still getting the same errors.
- Debug is already enabled, no further error messages shown.
- I am using RealUrl with default configuration.
- I also used the upgrade wizard for the t3blog.

But I noticed, when adding **new comments**, everything works fine. So I examined the old comments and they mostly **do not have an author or email address**, which are now mandatory (they haven't been madatory in the old blog, there was the possibility to configure the required fields in the setup, haven't found that option yet). When I filled in values for these fields, the post was shown, but there are still the red error messages occuring as shown in first picture above.
So I guess the problem are the empty fields (probably also for the error message on screenshot 3 when using the 'Latest comments' plugin).
Is there a way to configure the required fields for the comments, equivalent to the old blog?

Further information:
Typoscript setting for the blog: 
Constants: the minimal configuration (storagePid, Emails etc.)
Setup: now empty
Include static: T3Extblog Default setup, T3Extblog additional RealUrl config

I created the recommended page structure and simply put the Blogsystem plugin on the main page of the blog. 
Did I miss anything? Do you need further information?

Thanks!

**Comment by fnagel** [comment]
> Is there a way to configure the required fields for the comments, equivalent to the old blog?

That's not possible with t3extblog. Might be possible using TS configuration and adding dynamic validation to the related fields.

> When I filled in values for these fields, the post was shown, but there are still the red error messages occuring as shown in first picture above.

Sounds odd that new comments just work. Sure there isn't anything else wrong with the old comments?

**Comment by DarthRosenberg** [comment]
I have updated all comment entries in the database and filled in the missing fields, also I have updated all post records (there was an invalid value in the author field). Now it's working as supposed and no more error messages!
Also the Latest-comments-Plugin is now working!

Maybe this should be considered in the script for the update wizard, that these fields shouldn't be empty.
Thanks!

**Comment by fnagel** [comment]
Glad it works now!

You're right, that should be definitely covered!

What do you about a check for empty fields with a warning and some notes on how to proceed?

**Comment by DarthRosenberg** [comment]
That would be great! 
The fields can really easily be filled with some SQL statements in the database.

**Comment by fnagel** [comment]
Added a update wizard to find invalid comments, see 08c58fc311f789b1449d8424226e9ebb14ded9c6
