### ISSUE TITLE
Configuration of Blog-Pagination

### ISSUE THREAD

**Issue by DarthRosenberg** [fnagel/t3extblog#201]
I am trying to adjust the pagination of the blog (Typo3 7.6.28, t3extblog 3.0.2)
To do so, I have added a Path for the widget to the templates in my setup according to the setup of the blog.
![screenshot-blog2](https://user-images.githubusercontent.com/40351936/41841396-74ef2042-7868-11e8-8f6d-7541e9f4ba2d.PNG)

Also I have adjusted the file 
fileadmin/templates/ext/t3extblog/Templates/ViewHelpers/Widget/Paginate/Index.html
But this seems not to be working, it is still the old html code.

On the other hand, the adjustments to the template, partial and layout paths are just working fine!

Thanks in advance!

**Comment by fnagel** [comment]
Your code and file location for the overwrite looks good to me. Not sure what's the issue here. 

As this used default core functionality there might have been a change there. 

Would you mind trying if setting `widget.TYPO3\T3extblog\ViewHelpers\Widget\PaginateViewHelper.templateRootPath` works? 
Take a look here too: https://github.com/georgringer/news/issues/145

**Comment by DarthRosenberg** [comment]
This seems to work!
Thanks a lot!!!

I've already tried several different path combinations, but no success ...

**Comment by fnagel** [comment]
Just to be sure (and to document this somehow): `templateRootPath` did work for TYPO3 7.6 but `.templateRootPaths.10` did not?

**Comment by DarthRosenberg** [comment]
Exactly!

**Comment by fnagel** [comment]
This seems to work with current master in TYPO3 8.7 as intended using following configuration:

Template file: 
`web/typo3conf/ext/my_extension/Resources/Private/Templates/Plugins/T3extblog/Templates/ViewHelpers/Widget/Paginate/Index.html`

TS Configuration:
`widget.FelixNagel\T3extblog\ViewHelpers\Widget\PaginateViewHelper.templateRootPaths.0 = EXT:my_extension/Resources/Private/Templates/Plugins/T3extblog/Templates/`
