### ISSUE TITLE
Subscription Manager creates Missing authentication

### ISSUE THREAD

**Issue by eiszeit** [fnagel/t3extblog#203]
Hi.
I added the subscription manager on a seperate page than the blog system.  Added the page where the mails should be stored as record store page and added the page where the manager is located in constants: plugin.tx_t3extblog.settings.subscriptionManager.pid = 90. I have valid email addresses as well, but still my page shows "Authentication missing. Please try again." I am using t3extblog 3.0.0 and typo3 7.6.30. The rest of the blog works fine for me.

**Comment by stephanreinecke** [comment]
Same problem here with TYPO3 7.6.29 and t3extblog 3.0.2.

**Comment by fnagel** [comment]
> I added the subscription manager on a seperate page than the blog system. 

Recommended way to set up the subscription manager. 
Page should have UID = 90 according to your config. Is this the case?

> Added the page where the mails should be stored as record store page 

Please explain what you mean when talking about "mails" and "record store page"?

**Comment by eiszeit** [comment]
> Recommended way to set up the subscription manager.
Page should have UID = 90 according to your config. Is this the case?
Yes I have the plugin with the subscription manager at page UID = 90, that is where I get the error.

> Please explain what you mean when talking about "mails" and "record store page"?

![unbenannt-1](https://user-images.githubusercontent.com/22792207/42886716-9026f558-8aa4-11e8-9410-44bc3829263b.jpg)

I have a system folder where all email adresses should be stored which are subscribers. That´s more or less all I can configure.

**Comment by fnagel** [comment]
Thanks for the feedback. 

@stephanreinecke Have you been able to fix your problem, too?

**Comment by stephanreinecke** [comment]
Yes, problem is fixed, thank you. I forgot to choose the Record Storage Page in the plugin "Subscription manager".

Now the next problem occured:
When I write a new article and click on the "send e-mail to the subscribers" nothing happens. All other e-mails are working, but not this one.
I have a folder for the articles and a separate page for the subscribers.
These are my contants:
plugin.tx_t3extblog.settings.blogName = My Blog
plugin.tx_t3extblog.persistence.storagePid = 366
plugin.tx_t3extblog.settings.blogsystem.pid = 360
plugin.tx_t3extblog.settings.subscriptionManager.pid = 365
plugin.tx_t3extblog.settings.subscriptionManager.admin.mailTo.email = my email address
plugin.tx_t3extblog.settings.subscriptionManager.comment.admin.mailTo.email = my email address
plugin.tx_t3extblog.settings.emailFrom = my email address
plugin.tx_t3extblog.settings.emailTo = my email address
