### ISSUE TITLE
No e-mails to blog subscribers

### ISSUE THREAD

**Issue by stephanreinecke** [fnagel/t3extblog#204]
Hi!

I have a problem with sending e-mails to blog subscribers. When I go to article list and hit the button "Sende Benachrichtigungs-E-Mails für neuen Artikel" I get the message "Es wurden erfolgreich 0 E-Mails versendet.". But there are subscribers and they are active.

My configuration:
TYPO3 7.6.30 and t3extblog 3.0.2

My page structure is like this:
- Blog [id: 360] (includes the plugins Blog Subscription Form and Blogsystem
-- Data [id: 366] (Storage folder with categories, articles, and comments)
-- Subscription Manager [id: 365] (plugin Subscription manager, stores the blog subscribers)

In my constants I have:
plugin.tx_t3extblog.settings.blogName = My Blog
plugin.tx_t3extblog.persistence.storagePid = 366
plugin.tx_t3extblog.settings.blogsystem.pid = 360
plugin.tx_t3extblog.settings.subscriptionManager.pid = 365
plugin.tx_t3extblog.settings.subscriptionManager.admin.mailTo.email = my email address
plugin.tx_t3extblog.settings.subscriptionManager.comment.admin.mailTo.email = my email address
plugin.tx_t3extblog.settings.emailFrom = my email address
plugin.tx_t3extblog.settings.emailTo = my email address

Any misconfiguration?

**Comment by fnagel** [comment]
Is this related to your comment here? https://github.com/fnagel/t3extblog/issues/203#issuecomment-406976975

**Comment by fnagel** [comment]
Configuration looks good from what I see. 

Please check table `tx_t3blog_blog_nl`. Are there valid records? Which PID do those records have (should be 366) in your case.

**Comment by stephanreinecke** [comment]
I checked the table and the subscribers have the wrong PID, they all have 365. After I changed it to 366, everything works fine. Why do they have the wrong PID?
And yes, this is related to my other comment, I thought I is better post a new issue.
Thank you!

**Comment by stephanreinecke** [comment]
Oh, I found my mistake:
In the subscription manager plugin and in the Subscription form plugin I choosed the page subscription manager (PID 365). I changed both to the page/folder data (PID 366) and now it seems to work.
Now all is stored in the data folder, the others are only pages. It was not really clear in the manual or I did not understand it.
Thank you very much!
