### ISSUE TITLE
List blog entries for single category only

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#205]
Hi @fnagel !

Quick question: Is it possible to show blog entries for a single category only using the blog plugin?
If so, how?

Thank you very much!

Best wishes
Tom

**Comment by fnagel** [comment]
Hey Tom, 

that is possible using the latets posts plugin!

Regards
Felix

**Comment by tomhatzer** [comment]
Awesome! Worked perfectly fine 👍
