### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#207]
Typo3 Version: 8.7.19
t3extblog Version: 4.0.0
Composer based installation

> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /www/typo3conf/ext/t3extblog/Classes/Domain/Repository/PostRepository.php line 197

This warning is thrown because of this check here which tries to count() a null value if the Category is undefined or the category was deleted and is not yet updated in the post itself:
https://github.com/fnagel/t3extblog/blob/572e9560efc1ac071d0035bf6ddc49e0a37bbb4d/Classes/Domain/Repository/PostRepository.php#L197

This code here is what returns null:
https://github.com/fnagel/t3extblog/blob/572e9560efc1ac071d0035bf6ddc49e0a37bbb4d/Classes/Domain/Model/Category.php#L155-L157

So if you create a category, assign a post to this category, then delete the category and view the post list in the frontend, you'll get this warning.

A quick fix would be to check for null value before counting, something like:
```
if (!is_null($categories) && count($categories) > 0) {
```

**Comment by fnagel** [comment]
Sounds reasonable. Thank you for your contribution!
