### ISSUE TITLE
Q: RSS Output - What needs to be done to get it formated as in the docs

### ISSUE THREAD

**Issue by kludikovsky** [fnagel/t3extblog#209]
This is just a question:

I get the RSS output a plain text XML.

The documentation shows a formatted RSS (https://docs.typo3.org/typo3cms/extensions/t3extblog/_images/rssoutput.png)

What do I need to do to get this format, including the RSS Link?

Can't find any settings, but I may be blind.

Typo3 8.7.19
t3extblog 4.0.0

**Comment by fnagel** [comment]
Are you using the RSS TypoScript? See https://github.com/fnagel/t3extblog/blob/master/Documentation/AdministratorManual/Index.rst#rss-feed-1

The formatted RSS shown in the screenshot is how RSS xml looks like in Firefox (at least in older ones, not sure of Mozilla already abandoned the RSS functionality from FF).

**Comment by kludikovsky** [comment]
OK. 
It's obviously a browser issue.
As you said, it works in FF and also in IE.
But it does not in Opera, Vivaldi and Chrome.
Vivaldi und Chrome at least display the raw XML, which Opera just shows a gray page, which also contains the raw XML. 

Thx.
