### ISSUE TITLE
Blog Subscriber - Authentication failed!

### ISSUE THREAD

**Issue by KaiBroenstrup** [fnagel/t3extblog#211]
Hi,
my problem: I cant subscribe to new blog posts. If i click on the Optin Link in the Email it redirects me to the subscription-manager page but i get the Message: "Authentication failed! - Authentication has failed. It seems no such subscription exists."

Everything else works fine. I debugged a little bit and the SQL in "findByCode" function picks the wrong table. Instead of "tx_t3blog_blog_nl" it takes the "tx_t3blog_com_nl" table. 

Is that a known bug or what is missing? 

Typo3 Version: 8.7.20 - t3blog Version 4.0.1

Thanks

**Comment by fnagel** [comment]
I've just tested this in my local setup and was not able to reproduce this. When using the `` plugin a new record is created in table `tx_t3blog_blog_nl`. After clicking the link within the email it's no longer `hidden` and I get a proper message in the frontend.

Looks like something is fishy in your installation. I would recommend trying this in a clean installation or a introduction package setup. 

Did you check all TS setup if there is something broken? You can check using the "Typoscript object browser" within the "template" BE module.

**Comment by KaiBroenstrup** [comment]
Hi Felix,
so i got a fresh installation - only the blog extension on it. I did everything mentioned in the Quick Installation guide. Added the typoscript template and changed the constants to my id's. But subscription not working. If i open the Subscription Manager page i directly get an "Missing Authentification - Authentication missing. Please try again."
What typoscript settings am i missing? I can give you a link to the backend if you want.
Thx

**Comment by KaiBroenstrup** [comment]
![bildschirmfoto 2019-01-07 um 12 36 09](https://user-images.githubusercontent.com/5145789/50766299-f3f7f580-1278-11e9-8ef0-1101d9745329.png)
![bildschirmfoto 2019-01-07 um 12 35 32](https://user-images.githubusercontent.com/5145789/50766300-f3f7f580-1278-11e9-90a3-8c425032d917.png)

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by KaiBroenstrup** [comment]
Hi, i am afraid not. Still not working. I will try again with a fresh 8.7 and the last version. Will report on monday.

**Comment by KaiBroenstrup** [comment]
Sorry but it still doesnt work. 
A fresh Typo3 (8.7.17) - a fresh Blog Ext (4.0.1) and i still got the authentication missing. 
Lets have a try: http://testing.kaibroenstrup.com/index.php?id=2

**Comment by fnagel** [comment]
Added a comment. Needs to be approved...

**Comment by KaiBroenstrup** [comment]
Comment is approved. But do you get the same error if subscribing to the whole blog?

**Comment by fnagel** [comment]
Just added a new blog posts subscription, too. Problem is: I did not get any email, so no testing possible. 

> But do you get the same error if subscribing to the whole blog?

I did not see any error.

**Comment by fnagel** [comment]
Just got the email for the new posts subscription. Seems you're not using RealUrl and for some reason the non RealUrl link in the email is wrongly escaped.

Try replacing `&amp;` with `&` in the link and it works. Solution would be to see why the links are wrongly encoded or just installing RealUrl.

**Comment by KaiBroenstrup** [comment]
Yeah didnt see that. Thanks - it works with real url and auto configuration.

**Comment by fnagel** [comment]
Nice. Good to hear you make it work.

Do you have any idea why the links are invalid without RealUrl. Would be nice to have this working even without RealUrl...

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by KaiBroenstrup** [comment]
Hi, sorry no idea - without real url it didnt work.

**Comment by fnagel** [comment]
Ok, thanks for the feedback!
