### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by christophbee** [fnagel/t3extblog#213]
![Bildschirmfoto 2019-04-16 um 08 09 43](https://user-images.githubusercontent.com/22295289/56186305-4fc3de80-601f-11e9-8ef4-2a922b04f961.png)

In section "Overwrite templates" the paths to the Partials and Layouts are mixed and have to be changed. In "partialRootPaths" the path is `EXT:my_theme/Resources/Private/T3extblog/Layouts/` and in "layoutRootPaths" the path is `EXT:my_theme/Resources/Private/T3extblog/Partials/`. Please correct the last parts of the paths.

https://docs.typo3.org/typo3cms/extensions/t3extblog/Configuration/Index.html?highlight=partial#overwrite-templates

**Comment by fnagel** [comment]
Thanks for the hint!
