### ISSUE TITLE
Error while submitting commend

### ISSUE THREAD

**Issue by hweckhardt** [fnagel/t3extblog#215]
Release 4.0.2-dev:

Oops, an error occurred!
Fluid parse error in template Email_action_AdminNewCommentMail_163f438f2204623e10e8c34d0d176800805f7a3e, line 37 at character 2. Error: The ViewHelper "<t3b:wordwrap>" could not be resolved. Based on your spelling, the system would load the class "FelixNagel\T3extblog\ViewHelpers\Frontend\WordwrapViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <t3b:wordwrap>
More information regarding this error might be available online

**Comment by fnagel** [comment]
You are using the 9.x branch, aren't you? https://github.com/fnagel/t3extblog/tree/typo3-9

Seems that VH was removed by accident, but even reverted there are still issues with the FE link helper which needs to be fixed...

**Comment by hweckhardt** [comment]
Yes, I am using the 9.x branch from this Github page. The website where i want to use the t3extblog extension is still under construction, so i will follow up the changes on Github from time to time. Many thanks for your efforts.

**Comment by hweckhardt** [comment]
Hey, I have seen that the WordwrapViewHelper is available again. However, after pressing "Absenden" i get another error message:

Oops, an error occurred!
Call to a member function getUriBuilder() on null

Many thanks in advance for your help.

**Comment by fnagel** [comment]
I guess this is still WIP :-/

See here for current status: https://github.com/fnagel/t3extblog/issues/185

Any help is highly appreciated!

**Comment by fnagel** [comment]
@hweckhardt FYI:

> Call to a member function getUriBuilder() on null

Has been fixed in cbbe9bab787e21e22d33218b24355af63892ae00

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by hweckhardt** [comment]
I have not followed up this issue, as I have switched to the Typo3 Blog Extension „blog“.

 

Von: Felix Nagel [mailto:notifications@github.com] 
Gesendet: Dienstag, 5. November 2019 19:00
An: fnagel/t3extblog
Cc: hweckhardt; Mention
Betreff: Re: [fnagel/t3extblog] Error while submitting commend (#215)

 

Any feedback on this issue?

**Comment by fnagel** [comment]
@hweckhardt Thanks for the feedback!
