### ISSUE TITLE
Some error with a clean typo3 and t3extblog

### ISSUE THREAD

**Issue by jooler** [fnagel/t3extblog#218]
I have install typo3 9.5.11 and only install t3extblog extension 
but when I add plugins to the page I got this
![屏幕快照 2019-11-26 下午9 56 37](https://user-images.githubusercontent.com/25960405/69640169-e158fb80-1098-11ea-83e2-96287eda3983.png)

I have follow this page to config plugin
https://docs.typo3.org/p/typo3/t3extblog/3.0/en-us/Installation/Quick.html

**Comment by fnagel** [comment]
Please use the search function: https://github.com/fnagel/t3extblog/issues/196

tl;dr: Wrong SQL mode.
