### ISSUE TITLE
Update to TYPO3 9.5 - minor Documentation thing

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#220]
Hi!
I´ve update my old TYPO3 8.6 to TYPO3 9.5 and to the newest t3extblog version.
Works like charm!

One very small thing to add to the documentation: when you got a lot of articles, you need to hit the "create missing post URLS slugs" multiple times. Seems like just 100 or so are converted. 
Maybe to the sentence "2. Run “Create missing post URL slugs” update wizard in extension manager" in the documentation a small "hit multiple times when you have more than x posts" or something should be added.
Best

**Comment by fnagel** [comment]
You're absolutely right! Bad UI design :-(

I've added a counter and a note as you suggested! Thanks a lot!

And feel free to add more feedback regarding the latest version!
