### ISSUE TITLE
Exception caused by existing (but marked as missing) field t3ver_oid

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#225]
Hi Felix,

the following error occurs on Typo3 9.5.14 when t3extblog is at the last position of the packages array in the PackageStates.php file.
Did you get this error in the past too?

![Screenshot_2020-03-02-TYPO3-Exception](https://user-images.githubusercontent.com/3952168/75665747-f1beda80-5c74-11ea-90cf-ba13c4c35e60.png)

The field exists in the database and the index is there too:
![typo3_bug](https://user-images.githubusercontent.com/3952168/75665870-2337a600-5c75-11ea-86d0-0dde5992379e.png)

When I change the position of the t3extblog package in the PackageStates.php file to somewhere near the top, the error disappears until I want to activate another Extension in the Extension Manager. While reordering, the t3extblog extension is again placed at the last position and causing the exception from above.

Steps to reproduce:

- Log into typo3 Backend.
- Open Extension Manager.
- Activate an inactive extension while t3extblog is placed at last position in the PackageStates.php file.

Thanks and have a great start of the week!

Best wishes
Tom

**Comment by tomhatzer** [comment]
Nevermind, I found the evil part. I had an extension for t3extblog in a custom package I created which was loading parts of t3extblog without having a dependency for it in the ext_emconf.php file.

After adding this code to my extensions ext_emconf.php the problem disappeared:
![image](https://user-images.githubusercontent.com/3952168/75674572-a7922500-5c85-11ea-9c03-a073d7ae9dcc.png)

**Comment by fnagel** [comment]
Good to hear you fixed your issue :-D

And thanks for reporting back what the solution was! Have a good one!
