### ISSUE TITLE
Make comment email optional

### ISSUE THREAD

**Issue by msollmann** [fnagel/t3extblog#226]
Would it be possible to remove the hard coded "required"/"notEmpty" attribute for the email field in comments? In my opinion it is not required by the GDPR, so it wolud be nice to make it configurable via TS.

**Comment by fnagel** [comment]
That would need some more changes, doesn't it? Like without email we cannot process subscriptions and need optional validation based on that TS value too. Not sure if there's some more thing to consider.

Would you mind adding a PR for that change? I'm still busy trying to make the extension TYPO3 10 compatible...

Some references:
https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Partials/Comment/FormFields.html#L38
https://github.com/fnagel/t3extblog/blob/master/Classes/Domain/Model/Comment.php#L52-L53

**Comment by msollmann** [comment]
Didn't know that it is so complicated because I do not use the subscribe function. I only changed the model, template and TCA. I am also too busy for doing a substantial modification.

**Comment by fnagel** [comment]
I'm happy you made it work for your project! Would you mind to share you changes here for anybody else? 

In general, it's something to consider and not THAT complicated to accomplish. And you're definitely right, an email address is not really required to comment. Would be a nice minor feature to have. So here is...

**What needs to be done:**

* [ ] Add dynamic (optional) required validation for comment email property
* [ ] Make comment email validation configurable using TS
* [ ] Add check for email and subscription checkbox incl. flash message
* [ ] Add template condition for comment email required attribute

**Comment by fnagel** [comment]
@msollmann I've created a branch with optional comment email address support. 

See https://github.com/fnagel/t3extblog/tree/feature-comment-email-optional

Would you mind testing this?

**Comment by fnagel** [comment]
Any feedback on this?

**Comment by msollmann** [comment]
Can not test it because I am using Version 5 on TYPO3 9. 
Thank you anyway!

**Comment by fnagel** [comment]
Ahh ok. Thanks for the info. I will do some more tests and merge this to master soon...

**Comment by fnagel** [comment]
Merged to master. Will be included in next release.
