### ISSUE TITLE
Custom linkhandler still necessary?

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#227]
TYPO3-version: 9.5.14
Webserver: Apache/2.4
PHP-version: 7.3.15
t3extblog-version: 5.0.0

Hi Felix!

I hope you are doing well.
I've got a small problem on a clients website, regarding links to other blog articles inside the blog article detail page.

Is the custom linkhandler that's referenced in the [FAQs](https://docs.typo3.org/typo3cms/extensions/t3extblog/stable/FAQ/Index.html#link-handler-configuration) still relevant? If I remove it, there's on link being printed on the website.
If i keep it, it only links to the overview page, but not to the detail page of the blog article.

The non-working links that are generated look like this: `https://domain.com/<page with blog article list overview>/page?tx_t3extblog_blogsystem%5Bday%5D=04&tx_t3extblog_blogsystem%5Bmonth%5D=12&tx_t3extblog_blogsystem%5Bpost%5D=51&tx_t3extblog_blogsystem%5Byear%5D=2019&cHash=2b6806df088652525ad98b2323f1f77e`

A correct link would be eg. `https://domain.com/<page with blog article list overview>/article/2020-04-03-this-is-a-new-blog-article`

Do you possibly have a solution for this?

Thank you very much!

Best wishes
Tom

**Comment by tomhatzer** [comment]
Ok I saw that there were small changes in the TypoScript for Typo3 9.x - implemented those changes and now it works as expected. Sorry again for disturbing 😅

**Comment by fnagel** [comment]
Hey Tom, good to hear you already solved the issue :-D

Is that something somebody else could stumble upon? Should I update the upgrade guide in order to point out some required changes?

**Comment by tomhatzer** [comment]
It would be nice if there was a little bit more information in the upgrade guide for version 5 here, specially regarding changes in the typoscript/tsconfig stuff: https://docs.typo3.org/p/felixnagel/t3extblog/5.0/en-us/UpgradeGuide/Version-5.html

I read the FAQ and due to the similarity of the old code and the new one I scrolled past it 😅

Also finding the upgrade guide for version 5 is not that easy as it‘s not linked on the docs page for the upgrade guides for version 1-4 here (which is still one of the first results on google for t3extblog upgrade guide): https://docs.typo3.org/typo3cms/extensions/t3extblog/stable/UpgradeGuide/Index.html

If I can help you with anything, please tell me 😊

Thank you very much!

**Comment by fnagel** [comment]
Hey Tom! Thanks again for your valuable feedback!


> Also finding the upgrade guide for version 5 is not that easy as it‘s not linked on the docs page for the upgrade guides for version 1-4 here

Ahh damn, seems I forgot to add the page to the index when releasing 5.0.0. It's already included in the master branch of the documentation: https://docs.typo3.org/p/felixnagel/t3extblog/master/en-us/UpgradeGuide/Index.html and within the 5.x branch (from which I will release a version 5.1.0 soon): https://github.com/fnagel/t3extblog/blob/5.x/Documentation/UpgradeGuide/Index.rst Anyway, thanks for the hint!


> It would be nice if there was a little bit more information in the upgrade guide for version 5 here, specially regarding changes in the typoscript/tsconfig stuf

Make sense but what exactly is missing? Looking at the diff from 4.1.0 to 5.0.0 I identify following changes: 

* Rename TS and TSconfig files to newer file extensions
* Split TS configuration into multiple files

What am I missing regarding TS / TSconfig changes? What else do you think should be covered?

With the upcoming 5.1.0 there has been a fix for the TS linkhandler configuration which is alredy documented (but not yet visible when looking at the rendered 5.0.0 docs): https://github.com/fnagel/t3extblog/commit/3135015a666ec7e306dc2dcc31fa3b4c5f01af85#diff-5b6cf869265c13af8566f192b4ab3d2a
