### ISSUE TITLE
Invalid service "dashboard.widget.t3extblog.latestPosts": class "TYPO3\CMS\Dashboard\Widgets\ListWidget" does not exist.

### ISSUE THREAD

**Issue by julian-angermaier** [fnagel/t3extblog#228]
**TYPO3 10.4.3**
After installing it crashed my backend. Installtool gave me this message in "check for broken extensions"

(1/1) Symfony\Component\DependencyInjection\Exception\RuntimeException
Invalid service "dashboard.widget.t3extblog.latestPosts": class "TYPO3\CMS\Dashboard\Widgets\ListWidget" does not exist.

Is this a general problem? it seems like the integration changed: 
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Breaking-90660-RegistrationOfWidgetsChanged.html

Thank You

**Comment by fnagel** [comment]
Which version of t3extblog are you using? Did you update the extension or TYPO3? 

Probably some cache related stuff as the mentioned breaking change has been adapted for the extension, see this commit: https://github.com/fnagel/t3extblog/commit/77ae7aa70cf92284294f6d0d38173acfd87629a5

The "latestPosts" widgets works for me in multiple installations: 
![image](https://user-images.githubusercontent.com/116824/82872841-e1489400-9f33-11ea-8310-fb9f551aeae9.png)

**Comment by fnagel** [comment]
Please try clearing the cache in the "maintenance module" and try to remove and add the widgets from the dashboard.

**Comment by julian-angermaier** [comment]
I am using a fresh installed 6.0.0 and TYPO3 Installation too. It crashes my backend. Clearing cache via Installtool returns 500 and database compare shows this message.
![Bildschirmfoto 2020-05-26 um 15 25 39](https://user-images.githubusercontent.com/58265225/82906228-3650ce00-9f65-11ea-9db1-8f8ce1c25654.png)

**Comment by fnagel** [comment]
Just checked the yaml configuration keys and the related classes again. Looks good.

Did you install the core EXT:dashboard?

**Comment by julian-angermaier** [comment]
Thank You, EXT:dashboard fixed the "problem". 
A dependency to this extension would be good :)

**Comment by fnagel** [comment]
Nice! Yeah, it's in the "suggest" part of composer (https://github.com/fnagel/t3extblog/blob/master/composer.json#L47), but it seems this needs a proper fix. Not sure how, but I hope to get some helpful replies here: https://twitter.com/felixnagel/status/1265662071640928259

**Comment by fnagel** [comment]
Created a ticket here: https://forge.typo3.org/issues/91531
