### ISSUE TITLE
open graph as meta property instead of meta name

### ISSUE THREAD

**Issue by msollmann** [fnagel/t3extblog#229]
The open graph data needs to be set with "property" instead of "name":

False: `<meta name="og:title" content="Live Science Slam" />`
Correct: `<meta property="og:title" content="Live Science Slam" />`

So you have to set:
```
if (strpos($property, 'og:') === 0)
    $metaTagManager->addProperty($property, $content, [], false, 'property');
else
    $metaTagManager->addProperty($property, $content);
```
in Classes/ViewHelpers/Frontend/MetaTagViewHelper.php, line 76

**Comment by fnagel** [comment]
Thanks for the bug report. Please add info as described in https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md

This looks like an core bug to me, as the EXT:seo should use the `property` attribute for "og" meta data, see https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/seo/Classes/MetaTag/OpenGraphMetaTagManager.php#L34

It works for me usingTYPO3 10.4.4 and t3extblog 6.0.1 (compare my own blog: view-source:https://www.felixnagel.com/blog/artikel/2018/11/01/symfonylive-2018-in-berlin/). 

Are you using and old version of t3extblog or TYPO3?

**Comment by msollmann** [comment]
TYPO3 9.5.17, t3extblog 5.0.0

But today I cannot reproduce the issue anymore - don't know why. 6 days ago it was a stable error which I could only solve by the aforementioned code. Let's close this issue and open it again if there are any news on this.

**Comment by fnagel** [comment]
Uhhh, probably some wired caching thing? Anyway, I'm glads its working for you now. 

Closed, please reopen if needed.
