### ISSUE TITLE
Test and fix for TYPO3 CMS 7.x

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#23]
https://github.com/fnagel/t3extblog/tree/typo3-7x

General
* [x] Test in TYPO3 CMS 7.x
* [x] Test in TYPO3 CMS 6.2
* [x] Remove all deprecated core function: #19
* [x] Use PHP namespaces #41
* [x] Update dependency to 6.2-7.x, remove legacy code

TYPO3 CMS 7.x ToDo
* [x] General functionality
* [x] Comments allowed VH (Caching issue)
* [x] BE module functionality
* [x] Testing: Comments
* [x] Testing: Subscription
* [x] BE module pager styling
* [x] Check RealUrl support
* [x] Nicer BE icon

**Comment by fnagel** [comment]
WIP branch with support for TYPO CMS 7.x:
https://github.com/fnagel/t3extblog/tree/typo3-7x

**Comment by pvanhemmen** [comment]
Here's a suggestion for a new BE Icon. I tried to keep the visual apperance of the original icon, just ported it over to match the new Icon Layout:

![ext_icon](https://cloud.githubusercontent.com/assets/715022/8953467/f60eacb2-35de-11e5-9208-a759796eea8c.png)

Here's how it looks in context:

![icontest](https://cloud.githubusercontent.com/assets/715022/8953516/6af23c88-35df-11e5-9731-51469320f4d9.png)

Please let me know if you don't like it or want anything changed. Didn't make a Pull request for this one, because it's such a small enhancement. Can make one, though, if that's more convenient for you.

**Comment by fnagel** [comment]
Love the new design! Great work! I could imagine to redesign all t3extblog icons to have a fresh new look for version 2.0.0. What do you think?

I've just pushed a few new commit incl. your new icon. Would you mind posting the PSD?

**Comment by pvanhemmen** [comment]
You're welcome. Will send you the PSD by mail as it is not allowed to upload it here.

Redesigning the other icons sounds good. If you don't mind I'll try to come up with some suggestions.

**Comment by fnagel** [comment]
info @ felix nagel . com

Yes, of course! Thanks a lot for your contribution!

**Comment by pvanhemmen** [comment]
OK here we go, please let me know what you think:

![blogroll](https://cloud.githubusercontent.com/assets/715022/8969806/04231970-3646-11e5-960d-a28013da08be.png) blogroll
![category](https://cloud.githubusercontent.com/assets/715022/8969807/09b7258e-3646-11e5-836e-e27301492921.png) category
![comment](https://cloud.githubusercontent.com/assets/715022/8969811/0c16b8e4-3646-11e5-9df1-adf11171e055.png) comment
![folder](https://cloud.githubusercontent.com/assets/715022/8969813/0df4bc24-3646-11e5-9883-2b4dc14c680c.png) folder
![page](https://cloud.githubusercontent.com/assets/715022/8969848/3b472838-3646-11e5-8acd-133b1931e1b3.png) page
![subscriber](https://cloud.githubusercontent.com/assets/715022/8969822/1173f46e-3646-11e5-8390-ac18905e9046.png) subscriber
![trackback](https://cloud.githubusercontent.com/assets/715022/8969824/130cb50e-3646-11e5-8f6e-6b6d5149b75d.png) trackback

**Comment by fnagel** [comment]
I like the general shape and look but I'm not sure if we want head to a inverted, darker style. Any intention why you did so?

**Comment by pvanhemmen** [comment]
Readabilty. But I'll try to create a lighter style that matches the overall look, and will post it here. Any suggestions or wishes?

**Comment by fnagel** [comment]
No not really -- matching the default / core icons for records.

**Comment by pvanhemmen** [comment]
Another set. Lighter and more leaned towards the default icon set. Let me know what you think!

![blogroll](https://cloud.githubusercontent.com/assets/715022/8987557/f8bef4a4-36e1-11e5-856b-ea599689b211.png) blogroll
![category](https://cloud.githubusercontent.com/assets/715022/8987556/f8bea2ba-36e1-11e5-9bce-c793dbd3a3b3.png) category
![comment](https://cloud.githubusercontent.com/assets/715022/8987561/f8c1e1be-36e1-11e5-95d5-d9fd24550ce7.png) comment
![folder](https://cloud.githubusercontent.com/assets/715022/8987560/f8c1c81e-36e1-11e5-8680-5b271a711dcd.png) folder
![page](https://cloud.githubusercontent.com/assets/715022/8987559/f8c11702-36e1-11e5-9610-a5f65d28b33e.png) page
![subscriber](https://cloud.githubusercontent.com/assets/715022/8987558/f8bfae58-36e1-11e5-89a8-8c0249997e87.png) subscriber
![trackback](https://cloud.githubusercontent.com/assets/715022/8987562/f8d53d36-36e1-11e5-92aa-217141ab856d.png) trackback

**Comment by fnagel** [comment]
Yeaah, very nice! Love the new layout and the details! I think we got our new icon design :-D

I opened a new issue for this topic, see #76

**Comment by fnagel** [comment]
Closing this. More discussion here: #79
