### ISSUE TITLE
T3 9.5 with 5.1.0 - Parameter "tx_t3extblog_blogsystem__post" for route "tx_t3extblog_blogsystem_0" must match "\d+" 

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#230]
Hi @fnagel !

I've just updated to version 5.1.0 of t3extblog and was immediately presented by the following error message after visiting a page where t3extblog is included 😅 

```
Parameter "tx_t3extblog_blogsystem__post" for route "tx_t3extblog_blogsystem_0" must match "\d+" ("2020-03-03-reach-risiken" given) to generate a corresponding URL.
```

I haven't changed anything in the default configuration file of the routing, I'm just including it in my sites configuration.yaml. The only thing I did was switch all slugs to the (at that moment) new format `y-m-d-<slug>`.

Have you ever seen this one here before (had to censor a few things)?

![image](https://user-images.githubusercontent.com/3952168/84918492-f216a080-b0c0-11ea-977d-aae78ab5c4e3.png)

Thank you very much!

Best wishes
Tom

**Comment by fnagel** [comment]
You updated TYPO3 too, didn't you? Because there has been no relevant change to the blog routing since quite some time, but with TYPO3 10.4.4 and TYPO3 9.5.15 I needed to fix some `requirements` (which seem not be be really evaluated before). 

Please see and test this commit 8ee5e7add6c5e88c94fc9e61f2fbf51e8c1265a5

**Comment by tomhatzer** [comment]
Yes, I've updated Typo3 from 9.5.16 to 9.5.19 in the same go.
The linked commit fixed the problem. Thank you very very much! 🥰

**Comment by fnagel** [comment]
Glad I could help :-D

I probably should do a hotfix release...

**Comment by fnagel** [comment]
Just released a 5.1.1 bugfix release.

**Comment by tomhatzer** [comment]
@fnagel I think I've found another bug with the URL parameters:
![image](https://user-images.githubusercontent.com/3952168/86759203-aa8e8f00-c044-11ea-82a1-0a956b863428.png)

Running on 5.1.1 bugfix release and Typo3 9.5.19. 😅

**Comment by tomhatzer** [comment]
Quickfix for the category title stuff:
Append `\/` to the regex for `category_title` resulting in: `category_title: '^[\p{Ll}\d\-\_\/]+$'`
