### ISSUE TITLE
Typo3 9.5.18 / t3extblog 5.1.0 : Error messages

### ISSUE THREAD

**Issue by annaemde** [fnagel/t3extblog#231]
Hi,

I tried to install t3extblog 5.1.0 on several projects with T3 9.5.18 and I get the following error message in the Upgrade Wizard - Ajax error: 
```
"Deprecated: Referencing the navigation component ID "typo3-pagetree" 
will be removed in TYPO3 v10.0.Use "TYPO3/CMS/Backend/PageTree/PageTreeElement" instead. 
Module key: web-T3extblogTxT3extblog in 
/kunden/201892_70794/rp-hosting/7476/8477/typo3cms/typo3_src-9.5.14/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php
 on line 874
{"success":true,"needsUpdate":false,"adds":[]}
```

Regards
Anna

**Comment by fnagel** [comment]
Looks like an bad error reporting configuration to me. Deprecation notices should not cause fatal errors.

**Comment by annaemde** [comment]
Thanks for the hint. After switching from "Debug" to "Live" I don't get these messages any longer, so I'll try to find a custom configuration where I do not get deprecation warnings in my development environment :-)

**Comment by fnagel** [comment]
This should not happen with a fresh TYPO3 installation. Did you upgrade? Probably some old, legacy configuration for your error / log reporting. 

Best would be to enable deprecation logs, but only for DEV environment and written to files.

Closing this here, as it's not really related to this extension.

**Comment by annaemde** [comment]
Hi Felix,

yes, I made an upgrade of a Typo3 8.7 installation which is actually
almost 10 years old. I've learned a lot about error reporting in the
meantime ;-)

Thanks for closing the issue. Actually you may also delete it, if you
can do so.

Regards
Anna


Am 19.06.2020 um 10:12 schrieb Felix Nagel:
