### ISSUE TITLE
Call to undefined Method in TYPO3 10.4.4

### ISSUE THREAD

**Issue by PhilippKuhlmay** [fnagel/t3extblog#232]
With TYPO3 Version 10.4.4 and t3extblog 2.1.0 I got following Error when trying to access the backend:
`Call to undefined method TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath()`

See here: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.4/Deprecation-78193-ExtensionManagementUtilityextRelPath.html

**Comment by PhilippKuhlmay** [comment]
I had ` "config": { "platform": { "php": "7.4"  } },` in my composer.json, so it installed the wrong t3extblog version. With php 7.3 it installed the version 6.0.x. and it worked.

**Comment by fnagel** [comment]
For reference: Version 2.1.x did not have TYPO3 constraints.
