### ISSUE TITLE
Language packs not available

### ISSUE THREAD

**Issue by MaSa759** [fnagel/t3extblog#239]
Hi there!

Updating the german (or any other) language-pack of t3extblog results in:
`0 new language packs downloaded, 0 language packs updated, 1 language pack not available`
The requested package returns 404: https://localize.typo3.org/xliff/t/3/t3extblog-l10n/t3extblog-l10n-de.zip

Is there a solution or workaround?

**Comment by fnagel** [comment]
Hi! Which TYPO3 version are you using? 

I've tested with TYPO3 10.4.1.0 and can confirm the issue. I will ask in the related TYPO3 Slack channel for help as I'm using the default structure for providing extension localization, see https://typo3.slack.com/archives/C032FRT0W/p1606139796004100.

As a workaround you might be able to download the language pack directly from the Pootle Server: https://translation.typo3.org/projects/TYPO3.ext.t3extblog/

**Comment by MaSa759** [comment]
I've had this bug with TYPO3 10.4.6 and 10.4.9
Unfortunately the download of files on https://translation.typo3.org/projects/TYPO3.ext.t3extblog/ results in 

    Unhandled Exception
    An unhandled exception was thrown by the application.

But this occures also by working packages, so I figured this has nothing to do with the bug.

**Comment by fnagel** [comment]
This seems to be an server issue which is already under investigation:

> Solution is coming soon (server team acknowledged and on it now). Workaround is to manually fetch by replacing https://localize.typo3.org/xliff/ prefix by https://extensions.typo3.org/fileadmin/l10n/

See here for more info:
https://gitlab.typo3.org/services/localize.typo3.org/site/-/issues/1
https://typo3.slack.com/archives/C032FRT0W/p1606383457005900
https://typo3.slack.com/archives/C041L7V6Q/p1606375674295400

**Comment by fnagel** [comment]
@MaSa759 Please check again. Seems to work again.

**Comment by MaSa759** [comment]
@fnagel Yes, it works. Thank you.
