### ISSUE TITLE
Bug in CommentAllowedViewHelper since Version 5.0.0

### ISSUE THREAD

**Issue by baggyownz** [fnagel/t3extblog#240]
hello,

you are reference two core functions the are removed since TYPO3 9.5.

AbstractConditionViewHelper
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html

And I mean these too: RenderingContextInterface

best regards

**Comment by fnagel** [comment]
Hey! Thanks for the bug report!

Can you tell in which version of TYPO3 and t3extblog you're having problems? And which files exactly causes an error?

Because in my test everything seems to work as expected and the files of master and 5.x branch look good to me:
https://github.com/fnagel/t3extblog/blob/master/Classes/ViewHelpers/AbstractConditionViewHelper.php
https://github.com/fnagel/t3extblog/blob/5.x/Classes/ViewHelpers/AbstractConditionViewHelper.php

**Comment by baggyownz** [comment]
hello fnagel,

the references are in the CommentAllowedViewHelper.
During an core update (from TYPO3 8.7 to 10.4) I installed TYPO 9.5.4 as an intermediate step and raised the t3extblog extension to version 5.0.0 as first and than to 5.1.1. 
In the partials \Comment\New.html is the viewhelper t3b:commentAllowed and the comment form was not showen for me.
Maybe it's a mistake on my part, but I didn't get into the "then part" when setting outputs. So I suspect that it had to do with referencing non-existent classes.

https://github.com/fnagel/t3extblog/blob/master/Classes/ViewHelpers/Frontend/CommentAllowedViewHelper.php
https://github.com/fnagel/t3extblog/blob/5.x/Classes/ViewHelpers/Frontend/CommentAllowedViewHelper.php

**Comment by fnagel** [comment]
Mhhh, I'm testing every release and use it on my personal website, but it's not impossible I overlooked something :-)

I'm still a little but struggling which class seems to be missing in the `CommentAllowedViewHelper`. Both versions, the 5.x and the master are using the newer `TYPO3Fluid\Fluid` namespace, like it's described in the changelog you linked above. Can you help me here? Or even better, create a PR for the problem?

Sadly I have no TYPO3 9.5 instance available for testing at the moment, so I'm not able to test this right away.

**Comment by baggyownz** [comment]
I think I made a mistake and looked for files in the wrong folder all the time. Sorry
I think we can close this.

**Comment by fnagel** [comment]
No problem at all. Thanks for letting me know! Hope you enjoy working with t3extblog!
