### ISSUE TITLE
Subscription results in a Oops, an error occurred!

### ISSUE THREAD

**Issue by taarikdoukali** [fnagel/t3extblog#241]
Hi @fnagel ,

when using the blogsubscription i get a:

"The HTTP status code must be of type integer, string given."

I can not find, what the issue here is. 

Thx for the help!

**Comment by PhilippKuhlmay** [comment]
After submitting the subscription form:
<img width="1128" alt="Bildschirmfoto 2020-12-09 um 21 51 11" src="https://user-images.githubusercontent.com/57705869/101685962-b1448680-3a68-11eb-8c75-9e1786433421.png">
URL is https://t3extblog.ddev.site/autogenerated-1/default-title?tx_t3extblog_blogsubscription%5Baction%5D=create&tx_t3extblog_blogsubscription%5Bcontroller%5D=BlogSubscriberForm&cHash=fedbf46814e111c43b60ff37993af7d1#subscriber-form

**Comment by fnagel** [comment]
This happens when a comment or a subscription is marked as SPAM. Fixed in master, but I think it's worth a bugfix release.

Thanks for reporting!
