### ISSUE TITLE
DB Errror: pages.title isn't in GROUP BY

### ISSUE THREAD

**Issue by Longjogger** [fnagel/t3extblog#245]
Hi everybody,

I installed the extension (version 4.2 on TYPO3 8.7.32 with PHP 7.2 and MariaDB 10.1), but if I select the T3extblog backend, there is displayed the following error:

`array(4 items)`
`   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)`
`   ERROR => ''database.pages.title' isn't in GROUP BY' (43 chars)`
`   lastBuiltQuery => 'SELECT pages.uid, pages.title FROM pages LEFT JOIN tx_t3blog_post ON pages.u
      id = tx_t3blog_post.pid LEFT JOIN tx_t3blog_com ON pages.uid = tx_t3blog_com
      .pid WHERE pages.deleted = 0 AND (tx_t3blog_post.deleted = 0 OR tx_t3blog_co
      m.deleted = 0) GROUP BY pages.uid' (261 chars)
   debug_backtrace => 'require(o3/sysext/backend/Resources/Private/Php/backend.php),o3/index.php#3
      // {closure}#25 // TYPO3\CMS\Backend\Http\Application->run#24 // TYPO3\CMS\C
      ore\Core\Bootstrap->handleRequest#92 // TYPO3\CMS\Backend\Http\BackendModule
      RequestHandler->handleRequest#319 // TYPO3\CMS\Backend\Http\BackendModuleReq
      uestHandler->dispatchModule#89 // TYPO3\CMS\Extbase\Core\Bootstrap->run#182
      // TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#186 // TYPO3\CMS\Extbase\
      Mvc\Web\BackendRequestHandler->handleRequest#199 // TYPO3\CMS\Extbase\Mvc\Di
      spatcher->dispatch#32 // FelixNagel\T3extblog\Controller\BackendBaseControll
      er->processRequest#85 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController->
      processRequest#114 // FelixNagel\T3extblog\Controller\BackendBaseController-
      >initializeAction#165 // FelixNagel\T3extblog\Controller\BackendBaseControll
      er->getBlogRelatedPageInfo#150 // FelixNagel\T3extblog\Controller\BackendBas
      eController->getBlogRelatedPages#170 // FelixNagel\T3extblog\Controller\Back
      endBaseController->getPagesWithBlogRecords#202 // FelixNagel\T3extblog\Contr
      oller\BackendBaseController->execBlogPageRelatedQuery#241 // TYPO3\CMS\Core\
      Database\DatabaseConnection->exec_SELECTgetRows#223 // TYPO3\CMS\Core\Databa
      se\DatabaseConnection->exec_SELECTquery#379 // TYPO3\CMS\Core\Database\Datab
      aseConnection->debug#313' (1316 chars)`

So, what's wrong?

Best regards,
Erik

**Comment by fnagel** [comment]
Sounds like an issue with the SQL mode (which is something that should be fixed / improved in later versions). See here for more info: https://github.com/fnagel/t3extblog/issues/196#issuecomment-400002928

Try running `SET GLOBAL sql_mode = '';` 

Does that help?

**Comment by Longjogger** [comment]
Yes, that helps! :+1:
Thank you!

**Comment by fnagel** [comment]
Glad I could help!
