### ISSUE TITLE
Blogsystem is sorting in ascending order

### ISSUE THREAD

**Issue by Longjogger** [fnagel/t3extblog#246]
Hi,
The entries of my blogsystem are orded by ascending. How I can correct this to descending order?

Thx for help!

**Comment by fnagel** [comment]
Do you talk about the backend or the frontend? And do I understand this right: you want your blog post list to start with the oldest articles?

**Comment by fnagel** [comment]
I'm sorry but the sorting order is hard coded in the repo, see: https://github.com/fnagel/t3extblog/blob/master/Classes/Domain/Repository/PostRepository.php#L23

**Comment by Longjogger** [comment]
Sorry because of my late answer: There was a thinking mistake of myself - I have to set the date of blog entry manually, that is the problem.
