### ISSUE TITLE
Filter Blog by category

### ISSUE THREAD

**Issue by rabele** [fnagel/t3extblog#254]
Hi Felix, this is a real great extension. I've got one issus: would it be possible to filter the output of the blog to one or more categories, when the Page is opened? I know there is the category mode but I need to output different categories in the blog on different pages (reason is different frontend users).
Thanks in advance for any hint.
Ralf

**Comment by rabele** [comment]
> Hi @rabele! Thanks and I'm glad you like this extension :-)
> 
> It's possible to filter by one category in the frontend like this: https://www.felixnagel.com/blog/kategorie/typo3/
> 
> But I assume you want a filtered blog post list, right? Filtering a list is possible using the latest posts plugin, but only using one category.

Hi @fnagel - thank you very much for your reply. Yes - I'd have to filter a list with one category. If user one is logged in, the posts of category1 is shown, for user two the output is category2 and so on.

**Comment by fnagel** [comment]
Did you try using the lastest plugin as suggested? It's not capable of rendering different categories based on user, but you might want to do this using different pages.

**Comment by fnagel** [comment]
Any feedback on this issue?
