### ISSUE TITLE
Breaks indexed_search in TYPO3 v11.5.16

### ISSUE THREAD

**Issue by cyberbehoerde** [fnagel/t3extblog#255]
Hi there,
after the upgrade of TYPO3 from `v11.5.15` to `v11.5.16` the indexed_search doesn't display any search results as long as t3extblog is installed.
It seems to have something to do with the default routing configuration of t3extblog and the T3extblogPostMapper class.
I'll try to further investigate and provide some logs.

**Comment by fnagel** [comment]
Thanks for reporting! If you could provide some more info that would be wonderful. PRs are welcome too!

**Comment by cyberbehoerde** [comment]
Thanks for your reply.
I'm sorry - during investigating this issue I realized I messed up my site-configuration regarding the YAML-imports.
So this was my fault and everything's working as intended.

**Comment by fnagel** [comment]
No problem at all. We've all been there ;-) Thanks for the feedback!
