### ISSUE TITLE
Check existing LOG configuration before writing

### ISSUE THREAD

**Issue by josefglatz** [fnagel/t3extblog#256]
Hi Felix,

would it make sense to check for an existing log configuration for `$GLOBALS['TYPO3_CONF_VARS']['LOG']['FelixNagel']['T3extblog']['writerConfiguration']` so that it's easier to overwrite you extension default LOG configuration via LocalConfiguration/AdditionalConfiguration?

Actually another package needs to require `felixnagel/t3extblog` and overwrite is possible if I do it in ext_localconf.php of the package which is loaded after your extension.

Background: the reason for this is that your logger creates a hugh bunch of false positive entries when you the TYPO3 Routing component tries all routes, route by route

```
Thu, 06 Oct 2022 12:27:33 +0200 [CRITICAL] request="fda6ab515a26f" component="FelixNagel.T3extblog.Service.LoggingService": Invalid blog post slug given! - {"url":"https://www.domain.com/news/blog/detail/permalink/51/","datePrefix":"Y-m-d-","datePrefixRegex":"#^\\d+-\\d+-\\d+-#","tableName":"tx_t3blog_post","routeFieldName":"url_segment","HTTP_HOST":"www.domain.com","TYPO3_HOST_ONLY":"www.domain.com","TYPO3_PORT":"","PATH_INFO":"","QUERY_STRING":"","REQUEST_URI":"/news/blog/detail/permalink/51/","HTTP_REFERER":"https://www.domain.com/news/blog/detail/2021-03-29-down-to-80-c-112-f-bla-bla/","TYPO3_REQUEST_HOST":"https://www.domain.com","TYPO3_REQUEST_URL":"https://www.domain.com/news/blog/detail/permalink/51/","TYPO3_REQUEST_SCRIPT":"https://www.domain.com/index.php","TYPO3_REQUEST_DIR":"https://www.domain.com/","TYPO3_SITE_URL":"https://www.domain.com/","TYPO3_SITE_SCRIPT":"news/blog/detail/permalink/51/","TYPO3_SSL":true,"TYPO3_REV_PROXY":false,"SCRIPT_NAME":"/index.php","TYPO3_DOCUMENT_ROOT":"/html/app/releases/20221006091100/private","SCRIPT_FILENAME":"/html/app/releases/20221006091100/private/index.php","REMOTE_ADDR":"0.0.0.0","REMOTE_HOST":"","HTTP_USER_AGENT":"Mozilla/5.0 (compatible; Scrutiny/9; +https://peacockmedia.software/mac/scrutiny/","HTTP_ACCEPT_LANGUAGE":"*"}
```

In the example above "datePrefix" and "datePrefixRegex" comes from the routing component which tries all of them.

**Comment by fnagel** [comment]
Hi Josef!

I personally think, if you want to change configuration from another extension, this extension should depend on t3extblog. But I definitely see the issue when using LocalConfiguration/AdditionalConfiguration. 

Would it be sufficient to just check for an empty `$GLOBALS['TYPO3_CONF_VARS']['LOG']['FelixNagel']['T3extblog']['writerConfiguration']` before adding the config in `ext_localconf.php`?

Any idea how to improve the logging (so we have useful information instead of too much noise)? I thought using [this](https://github.com/fnagel/t3extblog/blob/master/ext_localconf.php#L170) would work for production instances.

**Comment by josefglatz** [comment]
The idea for checking if its empty sounds nice, yes.

I'm not sure is there anywhere a condition which changes the severity of log entries in some situation? I think this was something why it was to much information.

**Comment by fnagel** [comment]
> The idea for checking if its empty sounds nice, yes.

I've changed this in master, see: c3f639900f17afabc06fc4f0123b9f81ce77d005

> I'm not sure is there anywhere a condition which changes the severity of log entries in some situation? I think this was something why it was to much information.

You configure the sensitivity in the TYPO3_CONF_VARS but what an actual log entry is, that is defined in the code. We might want to change something in the routing mapper.

> Background: the reason for this is that your logger creates a hugh bunch of false positive entries when you the TYPO3 Routing component tries all routes, route by route

When exactly does this happen? The log comes from this line https://github.com/fnagel/t3extblog/blob/master/Classes/Routing/Aspect/PostMapper.php#L102 but that should only fire if a requested URL can't be resolved. Which would justify an error level log entry IMHO.
