### ISSUE TITLE
Problem when disabling datePrefix in the routing

### ISSUE THREAD

**Issue by milenishte** [fnagel/t3extblog#257]
## Prerequisites

TYPO3 v11.5.18
PHP 7.4

## Description

When the datePrefix is removed from the routing configuration, the following exception occurs:

(1/1) TypeError

Typed property FelixNagel\T3extblog\Routing\Aspect\PostMapper::$datePrefix must be string, null used
in /var/www/public/typo3conf/ext/t3extblog/Classes/Routing/Aspect/PostMapper.php line 57

The problem is that in PostMapper.php the properties are defined as strings and don't accept null as a value:
    protected string $datePrefix;
    protected string $datePrefixRegex;

**Comment by fnagel** [comment]
Thanks for reporting! Fixed in latest master branch!
