### ISSUE TITLE
Update vhs (VHS: Fluid Viewhelpers) to v 7.0.0 breaks t3extblog v 6.2.1 Detail-View

### ISSUE THREAD

**Issue by hgra60** [fnagel/t3extblog#265]
The function "renderRecord" is updated in vhs

an old version is taken into "/t3extblog/Classes/ViewHelpers/Frontend/RenderContentViewHelper.php":
```
/**
 * This function renders a raw record into the corresponding
 * element by typoscript RENDER function.
 *
 * Taken from EXT:vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php
 *
 * @param int    $uid
 * @param string $table
 *
 * @return string
 */
protected function renderRecord($uid, $table)
{ ...
```
but not updated accordingly.

Thx for your attention to this

Helmut Grabendörfer, visionbites

**Comment by fnagel** [comment]
Hi Helmut, 

can you please describe the error and post the complete stack trace? Not sure what "breaks detail view" means.
As there is no dependency of EXT:vhs I'm unsure how an update of VHS should break T3Extblog at all. 

In newer version of the extension, I replaced the VH with core functionality: https://github.com/fnagel/t3extblog/commit/adefdb968a5831f82c4e5373778c74750b91dfec

You may want to try that and give feedback please. But any PR for the 6.x branch in order fix the VH is fine too!

**Comment by fnagel** [comment]
Thanks for the error report. A little strange that there is no error but this part of code works with the register and TS rendering, so you never know...

Can you explain how to reproduce this issue? Using TYPO3 10, VHS 7.x and T3Extblog 6.x as far as I understood. Then I need to configure the blog system and do what exactly with VHS to reproduce the issue? Or is installing both extensions enough?

> In newer version of the extension, I replaced the VH with core functionality: https://github.com/fnagel/t3extblog/commit/adefdb968a5831f82c4e5373778c74750b91dfec

Did you try to use this change? Does it help? 

Any reason why you do not update to v11 and T3Extblog 7.x? To be honest, I'm not sure if I will find the time to debug this in TYPO3 v10 when I really need to fix the extension to work with TYPO3 v12.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Can you please check if EXT:vhs v7.0.2 fixes this? There have been quite a few bugs in v7.0.0, see here:

Workaround for one of them: 12b247a9f2c8bdd40378965a8070e6e9dbf906e2 
https://github.com/FluidTYPO3/vhs/blob/development/Documentation/Changelog/7.0.1.md
https://github.com/FluidTYPO3/vhs/blob/development/Documentation/Changelog/7.0.2.md

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
