### ISSUE TITLE
TypeError in inline content elements

### ISSUE THREAD

**Issue by garfieldius** [fnagel/t3extblog#266]
The method `\FelixNagel\T3extblog\Domain\Model\Content::getBodytext` ist typed as "string", but the database field tt_content:bodytext can be null. If this is the case, PHP will throw a `TypeError`. This method is also used in `\FelixNagel\T3extblog\Domain\Model\Post::getPreview`, so the exception can appear in both frontend and the BE module. Editing posts via the List module is not affected.

**Comment by fnagel** [comment]
Again, thanks for your contribution!
