### ISSUE TITLE
Detailview: prev/next

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#27]
In the detailview links to the previous / next article would be nice.

**Comment by fnagel** [comment]
It's now possible to use `nextPost` and `previousPost` marker in post detail view.

We should add this to documentation.

**Comment by criwe** [comment]
Hrm, I don´t get it.. 

I´ve tried something like this, but that crashed the site..
 
<f:link.action controller="Post" action="show" pageUid="{settings.blogsystem.pid}" arguments="{nextPost}">
     next
 </f:link.action>

**Comment by fnagel** [comment]
How is `nextPost` as link argument supposed to work? You will need to use `nextPost.linkParameter`.

**Comment by criwe** [comment]
Ok, gtk. 
Works fine!
I added a condititon to avoid errors when no next/prev-ID are given (i.e. first/last article):

```
<f:if condition="{nextPost.linkParameter}">
  <f:then>
    <f:link.action controller="Post" action="show" pageUid="{settings.blogsystem.pid}" arguments="{nextPost.linkParameter}">
      {nextPost.title}
    </f:link.action>
 </f:then>   
</f:if>  

<f:if condition="{previousPost.linkParameter}">
 <f:then>
  <f:link.action controller="Post" action="show" pageUid="{settings.blogsystem.pid}" arguments="{previousPost.linkParameter}">
    {previousPost.title}
 </f:link.action>
 </f:then>   
</f:if> 
```
Maybe theres a better way to to this? 
Should we add this code to the tempate files or just mention it in the documentation?

**Comment by fnagel** [comment]
Right, you will need to test if the post exists for first and last post. Your code looks fine to me.

We could add this to the documentation.

**Comment by criwe** [comment]
Fine. Added this to the documentation.
[closed]
