### ISSUE TITLE
Unable to configure Subscription Manager Plugin

### ISSUE THREAD

**Issue by rbn491** [fnagel/t3extblog#272]
Hi, hope you are doing well.

I followed the installation guide (https://docs.typo3.org/p/felixnagel/t3extblog/7.2/en-us/Installation/Full.html) and the blog itself works fine, but i am currently having trouble getting the subscription manager to work. 
When adding the plugin to the page, after the refresh prompt, it wont`t show the selection field for the record storage page or any other configuration option. Am i missing something?

![sub_manager](https://github.com/fnagel/t3extblog/assets/24765173/e4bdf1f1-1243-453f-8d70-3bd77be1b814)

Here is my page structure and blog configuration:

![blog_structure](https://github.com/fnagel/t3extblog/assets/24765173/73613795-f72a-4e6b-89cd-92e8f04c2229)

![blog_config](https://github.com/fnagel/t3extblog/assets/24765173/6a063082-d3ee-4d43-9009-2b304c987f1c)

At the moment i am using TYPO3 v11.5.33 and t3extblog v7.2.0.

I also tested this in a local ddev project and the issue occured on a fresh TYPO3 11.5.34 installation with t3extblog 7.2.0 as well.

Thanks in advance and have a nice day :)

**Comment by fnagel** [comment]
Hi there!

> but i am currently having trouble getting the subscription manager to work.

Can you elaborate what exactly does not work?


> When adding the plugin to the page, after the refresh prompt, it wont`t show the selection field for the record storage page or any other configuration option. Am i missing something?

There is no configuration flexform for this plugin. It will use your TypoScript configuration, which looks good (even though, there are no PIDs visible in your page tree screenshot).

**Comment by rbn491** [comment]
Okay, i got it working.
Doing some more testing and checking my TypoScript config did the trick. Turns out i had a misunderstanding of how the subscription manager actually works. Additionally, there were some issues with my custom blog templates.
After fixing those, everything works now 👍

Thanks and have a nice day :)

**Comment by fnagel** [comment]
Glad to hear you were able to fix the issue!

If you have some idea how to make the docs better for this functionality, I'm always happy to merge PRs improving the extension :-)
