### ISSUE TITLE
Handling of 404 for blog directory works unexpectedly

### ISSUE THREAD

**Issue by alorotom** [fnagel/t3extblog#273]
Hello!

TYPO3: 9.5.31 with slug
t3extblog: 5.1.1

When I tried to access to not existing blog page the engine displays blog root page content with 200 code instead of correct handling of 404 issue. Is it possible to change this behaviour?

https://example.com/blog/blabla -- blabla doest not exists, but the blog root page (posts list view) will be displayed.

Outside the blog folder handling of 404 works as expected.

Could you please help and clarify how to handle it correctly?

**Comment by alorotom** [comment]
Looks like not related to the blog extension wrong 404 handling configuration.

**Comment by fnagel** [comment]
Please feel free to ask again if there are issues with the blog extension regarding 404 pages. It should work without issues.
Otherwise please close the issue.
