### ISSUE TITLE
Cannot access offset of type array in isset or empty in backend module -> Posts

### ISSUE THREAD

**Issue by helmutstrasser** [fnagel/t3extblog#279]
TYPO3 v12.4.17, t3extblog v8.0.1
When opening the backend module "Blog" and selecting "Posts" from the dropdown, the TypeError "Cannot access offset of type array in isset or empty" occurs in file Classes/ViewHelpers/Backend/LocalizationViewHelper.php line 89.

This is, because the foreach extracted $sysLanguageUid is not only the uid, its an array with the key as the uid.

Bugfix is on it's way.

**Comment by fnagel** [comment]
PR has been merged. Thanks a lot for your contribution!
