### ISSUE TITLE
Links in subscription emails doesn´t show up?

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#29]
When commenting a post, theres an option to be notified when new comments are written. Before that process starts, the person has to confirm the subscription. 

The generated confirmation mail has two issues (maybe I configured something wrong..):

- blogName is taken from the standard setup, my ownTS-override doesnt work
- theres no comfirmation link 

What if´ve done:

- created a page, insert the plugin (subscpription manager)
- set pid via TS

Best Regards
Christoph

**Comment by fnagel** [comment]
Screenshare aftermath:

* TypoScript generation in BE context seems incorrect
* Works for static TS from extensions but not inline TS config in template record
* Needs testing and a fix

**Comment by fnagel** [comment]
Ok, I've found the problem:

TYPO3 uses `module.` instead of `plugin.` TypoScript key for Backend TypoScript. That's why we copy the FE TypoScript into our module TS: https://github.com/fnagel/t3extblog/blob/typo3_62/ext_typoscript_setup.txt#L109

When we change the TS settings we need to re-add these values to the module TS array. So we need to make sure that this snippet is the latest TS code:
````
module.tx_t3extblog {
	email < plugin.tx_t3extblog.email
	persistence < plugin.tx_t3extblog.persistence
	settings < plugin.tx_t3extblog.settings
}
````

As this is to complicated and very error-prone (as someone could forget to do so) I've added a PHP solution. Just pull the latest changes and let me know if it works for you!

**Comment by criwe** [comment]
Well, better, but still some problems: 

- System 1 (raw t3extblog installation): wenn setting only 

plugin.tx_t3extblog.settings.blogsystem.pid = 123
plugin.tx_t3extblog.settings.blogName = Testblog TEST123
plugin.tx_t3extblog.settings.subscriptionManager.pid = 124
plugin.tx_t3extblog.settings.blogsystem.comments.approvedByDefault = 0
plugin.tx_t3extblog.persistence.storagePid = 125

It works! BUT: wenn I try to configure some things (i.e. Mailadress.. ) no mail is sent at all. Approving works fine.

- System 2 (live system, configured a lot): no mail is send. When approving a comment an error occurs: 

Fatal error: Call to a member function convertTypoScriptArrayToPlainArray() on a non-object in typo3conf/ext/t3extblog/Classes/Service/SettingsService.php on line 168

**Comment by fnagel** [comment]
Did you cleared all caches? Via install tool?

**Comment by criwe** [comment]
Yes

**Comment by fnagel** [comment]
Your fatal error says otherwise.

**Comment by fnagel** [comment]
Please make sure you really cleared all (!) caches. Clearing FE or all cache is not enough!

So, it works but fails when another config is set? Sounds not very reasonable.

Did you try to use the TS snippet instead?

**Comment by criwe** [comment]
Ok, I should not test right after waking up...  sorry.

Everything works fine! :-)
It think we could closes this ****** issue.

**Comment by fnagel** [comment]
Nice, I really put some time into this issue as it's a little complicated. Glad you are able give positive feedback :-D

Closed for now. Please re-open if needed.
