### ISSUE TITLE
Tag filter doesn´t work when using short tags

### ISSUE THREAD

**Issue by criwe** [fnagel/t3extblog#37]
Wenn using short tags ( 2 or less letters) nothing is filtered when clicking on these tags. After clicking, the starting page shows up, but using something like this as URL: domain.tld/tags/xy.html 
With 3 or more letters, it works fine.

**Comment by criwe** [comment]
Why?

**Comment by fnagel** [comment]
To prevent the cache from being filled with non existing pages. Also it doesnt seems very common to use tags short than three chars.

Any specific use case we're talking about?

**Comment by criwe** [comment]
yep, I´m using two short tags: IT and EU. The caching-problem is a good point, I think I just use other words for that and will put that point to the documation.

**Comment by fnagel** [comment]
Ok, if this is a common request we could change it without any hassle. It's just a string length check...

Please close when added to documentation.

**Comment by criwe** [comment]
I´ve allreay added this [closed]
