### ISSUE TITLE
Make use of PHP namespaces

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#41]
As we dropped 4.x support in master we should make use of PHP namespaces.

Related tasks: #19, #23

**Comment by cedricziel** [comment]
I'm in. Would you like me to PR to a different branch than master?

**Comment by fnagel** [comment]
Nice! Just for my curiosity: are you using t3blog or t3extblog in a project? We definitely need more testing and another active code contributor / reviewer would be very helpful!

No, master branch is fine. Perhaps you should wait until this evening or tomorrow as I'm about to release v1.0.0 (with minor changes regarding dependency config and documentation). 

Hint: Version 0.9.1 was a test flight to check documentation rendering on TYPO3 server and TER deployment (automated via Claus Due's gizzle plugins).

**Comment by cedricziel** [comment]
No, none of them, but we may need it in the near future. For now it's just a Kata of mine :)

**Comment by fnagel** [comment]
Feel free to ask questions if needed. 

I've pushed v1.0.0 so you have a clean base to start.

**Comment by cedricziel** [comment]
What is your desired namespace?

**Comment by fnagel** [comment]
I would suggest `TYPO3\T3extblog`. Whats your suggestion?

**Comment by cedricziel** [comment]
I always use my own vendor name, rather than ``TYPO3``. I'll happily use ``TYPO3\T3extblog`` on your command but assumed something like ``FNAGEL`` ;)

**Comment by fnagel** [comment]
Is there any objection against using a generic approach? If not, go for the `TYPO3\T3extblog` approach.

**Comment by cedricziel** [comment]
Nono, just preference :) On it..

**Comment by fnagel** [comment]
@cedricziel Just wanted to let you know I merged your branch and made some good progress: https://github.com/fnagel/t3extblog/tree/namespaceIt

Needs some more testing but seems to work fine so far.

**Comment by Ecmoechr** [comment]
Important

The TYPO3\CMS vendor name is reserved and may not be used by extensions!

and

Extension developers are free to use their own vendor name. However it may contain only one segment. Right:

\Webcompany


from: http://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Namespaces/Index.html

**Comment by fnagel** [comment]
We are not using the ``TYPO3\CMS`` vendor name. Should be no problem.

**Comment by fnagel** [comment]
@cedricziel Just released version 1.2.0 with your changes and full namespace support. This was the biggest step for TYPO3 7.x compatibility. Thanks again for your help!
