### ISSUE TITLE
layout and template override

### ISSUE THREAD

**Issue by m4chi** [fnagel/t3extblog#45]
Hi, thanks for the great plugin!
I’m fairly new to this, so maybe this is a simple mistake, but if I add it to a subpage of my website, it overrides or replaces the entire website layout and my bootstrap integration, as well as my content template. Is there any easy way to leave the site layout and settings intact and and use the website layout and templates, as well as the bootstrap css for the plugin?

**Comment by fnagel** [comment]
This seems like a TypoScript config issue to me. Hard to say whats wrong without seeing your TS. When used probably the usage of one of the plugins should not override your page setup but only show the corresponding templates within your page.

Are you using the default static TS? What's your TYPO3 version? Is there a demo link?

**Comment by m4chi** [comment]
Thanks a lot for getting back to me so quickly! Ill try to answer as much as I can. I'm running TS 6.2.9, and have included the blog extension on my root page under includes. This is the page link http://home.uni-leipzig.de/jgames
I'm attaching an image of how it looks without the extension included...
As for configuration, I've customized the file paths but not much more. This is my root-template typoscript:

constants

    plugin.tx_news.settings.cssFile = fileadmin/news/Public/Css/news-basic.css
    plugin.tx_news.view.layoutRootPath = fileadmin/news/Private/Layouts/
    plugin.tx_news.view.partialRootPath = fileadmin/news/Private/Partials/
    plugin.tx_news.view.templateRootPath = fileadmin/news/Private/Templates/

    plugin.tx_t3extblog.settings.blogsystem.pid = 47
    plugin.tx_t3extblog.persistence.storagePid = 51
    plugin.tx_t3extblog.view.layoutRootPath = fileadmin/t3extblog/Layouts/
    plugin.tx_t3extblog.view.partialRootPath = fileadmin/t3extblog/Partials/
    plugin.tx_t3extblog.view.templateRootPath = fileadmin/t3extblog/Templates/

setup

    config {
    	language = de
        locale_all = de_DE.UTF-8
      	htmlTag_setParams = lang="de" dir="ltr" class="no-js"
    }

    #LANGUAGE CONDITIONS#
    [globalVar = GP:L = 1]
      config {
        sys_language_uid = 5
        language = en
        locale_all = en_US.UTF-8
        htmlTag_setParams = lang="en" dir="ltr" class="no-js"
      }
    [global]

    [globalVar = GP:L = 2]
      config {
        sys_language_uid = 4
        language = ja
        locale_all = ja_JP.UTF-8
        htmlTag_setParams = lang="ja" dir="ltr" class="no-js"
      }
    [global]

    page = PAGE
    page {
      meta.viewport = width=device-width, initial-scale=1.0

      config {
    metaCharset = utf-8
     additionalHeaders = Content-Type:text/html;charset=utf-8
     }
  
     includeCSS.bootstrap = fileadmin/Public/Bootstrap/css/bootstrap.min.css
     includeCSS.bootstratheme = fileadmin/Public/Bootstrap/css/bootstrap-theme.min.css
     includeCSS.bootstrapcustom = fileadmin/Public/Css/custom.css
  
     includeJS.bootstrap = fileadmin/Public/Bootstrap/js/bootstrap.min.js
  
    10 = FLUIDTEMPLATE
    10 {
      file = fileadmin/Private/Layouts/Default.html
      layoutRootPath = fileadmin/Private/Layouts/
      partialRootPath = fileadmin/Private/Partials/
      variables {
            content_left < styles.content.get
            content_left.select.where = colPos = 0
            content_main < styles.content.get
            content_main.select.where = colPos = 1
            content_right < styles.content.get
            content_right.select.where = colPos = 2
        }
     
    file.stdWrap.cObject = CASE
    file.stdWrap.cObject {
          key.data = levelfield:-1, backend_layout_next_level, slide
          key.override.field = backend_layout
   
          default = TEXT
          default.value = fileadmin/Private/Templates/Standard_3-6-3.html
          1 = TEXT
          1.value = fileadmin/Private/Templates/Standard_3-6-3.html
        }
      }
    }

    plugin.tx_news.settings.displayDummyIfNoMedia = 0
    plugin.tx_news.settings.detail.showSocialShareButtons = 0


![jgames_noblog](https://cloud.githubusercontent.com/assets/11579473/7332965/247e01ce-eb5c-11e4-9ddf-4d3e92d2165f.jpg)

**Comment by fnagel** [comment]
Nice to hear you have solved your issue. Closing this, pleae reopen if needed.
