### ISSUE TITLE
frontend with error after installation 

### ISSUE THREAD

**Issue by stefan72** [fnagel/t3extblog#48]
Hi, 

After installing latest version 1.0.1 on TYPO3 6.2, I get the following error in the frontend:

XML Parsing Error: mismatched tag. Expected: </input>.
Location: http://www.domain.ch/
Line Number 6, Column 271:		<form action="daten-fuer-alle-seiten/suchergebnisse/" method="post" ><div class="input-group"><input name="tx_indexedsearch[sword]" value="" class="form-control" type="text" /><span class="input-group-btn"><input type="submit" class="btn btn-default" value="suchen"></span><input type="hidden" name="tx_indexedsearch_pi2[action]" value="search" /><input type="hidden" name="tx_indexedsearch_pi2[controller]" value="Search" /></div></form>
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^

Database was compared and updated, cache clered - perhaps a bug?
Best regards, Stefan

**Comment by fnagel** [comment]
Possible you've added the RSS static template for all pages?

**Comment by stefan72** [comment]
On 2/May/2015 7:39 PM, Felix Nagel wrote:
>
> Possible you've added the RSS static template for all pages?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fnagel/t3extblog/issues/48#issuecomment-98382032>.
>
Thanks Felix, that solved the issue.
And: thanks for the great blog extension :)

**Comment by stefan72** [comment]
Thanks Felix, that solved the issue.
And: thanks for the great blog extension :)

**Comment by fnagel** [comment]
Closed, please re-open if needed.
