### ISSUE TITLE
list view shows full length of blog post

### ISSUE THREAD

**Issue by stefan72** [fnagel/t3extblog#49]
Hi,
List and detail view works on my installation but I am unable to shorten the blog post on the list view. 
The full post is shown. It looks like this cannot be set?

Current TS settings
...
blogsystem {
      pid = 131

      posts {
        viewCount {
          # NOT IMPLENTED YET
          # views: Amount of seconds which have to pass by until an returning visitor is recounted.
          # if you want to have counted each view just put a negative number.
          # timePeriod = 10000
          # countBackendUsers = 1
        }

        paginate {
          itemsPerPage = 10
          insertAbove = 0
          insertBelow = 1
          maximumNumberOfLinks = 100
        }
      }

**Comment by prixxx** [comment]
Hello Stefan,
the t3blog is lacking of a lot of blog features. This is one option to crop the text in the list-view with plain TS:
[globalVar = GP:tx_t3extblog_blogsystem|post<1]
tt_content.text.20.stdWrap {
	crop > 
	cropHTML = 300 | ... | 1
	stripHtml = 0
}
[global]

**Comment by fnagel** [comment]
One can use the t3blog MORE marker functionality. Please see the documentation: http://docs.typo3.org/typo3cms/extensions/t3extblog/UsersManual/Index.html#blog-administration

Search for 'MORE'. 

This functionality needs improvement as its bad usability and bad working with more complex RTE HTML.

**Comment by prixxx** [comment]
Thanx for the answer. Not very handy - editors should not have to use marker like "###MORE###" when they write blog feeds.

**Comment by fnagel** [comment]
Yeah I agree. Its neither handy nor functional for complex HTML. This was needed for proper migration from t3blog to t3extblog. I think a extra field for a teaser (and another for an preview image) would be a much better solution. Please feel free to add feature request or a complete PR!

**Comment by fnagel** [comment]
Created feature request, see #52

Closed, please re-open if needed.
