### ISSUE TITLE
latest comments are not linked with blog post

### ISSUE THREAD

**Issue by stefan72** [fnagel/t3extblog#50]
If the t3extblog plugin 'latest comment's' is added, the comments are shown correctly but do not contain a link to the related article.

**Comment by criwe** [comment]
Hi!
In my Installation it works fine. How is your pagesetup, how do you integrate the latest posts? Maybe you forgot to set plugin.tx_t3extblog.settings.blogsystem.pid = .... ?

**Comment by stefan72** [comment]
Hi, thanks for reply, actually latest posts are working fine, but latest comments are not linked. Is this really working for you?

**Comment by criwe** [comment]
Oh, you´re right... my fault. Latest comments are not linked.

**Comment by fnagel** [comment]
Confirmed. I'm on it.

**Comment by fnagel** [comment]
Fixed, missed some needed arguments. 

I noticed another issue while fixing this one: #51
