### ISSUE TITLE
Extended CObjectViewHelper causes wrong realurl URLs

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#51]
When using ````<t3b:frontend.renderContent contentElements="{post.content}" />```` VH all links to a post after that are rendered with an appended "comment/post" segment. URLs look good without EXT:realurl. Seems this is an issue of the CObjectViewHelper our VH is based upon.

**Comment by fnagel** [comment]
Using the old TypoScript rendering lib does not change anything.

Works for list view which is strange enough. 

Any ideas how to properly fix this issue?

**Comment by stefan72** [comment]
Thank for looking at this and fixing latest comments links, unfortunately I am not good enough with programming to help. Someone else?

**Comment by fnagel** [comment]
Using something similar to 
````
$tt_content_conf = array('tables' => 'tt_content','source' => "45",'dontCheckPid' => 1);
$content .= $this->cObj->RECORDS($tt_content_conf);
````
does not work either. 

ToDo: test this in a plain TYPO3 installation to make verify if this could be a Core / realUrl issue.

**Comment by pvanhemmen** [comment]
Can not reproduce this in a clean TYPO3 7.3.1 Installation (Just realurl and t3extblog extensions installed). The anchor link is rendered as intended.

I should mention, though, that I could get realurl working with t3extblog only by including the realurl setup in the main template. Adding it to a seperate template to the page containing the blogsystem plugin only as mentioned in the documentation had no effect at all.

**Comment by fnagel** [comment]
Did you notice there is a workaround in the default templates? 

See here: https://github.com/fnagel/t3extblog/blob/typo3-7x/Resources/Private/Templates/Post/Show.html#L28-L31

**Comment by pvanhemmen** [comment]
Yes of course, for testing purposes I reverted back to the fluid tags that caused the problem, but everything worked as expected, at least for my setup.

**Comment by fnagel** [comment]
I think this needs to be tested in TYPO3 7.x -- perhaps it's just 6.x

**Comment by pvanhemmen** [comment]
Not sure what you mean, as mentioned I tested in TYPO3 7.x (7.3.1). This is what the fluid rendered anchor link looks like: http://typo3.domain.de/home/blog/article/2015/07/28/article-title/#comment-section

I'll set up a plain installation of TYPO3 6.2.x and test the link rendering again. Maybe it's a core bug already worked out in 7.x.

**Comment by fnagel** [comment]
I've fixed this just a few month ago, see f943fade0c5e02163a013e818370f2919f14b26e

Some testing would be great!

By the way: I've tested the 7.x branch in 6.2 and it seems to work -- next step to a 7.x compatible version in TER :-D

**Comment by pvanhemmen** [comment]
I tested exactly the setup that caused the problem mentioned in this ticket (not the temporary fix):

```html
<f:if condition="{post.content}">
	<div class="content">
		<t3b:renderContent contentElements="{post.content}" />
	</div>
</f:if>

<div class="bottom row-fluid">
	<div class="span4">
		<span class="badge">
			<f:link.action controller="Post" action="show" arguments="{post.linkParameter}" class="test" section="comment-section">
				<f:count subject="{post.comments}" /> <f:translate key="post.comments" />
			</f:link.action>
		</span>
		<f:link.action controller="Post" action="permalink" arguments="{permalinkPost: post.uid}" class="permalink">
			<i class="icon-link"></i>
			<f:translate key="post.permalink" />
		</f:link.action>
	</div>
	<div class="span8 text-right">
		<f:render partial="Post/TagCloud" arguments="{post: post}" />
	</div>
</div>
```

See the `<f:link.action>` tag? Just to make sure I tested this issue in a plain install of 7.x as well as 6.2.x - and I can not reproduce the bug. Added a `class="test"` to the link to double check it's really this very link. This is how the link gets rendered in both 6.2.x and 7.x:

```
<a class="test" href="http://typo3.domain.de/home/blog/article/2015/07/30/article-title/#comment-section">
    0 comments
</a>
```
This is correct link rendering, no additional "comment/post" segment.

Looking forward to the milestone 2.0.0! If you need any help please let me know. ;-)

**Comment by fnagel** [comment]
Ok, thanks for testing. I need to check this again, perhaps it was just me or a fixed core bug. 

What TYPO3 versions did you test in?

**Comment by pvanhemmen** [comment]
6.2.14
7.3.1

**Comment by fnagel** [comment]
Still experiencing this issue. Seems related to my configuration.

Just for my curiosity: what real URL versions are you using?

**Comment by fnagel** [comment]
Real world example straight from introduction package:

````
http://7x.typo3.dev/content-examples/blog/article/2015/06/21/test-2-en/comment/Post/#comment-55
````

where .../test-2-en/**comment/Post**/... is the problem.

**Comment by pvanhemmen** [comment]
Since I cannot reproduce the error on my end, I have setup a typo3 install where link rendering actually works, so at least you can compare settings between installations. Will email you link and login details. t3extblog is up to date except for the workaraound that I have removed as mentioned above. Hope that helps detecting the error.

**Comment by fnagel** [comment]
No idea why but I can't reproduce this in the introduction package any more. I took a look at your demo installation, thanks for providing access!

**Comment by fnagel** [comment]
Not sure why this is still an issue in my actual installation. It seems I need to dig deeper into this issue...

**Comment by fnagel** [comment]
Seems this issue of mine is somehow related to the skipDefaultArguments extbase feature and this snippet: https://github.com/fnagel/t3extblog/blob/master/Classes/Hooks/RealUrl.php#L96-L103

When disabling these lines only my comment anchor links have an additional
````
?tx_t3extblog_blogsystem%5Bcontroller%5D=Post&cHash=33311976b0eab59f531bee2aea3ab81d#comment-920
```` parameter. When disabling skipDefaultArguments for t3extblog, all post show links have this addition (which is correct). I really do not understand this.

**Comment by fnagel** [comment]
@pvanhemmen I think I found the issue: Please try to add a plugin CE to your blog post content. This seems to break the link rendering.

**Comment by fnagel** [comment]
Proposed fix:

````
    'GETvar' => 'tx_t3extblog_blogsystem[controller]',
    'noMatch' => 'bypass',
    'valueMap' => array(
        'new' => 'Comment',
    ),
````

in RealUrl config.

**Comment by fnagel** [comment]
@pvanhemmen Would you mind to test this? Adding any plugin should cause this issue.

**Comment by pvanhemmen** [comment]
@fnagel I was finally able to reproduce this with a custom CE added to the blog post as you suggested. The link rendering was not affected by this bug when adding standard Content Elements.

Your fix works as excpected. Good catch!

**Comment by fnagel** [comment]
Nice! Thanks for the feedback.
