### ISSUE TITLE
BE Module: Tab "Comments" does not list comments

### ISSUE THREAD

**Issue by romaneberle** [fnagel/t3extblog#54]
Switching from "Posts" to "Comments" in backend module does not list existing comments. Bug or feature?
(t3blog did list existing comments.)

**Comment by fnagel** [comment]
The BE module needs some love anyway but it "should" say "No comments found" when no more pending comments are available. Can you give me the exact steps to reproduce this?

**Comment by romaneberle** [comment]
no special steps required to reproduce this, just have some (approved/non-spam) comments on some posts, and choose "Comments" from tab/funcmenu in backend module. t3blog used to list these, t3extblog doesn't. that's why i was asking "Bug or feature?". maybe it's a new feature.
pending comments look fine as far as I can tell. 

(btw., can I get write-access to the project? so I could fix the obvious without bothering someone else. sorry for asking, I'm completely new to github)

**Comment by fnagel** [comment]
I've added a "list all comments" view as default. Please give feedback!

For now I would prefer if you send Pull Requests against my repo. We sure can talk about giving you full access to the repo some time. Take a look here: https://guides.github.com/activities/contributing-to-open-source/#contributing
