### ISSUE TITLE
BE Module: bad translation key "backendUserListing"

### ISSUE THREAD

**Issue by romaneberle** [fnagel/t3extblog#56]
unused / wrong translation key "backendUserListing" found in

Resources/Private/Backend/Templates/BackendComment/List.html, line 9:
 f:translate key="backendUserListing" All comments for post /f:translate

and

Resources/Private/Backend/Templates/BackendPost/Index.html, line 22:
f:translate key="backendUserListing" Post Listing /f:translate

**Comment by fnagel** [comment]
Related to #55
