### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by m4chi** [fnagel/t3extblog#58]
Hi again,
Thanks for all the work with this! I've been playing around with this a bit more and was wondering if you had any plans for multi language support, or, in case I am just ignorant, if it is already possible to create posts in multiple languages? I can imagine workarounds (i.e. using the categories), but it would be much easier if this was possible via the existing typo3 multi language support.

**Comment by fnagel** [comment]
This extension definitely aims to support all TYPO3 default features -- incl. localization.

I must confess I did not try this as I did not need it for my own project. This should be possible as the SQL from t3blog is still there but the TCA config is missing. 

A workaround (which should work at the moment) is to use different storagePids for each language.

**Comment by m4chi** [comment]
Thanks a lot! I�m really sorry that I can�t contribute more� lack of skills is never a good excuse, I know. But the workaround should do for now.

**Comment by fnagel** [comment]
@m4chi I've pushed a branch with multi language support. Would you mind to test and give feedback?

https://github.com/fnagel/t3extblog/tree/multilanguage

@criwe Are you able to test this too? 

PR: https://github.com/fnagel/t3extblog/pull/65

**Comment by m4chi** [comment]
That’s great, thanks a lot!
It also seems to work in general (as you can see in the screenshot, the title is displayed in both languages).

However, my content (random text) is not shown, even when I click on the header… At least the German version is not hiden. With the English version, I experienced that the red „hidden“ symbol on the left does not disappear even when I turn on the lightbulb on the right. Also, a minor glitch: the tab captions are not displayed (see screenshot).

I need to turn the blog-function off now for more testing (and also because the comment fields are messed up by bootstrap 3), but I can turn it back on for a short time in case you need to look at the site itself.
Thanks for all the work!
Martin

**Comment by fnagel** [comment]
Are you aware of TYPO3's localization features? What you see in the screenshots is the default prefix for translated records. You will need to adjust the translated record. 

Are you using the default localization steps (adding default first, then a translated one by using the language select)?

Please try clearing your cache, if needed use the install tool clear all caches button too. The BE translations have changed and the cache needs to be regenerated.

I would need BE access to see what's happening.

**Comment by m4chi** [comment]
Yes, thanks - that is why I said that it works. I had taken the right steps but not cleared that cache with the install tool - which worked wonders. Tabs are back and so is the blog post content! Thanks for the advise and patience. I’ll play with this a while...

**Comment by fnagel** [comment]
Nice!

Let me know if any issues with the mulitlanguage feature appear!

**Comment by fnagel** [comment]
I noticed subscription handling is not working as expected. I'm on it.

**Comment by fnagel** [comment]
ps: Already added a fix for correct comment listing and a small BE improvement for hiding the preview image link field. BE module now shows if any translated records for each post exist.

**Comment by fnagel** [comment]
Ok, I've added a bunch of fixes and improvements. Would you mind to test @m4chi and @criwe ?

You will need to update your t3extblog files and DB.

**Comment by criwe** [comment]
Very nice solution for the backend module. I´ve tested a bit, works fine!

**Comment by m4chi** [comment]
Dear Felix,
I'm sincerely sorry but I have to lay off for a while. As much as I want to dig deeper into typo3 and contribute to your great work with the blog extension, I also have to admit that setting up my page with typo3 was too ambitious given my own workload and also due to the fact that the blog we're working on will be written by multiple authors - none of whom knows typo3.
All lame excuses and I am quite frustrated and feel bad about it, but unless my work focuses more directly on typo3, I won't be able to return to this.
I with you all the best with the extension and really hope that I might be able to get involved again sometime in the future. Sorry for letting you down.

**Comment by fnagel** [comment]
No problem. TYPO3 is not that easy to learn.

Multi  language support is merged to master branch.
