### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by m4chi** [fnagel/t3extblog#59]
All looked good but when I tried to submit a comment I got a 500 error. Had these before, but they were gone after our system admin updated the account to php 5.5. Any idea why this is triggered by access to anything comment-related?

**Comment by fnagel** [comment]
No, any more specific error message? Checked TYPO3 syslog and apache error log?

**Comment by m4chi** [comment]
That was quick, thanks!
The logs recorded the following message:
> [14-May-2015 11:03:57 Europe/Berlin] PHP Catchable fatal error:  Argument 1 passed to TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper::render() must implement interface TYPO3\CMS\Extbase\Persistence\QueryResultInterface, instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage given in XXX/typo3_src-6.2.9/typo3/sysext/fluid/Classes/ViewHelpers/Widget/PaginateViewHelper.php on line 67

**Comment by fnagel** [comment]
Did you change the templates? It seems you are using the default paginator of Fluid, which is not capable of processing ObjectStorages. That's why t3extblog comes with an getter for returning the raw QueryResultInterface. See here: https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Templates/Post/Show.html#L54

Note the ````{post.commentsForPaginate}```` usage!

**Comment by fnagel** [comment]
> That was quick, thanks!

Working on the BE module translations :-)

**Comment by m4chi** [comment]
Thanks a lot for the help. Everything running smoothly again. It seems like I made a mistake when trying to adjust the style to bootstrap 3.4... Will try to identify the problem later on... Looking forward to the translations feature. I think actually the workaround you mentioned earlier could be problematic when you want to have people subscribe to the blog (btw., this didn't work for me yet...) but not only their specific language... Anyways, many thanks so far. I'll get back to you if I can produce anything useful in terms of bootstrap 3 styling.

**Comment by laxmanAppminds** [comment]
Hi, can you please let us know where the syslog or Apachelog exist in the typo3 setup. Becuase i mma new for this environment. Kindly help us.

Thanks,

Lakshman kumar.M

**Comment by fnagel** [comment]
Depends on your configuration and version.

Search here: Log Module (in backend), typo3temp/logs/ and default Apache logs.

**Comment by laxmanAppminds** [comment]
Thanks for giving update. I will check it now.

**Comment by fnagel** [comment]
Make sure TYPO3 debugging and logging is enabled! Check pre-configurations in install tool!

Please open a new issues for your problem.
