### ISSUE TITLE
500 internal server error when creating a new comment

### ISSUE THREAD

**Issue by thariel** [fnagel/t3extblog#60]
Redirect Path: blog/?tx_t3extblog_blogsystem%5Bpost%5D=4&tx_t3extblog_blogsystem%5Bday%5D=15&tx_t3extblog_blogsystem%5Bmonth%5D=05&tx_t3extblog_blogsystem%5Byear%5D=2015&tx_t3extblog_blogsystem%5Bcontroller%5D=Comment&cHash=c5f601707c465af8b628e38ae62a39c0#comment-section"

The comment is created successfully.

Is there any way to configure the redirect path/site?

Typo3 Version 6.1.7
PHP-Version: 5.3.29

Any ideas? Please help!

**Comment by fnagel** [comment]
Please post the stacktrace and your TS config.

Did you configure all needed page PIDs in the setup?

**Comment by thariel** [comment]
My TS Config:

==========================================
# PID where your blogsystem is included
plugin.tx_t3extblog.settings.blogsystem.pid = 80
# PID where you will store your blogposts
plugin.tx_t3extblog.persistence.storagePid = 74
plugin.tx_t3extblog.settings.blogName = NL Blog
plugin.tx_t3extblog.settings.latestPosts = 1
==========================================

Error message:

Fatal error: Call to undefined method Tx_T3extblog_Controller_CommentController::addFlashMessage() in /usr/www/users/netlun/typo3conf/ext/t3extblog/Classes/Controller/AbstractController.php on line 107

**Comment by fnagel** [comment]
Seems to be related to the flashMessage change documented here: http://wiki.typo3.org/Breaking_Changes#Extbase

In ````t3extblog/Classes/Controller/AbstractController.php```` change line 104-108 to:

````
if (version_compare(TYPO3_branch, '6.1', '<')) {
	$this->flashMessageContainer->add($localizedMessage, $localizedTitle, $severity);
} else {
	$this->addFlashMessage($localizedMessage, $localizedTitle, $severity);
}
````
Note the version change (6.0 -> 6.1).

Would you mind testing if this change helps?

**Comment by thariel** [comment]
Thanks for your fast response!
Unfortunately the same error appears after I changed the code.

**Comment by fnagel** [comment]
Cleared cache? Perhaps manually delete ````/typo3temp/Cache````?

I do not have time to set up a fresh 6.1 installation, so please try again with `````6.2````as condition.

**Comment by thariel** [comment]
Upgraded successfully to 6.2.12. Now it works! Thanks for your help! :+1:  :)

**Comment by fnagel** [comment]
Nice you've git it working!

Did you check if the proposed fix helps? Would be nice to have this checked and fixed!

**Comment by thariel** [comment]
I used the code you've posted above with version 6.1 and its working. Thanks again!

**Comment by fnagel** [comment]
Nice, thanks for testing!

I will add this: 

````
if (version_compare(TYPO3_branch, '6.2', '<')) {
    $this->flashMessageContainer->add($localizedMessage, $localizedTitle, $severity);
} else {
    $this->addFlashMessage($localizedMessage, $localizedTitle, $severity);
}
````
