### ISSUE TITLE
Pagination ViewHelper doesn't meet Twitter Bootstrap 3.x conditions

### ISSUE THREAD

**Issue by m10a** [fnagel/t3extblog#66]
Hi,
the pagination ViewHelper doesn't meet Twitter Bootstrap 3.x conditions. The pagination class should be placed in the ul-tag not in the surrounding div (see line 18 and 19 in Templates/ViewHelpers/Widget/Paginate/Index.html).

**Comment by fnagel** [comment]
This extension currently implements Twitter Bootstrap 2.x for all templates. There is already a ticket for an update: #24
