### ISSUE TITLE
conflict with yag

### ISSUE THREAD

**Issue by Ecmoechr** [fnagel/t3extblog#71]
t3extblog seems to conflict with yag i suppose. if one of both is active, all functions in both extensions are ok, if both are active, the list of plugins in the flexform can't be opened/changed. are any corrections or workarounds available?

**Comment by Ecmoechr** [comment]
this mystacle only appears in FF (i.e. 38.0.5), not IE (11) not actual Chrome

**Comment by fnagel** [comment]
Do you have a screenshot? What TYPO3 and yag versions are effected? What version of t3extblog are  you using?

**Comment by Ecmoechr** [comment]
Sorry for missing versions:
yag 4.0.5
t3extblog 1.1.0
t3 6.2.13
problem is, that the selectbox is not to be opened. ff freezes, if selectbox is clicked.
![unbenannt](https://cloud.githubusercontent.com/assets/13003534/8301373/a1d2b87c-198d-11e5-884d-9020aa9f9312.PNG)

**Comment by Ecmoechr** [comment]
hello Felix,
the failure reported seems to be originated in an icon sized 64x64 from yag (ext_icon.png). i changed yag to use gif sized 16x16 instead of png and all things are going well.
obviously ff cannot handle oversized icon in select-boxes well. i do not know, why this is seen only, when your extension and yag are active.
thank you for your investigations
chris

**Comment by fnagel** [comment]
64x64 is used for TYPO3 7.x versions. Perhaps this is worth a bug report in yag's bugtracker? Did you noticed this happens with other extensions and yag or is it only t3extblog? Would you mind testing the latest master version of t3extblog?

**Comment by Ecmoechr** [comment]
sorry to say, that it is the same effect with current master 2.x-dev . . .
i do not remember exactly but i asked them to use 16x16 for inkompatibility issue with T3V6.x . . .

**Comment by fnagel** [comment]
Any news on this issue?

**Comment by Ecmoechr** [comment]
hello Felix,
thanks for asking.
nothing heared from the yag-guys yet.

**Comment by fnagel** [comment]
Hey @Ecmoechr 

is this still an issue?

**Comment by Ecmoechr** [comment]
id did not have a look into it for months. think, it can be closed. thanks for help!
