### ISSUE TITLE
Changing Template dirs

### ISSUE THREAD

**Issue by prentice87** [fnagel/t3extblog#72]
Hi i added the lines

````
plugin.tx_t3extblog.persistence.storagePid = 178
plugin.tx_t3extblog.settings.blogsystem.pid = 97
plugin.tx_t3extblog{
  view {
    templateRootPath = fileadmin/sys/t3extblog/Templates/
    partialRootPath = fileadmin/sys/t3extblog/Partials/
    layoutRootPath = fileadmin/sys/t3extblog/Layouts/
  }
}
````

to my Constants inside my Template in the Typo3 7... branch. Somehow he will not accept it. I cleared the cache multiple times but no changes. Am I doing something wrong?

**Comment by fnagel** [comment]
Are you aware there is a 7.x branch?
https://github.com/fnagel/t3extblog/tree/typo3-7x

Still has issues, seems VH caching has been changed. Still searching for a solution. Help wanted, sponsoring possible!

**Comment by prentice87** [comment]
Yes without that branch i couldn't even get it to work on 7.3.1
If i had any idea how to write extensions, i would gladly help. I also couldn't get RealURL to work with the 7x branch. But i do like the new Preview/Teaser feature.

What do mean by sponsoring?
I would love a proper Blog Extensions that allows more flexible things and allows the view of a blog post on a different page than the one where categories can be selected.

**Comment by fnagel** [comment]
Please try this (as constants or setup):

````
plugin.tx_t3extblog{
  view {
    templateRootPath  {
10 = fileadmin/sys/t3extblog/Templates/
}
  }
}
````


> I also couldn't get RealURL to work with the 7x branch.

Please open a new issue for this problem.

> But i do like the new Preview/Teaser feature.
> What do mean by sponsoring?

It's possible to sponsor features or bugfixes in order to speed up and to
support further development.

> I would love a proper Blog Extensions that allows more flexible things
and allows the view of a blog post on a different page than the one where
categories can be selected.

Please open a new issue for this and explain your feature request in detail.

**Comment by fnagel** [comment]
>  I also couldn't get RealURL to work with the 7x branch.

Just tested this again: works without issues. Tried to manually truncate realurl tables?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by prentice87** [comment]
Sorry i couldn't get to work and switched to tx_news because i need the features included there.

**Comment by fnagel** [comment]
Thanks for your feedback.
