### ISSUE TITLE
Documentation: Improve installation and user manual 

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#78]
Simplify and fool-proof installation guide and document new constants (4eb06f81cc7f9692e748cab53956bd8bb2726f49).

* [x] Update images
* [x] Document new constants 
* [x] Add minimal (via constants) and extended setup instructions (via own TS)
* [x] Add extended TS setup example
* [x] Update *user manual* with preview tab guide
* [x] Make *user manual* more step by step after installing extension
* [x] Document how to overwrite templates in TYPO3 7.x, see [here](https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/Start/Index.html) or [here](https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/GoodToKnow/Templates/Index.html)
* [x] Improve RealUrl docs (hint when not using RealUrl autoconfig feature, aka adding config manually)

**Comment by criwe** [comment]
If help wanted, drop me a line. I should have some spare time in september and want to set up a new small blogproject.That would be a good point to enhance the documentation.

**Comment by fnagel** [comment]
Yes, help is appreciated!

I had multiple email and even phone (!) contacts with issues installing t3extblog. Guess we have some room for improvements. That's why I introduced some constants (see above commit) to do ease up the installation. Perhaps it is helpful to explain basic steps (use constants editor) or extended (copy TS and adjust whats needed).

I've added a proposed list above, it's incomplete and every point is changable. Input welcome!

**Comment by criwe** [comment]
Just a reminder for myself: 
Both settings needed:
plugin.tx_t3extblog.persistence.storagePid = 123
module.tx_t3extblog.persistence.storagePid = 123 (comments, be)

**Comment by fnagel** [comment]
Right, the module key TS settings is needed for BE. See this line: https://github.com/fnagel/t3extblog/blob/master/Configuration/TypoScript/setup.txt#L245

When overwriting the Plugin TS, one will need to reassign the settings to BE settings.

ps: I've started a to write some basic tests which will make sure all needed TS settings are available.

**Comment by fnagel** [comment]
@criwe  I've added some config checks and made sure storagePid is not needed in BE context. Please test again with latest code if the module.tx_t3extblog.persistence.storagePid is really NOT needed. 

Anyway, TS Settings are needed to be assigned to the module key when changed.

**Comment by criwe** [comment]
Commited some changes in the documentation (and the constants.txt). More will follow the next days.

**Comment by fnagel** [comment]
@criwe Any more changes? Would you mind pushing ecerything? 

I would like to rebase your changes onto master and create an PR. Now that it seems t3extblog is compatibly with TYPO3 7.6 I want to release it asap.

**Comment by criwe** [comment]
@fnagel I´ve just uploaded some more changes. Should be enough to release the next version.

One error occured while writing the documentation:

![error](https://cloud.githubusercontent.com/assets/7531138/11168659/01ae7a60-8b99-11e5-8221-310fc14a323f.jpg)

I´ve used TYPO3 6.2. with newst sphinx-stuff, that may be the reason. Rendering works fine

**Comment by fnagel** [comment]
@criwe Mhh, when exactly does that error occur? I'm not able to reproduce this with TYPO3 7.6 and latest TER sphinx and restdoc. Works like a charm.

What I got are some small CGL issues which will be fixed in my next commits:
````
QuickInstallation/Index.rst:20: WARNING: Title underline too short.

Quick installation guide
--------------------
````

**Comment by criwe** [comment]
@fnagel ok, I´ve fixed it (could you please recheck? I need to do it via texteditor, because I´ve update my "documentation installation" and it´s not working 100%).

The error occured on every page. I´ve found an forum post of xavier, he stated that it could be the TYPO3 Version (in my case 6.2).

**Comment by fnagel** [comment]
I've merged your changes and added a bunch of additions and fixes. Please see master branch! Should work without issues...

**Comment by fnagel** [comment]
@criwe Please note: I've removed some (hopefully) unneeded images. Please re-check and make sure not to add obsolete images to the repo.

See: https://github.com/fnagel/t3extblog/commit/ac7c2a13b2158c06f069cb7beca9d4ed1ca3fef0
