### ISSUE TITLE
Missing Categories for localized Posts

### ISSUE THREAD

**Issue by andreasjobst** [fnagel/t3extblog#80]
Is there a possibility to add categories for already localized posts. I have some localized posts and the category is N/A. If I try to edit these categories the localized posts have no field to set these categories in the TYPO3 backend.

**Comment by fnagel** [comment]
No, currently a localized post always has the same categories as its parent (the default language). Seems a valid assumption to me. What's your use case?

Seems this should be possible without too much trouble. You could try to change the ````l10n_mode```` mode in post TCA for field `````cat`````.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by andreasjobst** [comment]
Sorry for the late reply. I was on holiday and forgot about this issue afterwards. As far as I remember it was a mistake in our configuration. I think we did not localize the blog storage folder and therefore the localization of the categories did not work?

**Comment by fnagel** [comment]
Seems reasonable. Closed, please re-open if needed.
