### ISSUE TITLE
Wrong title in EXT:indexed_search

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#85]
Migrated from https://github.com/fnagel/t3extblog/issues/79#issuecomment-139855579

Probably not 2.0.0. related. But Search Indexed Blog Posts always have a trailing slash appended at their title:
![search](https://cloud.githubusercontent.com/assets/715022/9836022/b947b910-5a08-11e5-9e07-3a13d58ac9b3.png)

**Comment by fnagel** [comment]
I assume this is related to these files / lines:

https://github.com/fnagel/t3extblog/blob/master/Classes/ViewHelpers/Frontend/TitleTagViewHelper.php#L51

https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Partials/Post/Meta.html#L3

I think we need to move the VH line mentioned above within the $prepend if condition. Would you mind to test this?

**Comment by pvanhemmen** [comment]
Will test and give feedback ASAP

**Comment by pvanhemmen** [comment]
Your proposed fix works. I just moved the line after the if condition, so the allocation takes place in every case (does it make sense to make it dependent on the prepend condition)?

On the other side, this only fixes it when $prepend really is true, since the slash is always part of the title itself as defined through the template. My proposed fix would be to intoduce a "separator" attribute to the viewhelper and do concatanation in the viewhelper itself, and only when the $prepend condition is true.

**Comment by fnagel** [comment]
Idea behind having the prepend option is to have something like this "Post Title / Blog (PAGE NAME)  - MyDomain.com (STATIC DEFAULT BY TS)",but you could have post title only by modifying the template.

My idea will not work when not using the prepend option, so you're right. Why not just use something like this:

````
public function render($prepend = TRUE) {
	if (TYPO3_MODE === 'BE') {
		return;
	}
	
	$content = $this->renderChildren();
	
	if (empty($content) !== TRUE) {
		
		if ($prepend === TRUE) {
			$content = $content . $GLOBALS['TSFE']->page['title'];
		}
		
		$GLOBALS['TSFE']->indexedDocTitle = $content;
		$GLOBALS['TSFE']->page['title'] = $content;
	}
}
````

Or adding a specific parameter for search title -- probably our best way to go.

**Comment by pvanhemmen** [comment]
That's the version I've been testing. But this won't fix it, since when `$prepend === FALSE` this will leave you with the same title as before.

**Comment by fnagel** [comment]
I assumed when using `$prepend === FALSE` one would change the content of the VH tag as it doesn't make sense to use `{post.title} / ` it this case.

Can you give me an example fluid code for your use case?

**Comment by pvanhemmen** [comment]
You're right, I wasn't thinking of an actual use case. So your proposed fix is the way to go. Thanx!

**Comment by fnagel** [comment]
Ok, thanks for the feedback.

Added the proposed fix AND a new parameter for specific search index title. This should cover all needed use cases. New default for search title is the blog post title.
