### ISSUE TITLE
RealUrl Config is not working, no information in documentation

### ISSUE THREAD

**Issue by sxbxstxxn** [fnagel/t3extblog#86]
I put the additional realurl config in the additional template for the blog site (also tried in root template) and I added the /Configuration/TypoScript/RealUrl/setup.txt to my typoscript. But after deleting all caches nothing happened. I still have links with get parameters in it. I hope the realUrl issue is for creating nice links on the blog detail page ;)
Any ideas what could be the problem?

**Comment by fnagel** [comment]
> I put the additional realurl config in the additional template for the blog site (also tried in root template) and I added the /Configuration/TypoScript/RealUrl/setup.txt to my typoscript. 

This sounds like you added it twice? Adding https://github.com/fnagel/t3extblog/blob/master/Configuration/TypoScript/RealUrl/setup.txt on the blogystem plugin page should be enough.

You will need to use the provided RealUrl config, which will be added auto magic when using RealUrl autoconfig feature. See https://github.com/fnagel/t3extblog/blob/master/Classes/Hooks/RealUrl.php

**Comment by sxbxstxxn** [comment]
I'm sorry. I meant I first added it to the ext template (see picture)

![tmp1](https://cloud.githubusercontent.com/assets/5513276/10166388/14d7a26e-66c4-11e5-98c8-127ca2b5041d.jpg)
and then added the /Configuration/TypoScript/RealUrl/setup.txt in the typoscript setup.

**Comment by fnagel** [comment]
> and then added the /Configuration/TypoScript/RealUrl/setup.txt in the typoscript setup.

First step should be enough. 

Did you add the RealUrl postVarSets config to your RealUrl configuration?

**Comment by sxbxstxxn** [comment]
Ok, great. Now it's working. It's a little bit confusing in the documentation. So I don't change my typoscript, just do step 1 (on the picture). 
But I have to add the postVarSets to my realURL configuration. It's not added automatically.
But it's fine now. Thanks for help!

**Comment by fnagel** [comment]
We know the documentation needs improvement. We could need some help or hints, please see: #78 

 Did you noticed this section: https://github.com/fnagel/t3extblog/blob/master/Documentation/Configuration/Index.rst#realurl
