### ISSUE TITLE
No template found in Backend

### ISSUE THREAD

**Issue by sxbxstxxn** [fnagel/t3extblog#87]
When I try to execute the backend module "T3Extblog" I got an error

"The technical reason is: No template was found. View could not be resolved for action "index" in class "Tx_T3extblog_Controller_BackendPostController"."

But all templates are implemented. I also tried different orders of the typoscript but I have no idea what is the problem... I can edit the blog entries with the list module but the T3Extblog Module throw this error... Any ideas?

**Comment by fnagel** [comment]
You should check the TS in the TypoScript Object Browser (info module). Make sure `module.tx_t3extblog.view` configuration is available.

In addition: It seems you are using an outdated version of t3extblog. You should update asap!

**Comment by sxbxstxxn** [comment]
Ok I checked it. I can find it in typoscript Object Browser
![tsobjectbrowser1](https://cloud.githubusercontent.com/assets/5513276/10274423/e2024122-6b3d-11e5-8f71-6e96df99d1fa.jpg)
But are this the correct entries? That are my changed folders for frontend templates. I think it's because of this line of typoscript:
module.tx_t3extblog < plugin.tx_t3extblog

But if I comment this line out and so change it to the Backend templates there is another error when calling the "T3extblog" backend module:
#1344375003: No settings detected. This module can not work then. This usually happens if there is no frontend TypoScript template with root flag set. Please create a frontend page with a TypoScript root template. (More information)

**Comment by sxbxstxxn** [comment]
there is no update available in the extension manager (working with version 1.1.0).
Do I have to instlall it new with version 1.2.1 from repository?

**Comment by sxbxstxxn** [comment]
After updating to version 1.2.1 nothing changed in backend but I got an error in Frontend:
#1289386765: Could not analyse class:Tx_T3extblog_ViewHelpers_Frontend_RenderPreviewViewHelper maybe not loaded or no autoloader? (More information)

**Comment by gabip21** [comment]
Hi, i had just the same problem. 
I had the static template of t3extblog on a suppage. After removing it to the root page, the module works.
Maybe it is the solution for you, too.

**Comment by fnagel** [comment]
> module.tx_t3extblog < plugin.tx_t3extblog

Is needed to assign the config to the BE context. The error message is correct when this snippet is removed.

I'm not quite sure what's the issue here. Which version of TYPO3 are you using? Latest 6.2?
Try gabip21's hint and add the static TS in your root TS template. When changing it later you need to add the above code snippet again.

Another idea: try to add the following TS to make sure the BE templates use the default ones:
````
module.tx_t3extblog {
	view {
		templateRootPath = EXT:t3extblog/Resources/Private/Templates/
		partialRootPath = EXT:t3extblog/Resources/Private/Partials/
		layoutRootPath = EXT:t3extblog/Resources/Private/Layouts/
	}
}
````

**Comment by sxbxstxxn** [comment]
I tried everything, putting it to the root template has no effect.
If I try the snippet for the module.tx_t3extblog.view I got the php error above "No settings detected". Thats confusing because the files ARE there, I checked it...

**Comment by sxbxstxxn** [comment]
Ok, now it's working!!

Solution:
1. Put the typoscript in the root template
2. copy the Backend Templates to fileadmin
3. add following to your typoscript 
<code>
module.tx_t3extblog < plugin.tx_t3extblog

module.tx_t3extblog {
    view {
        templateRootPath = fileadmin/t3extblog/Backend/Templates/
        partialRootPath = fileadmin/t3extblog/Backend/Partials/
        layoutRootPath = fileadmin/t3extblog/Backend/Layouts/
    }
}
</code>
 
It's important that all the lines from the last code are there. A little bit confusing because I do not really know what was/is the problem, but it's fine now. Thx for help!

**Comment by fnagel** [comment]
Nice! Glad to hear it finally works for you!

> copy the Backend Templates to fileadmin

You did not copy all files but only some? It will definitely fail! Copy parts of the templates / partials / layout will only in TYPO3 >= 7.x

Copying all files and using this should work:
````
plugin.tx_t3extblog {
    view {
        templateRootPath = fileadmin/t3extblog/Backend/Templates/
        partialRootPath = fileadmin/t3extblog/Backend/Partials/
        layoutRootPath = fileadmin/t3extblog/Backend/Layouts/
    }
}
module.tx_t3extblog < plugin.tx_t3extblog
````

When using the latest master branch you are able to just change the TS constants instead!

**Comment by sxbxstxxn** [comment]
I copied all files and it's working.
But using the path from EXT is not working!
