### ISSUE TITLE
Upcoming version 2.0.0: Not possible to add/edit/change Content Elements via IRRE in TYPO3 7.5

### ISSUE THREAD

**Issue by pvanhemmen** [fnagel/t3extblog#88]
I'm not able to add/edit/change Content Elements of any type in TYPO3 7.5 within t3extblog posts anymore. Saving gives the following error:

![error](https://cloud.githubusercontent.com/assets/715022/10267240/17139016-6a8d-11e5-8367-db396670890c.png)

Anyone else experiencing this issue or is it just me? There are no entries in the php error log, editing CE in other extensions via IRRE work. To be honest I've got no clue whats going on. Investigating...

**Comment by fnagel** [comment]
I'm able to reproduce this issue.

**Comment by fnagel** [comment]
This seems only to fail when using the module. List module works as expected.

**Comment by fnagel** [comment]
Working on a fix.

**Comment by fnagel** [comment]
Pushed a fix. Needed to rework the linking in BE module templates. Should work in TYPO3 6.2 as we know generate links with BE default methods.

While testing I noticed an issue when try to translate the content elements. Can somebody confirm?

**Comment by pvanhemmen** [comment]
Thanx for the fix. Works great, although I still don't understand what was the cause of this problem. Do you mind to shed some light on what exactly happened?

I don't have a multilingual installation setup, but what exactly is the problem with translation of content elements?

**Comment by fnagel** [comment]
In TYPO3 7.5 the routing of BE modules was reworked and the links used in our BE module stopped working. Or better: the auth token passed with our links stopped working. Moved from some custom code to core functions and everything works as expected again. Streamlined the link generation in our modules, too.

Some testing would be helpful! Perhaps our TCA config is outdated?
When using the "translate records" or "sync with original language" buttons below the content elements in a blog post stopped working.

**Comment by pvanhemmen** [comment]
While checking the language problems I encountered another issue with fluid content elements (which also could affect other integrations). Somewhere in TYPO3 7 the concept of dataprocessing in general and in TYPO3 7.4 dataProcessing for media galleries was introduced: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.4/Feature-67663-IntroduceDataProcessorForMediaGalleries.html

Fluid Styled Content makes heavy use of this concept and uses the generated content in its templates:

![dataprocessing](https://cloud.githubusercontent.com/assets/715022/10364837/0633e32e-6dbf-11e5-8bee-6a8eae91bdd1.png)

In t3extblog for some reason these processors are never called for inline content elements within blogposts. Therefore all media (images/movies) added in fluid styled content textmedia elements are never rendered for content elements inside blogposts.

This is not an issue of inline content elements in general. Seems like the standard configuration is overridden somewhere, but I couldn't find out exactly where that is yet.

**Comment by pvanhemmen** [comment]
Followup: The issue is, that the viewhelper `RenderContentViewhelper` used in the templates basically fetches the contents from the database without executing any hooks/processors. For testing purposes I tried the RenderViewHelper provided by vhs, which works. I think the difference is how they fetch the tt_content records:

```$html = $GLOBALS['TSFE']->cObj->cObjGetSingle('RECORDS', $conf);```

This ensures all configurated processores etc. are called as the content is routed through the necessary classes. See also: https://github.com/FluidTYPO3/vhs/blob/master/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L242. Hope that helps!

**Comment by fnagel** [comment]
This seems like a non trivial issue. Would you mind creating a new issue /
ticket for this?

**Comment by pvanhemmen** [comment]
Of course, migrated to #92

**Comment by fnagel** [comment]
(y) Thanks!

I've opened another one for the broken (?) IRRE localization, see #93

**Comment by pvanhemmen** [comment]
The original issue has been fixed and the fix works great.
