### ISSUE TITLE
Pre-release tasks: version 2.0.0

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#89]
**General**

* [x] TYPO3 7.6 compatibility
* [x] Check and fix unit tests
* [x] Final testing (multi-language installations)
 * [x] TYPO3 CMS 6.2
 * [x] TYPO3 CMS 7.6

**Documentation**

* [x] Improve installation manual, see #78 
* [x] RWD Image feature (see 8378adfe2067b4717fe00204ffe40172b644f9b4)
* [x] Bootstrap form error VH (see d4c3c3a51d311fec122f28fdfe67cb925f1c3f3f)

**Comment by fnagel** [comment]
@criwe @pvanhemmen @all

I've added some more fixes for TYPO3 7.6 and did some testing in multi language 6.2 and 7.6 installations. Seems everything works fine and we are almost ready for version 2.0!!!

I would like to ask you to do some more final testing (see https://github.com/fnagel/t3extblog/blob/master/Documentation/DeveloperGuide/Index.rst#testing) in order to make sure everything is ready for a new release.

In addition, I've merged @criwe's documentation changes and added some changes myself. Would be helpful if somebody could proof read that, too.

Thanks for your help and your contributions!

**Comment by fnagel** [comment]
@criwe @pvanhemmen Did you find any time to take a look at this again?

**Comment by criwe** [comment]
@fnagel Hi Felix, I was / am quite busy, but can make same tests at the weekend. I could update t3extblog in my livesystem (6.2) or make some tests in my testing installation (7.6). What would be more useful?

**Comment by fnagel** [comment]
Testing in a live environment seems more useful to me. So go with the 6.2 live system. Make sure to create a backup before ;-)

I've already tested in my 7.6 staging system and will update my live installation to 7.6 (incl. t3extblog) asap.

**Comment by pvanhemmen** [comment]
I have t3extblog running on TYPO3 7.6 within a local dev environment and on a staging server (where other people are active as well). The only issue I have on the staging server is that I have an "No blog records found!" on whatever page / folder I call the t3extblog module from within the backend. The suggested link to the article manager is empty as well, although all blog posts display just fine.

Before calling it a bug I'll check my TS config as this could be settings related as well. I will try to look into it over the weekend, when I find some time ;)

**Comment by fnagel** [comment]
Thanks for the feedback! Sounds really good! Except for that folder issue. Not sure whats the issue here but wonder why you do not get any exception or similar. 

If possible, I would really like to take a look. Just ping me here, email or phone.

**Comment by criwe** [comment]
I´ve updated t3extblog in my livesystem (6.2). Everything works fine! Great job felix! 

Two things while updating: 
- use "clear all cache" (Installtool)!
- If using customised templates, you need to copy the be-template-folders (if not be-module throws an error or blank page)

Two BE-styling "issues", see screenshots

![be_error](https://cloud.githubusercontent.com/assets/7531138/11452621/f418d098-95ee-11e5-9a43-f9a0be952b91.png)
![be_error2](https://cloud.githubusercontent.com/assets/7531138/11452624/f86e1ed2-95ee-11e5-8b57-9ac93578986e.png)

Maybe caching problem??

**Comment by fnagel** [comment]
You mentioned tasks should be covered by the upgrade guide for 2.0

It seems you're missing the updated CSS. Works in my 6.2 installation.
BE should load this file: https://github.com/fnagel/t3extblog/blob/master/Resources/Public/Css/BackendStyle.css
Added here: https://github.com/fnagel/t3extblog/blob/master/Resources/Public/Css/BackendStyle.css

Try to clear cache multiple times. Force reload the BE. Try disabling the assets merging.

**Comment by fnagel** [comment]
@criwe @pvanhemmen Did you guys manage to solve your issues? Can I help to fix?

**Comment by fnagel** [comment]
@pvanhemmen Any news on this issue? I really would like to release the new version...

**Comment by fnagel** [comment]
Ok, time for releasing the new version.

@pvanhemmen Please open a new issue if the folder issue is still an issue.

**Comment by fnagel** [comment]
New release is life! See http://typo3.org/extensions/repository/view/t3extblog

Blog post (German language): https://www.felixnagel.com/blog/artikel/2015/12/18/neue-major-version-der-typo3-blog-extension-t3extblog-veroeffentlicht/

@criwe @pvanhemmen 
Thanks a lot for all your help and contributions! Really appreciated, you guys rock!
