### ISSUE TITLE
Plugin Categories shows error

### ISSUE THREAD

**Issue by dhoffmann1979** [fnagel/t3extblog#90]
When selecting a category the following error is displayed.

An error occurred while trying to call TYPO3\T3extblog\Controller\PostController->categoryAction().

Debug Output in Developer Log see attachment
![bildschirmfoto 2015-10-05 um 11 20 11](https://cloud.githubusercontent.com/assets/1279518/10277003/42fd089e-6b53-11e5-9b91-6ba05c922e6f.png)

**Comment by fnagel** [comment]
Which version of TYPO3 and t3extblog are you using? 

Did you check the TS settings? Is `plugin.tx_t3extblog.persistence.storagePid` and `plugin.tx_t3extblog.settings.blogsystem.pid` set?

**Comment by dhoffmann1979** [comment]
Hi i use Version 1.2.1 but i also tried the Version from the master branch about a week ago. Both Pids are set correct.

**Comment by fnagel** [comment]
Can you post a complete stack trace? Not sure what could cause this issue.

Which version of TYPO3 are you using?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by dhoffmann1979** [comment]
It is Version 6.2.15. The error mentioned above is the only message i can get out.

**Comment by fnagel** [comment]
Mhh, 1.2.1 definitely works well with 6.2.15. 

Strange this is there is no validator except `\TYPO3\T3extblog\Validation\Validator\UrlValidator`. So the "missing" validators are not configured anywhere. Is it possible there is another extension adding those validators? Did you tried to deinstall some other extensions?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by dhoffmann1979** [comment]
Yes, it doesn't work. I uninstalled nearly all non-core-extensions. Any other idea ?

**Comment by fnagel** [comment]
Tried latest master version?

No, not without a complete stack trace or looking into that TYPO3 instance.

**Comment by fnagel** [comment]
Any feedback on this issue? Does the problem still persist?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please re-open if needed.
