### ISSUE TITLE
TYPO3 7.5 - Blog post content localization

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#93]
While testing I noticed an issue when try to translate the content elements. The "translate records" or "sync with original language" buttons below the content elements in a blog post stopped working.

Can somebody confirm?

**Comment by corth** [comment]
Can confirm that behavior. The "sync" or "translate" Ajax request header returns 500 and will fail every time because the diffsoruce array seems to be empty.

**Comment by fnagel** [comment]
Probably related tickets: 
https://forge.typo3.org/issues/70376
https://forge.typo3.org/issues/70375

**Comment by fnagel** [comment]
It seems this issue is fixed in TYPO3 7.6. 

Can somebody confirm this?
