### ISSUE TITLE
RSS Feed is not valid

### ISSUE THREAD

**Issue by cleicht** [fnagel/t3extblog#94]
I use the latest Version from GitHub. The RSS Feed is not valid.
This feed does not validate.
line 6, column 41: language must be an ISO-639 language code: [help]
<description></description> <language></language> <copyright></copyright> 
line 8, column 154: url must be a full and valid URL: [help]
... sion for TYPO3</generator> <image> <url></url> 
line 11, column 10: link must be a full and valid URL: [help]
    <link></link>
line 18, column 150: XML parsing error: <unknown>:18:150: not well-formed (invalid token) [help]
... tem%5Bpost%5D=38&tx_t3extblog_blogsystem%5Bday%5D=06&tx_t3extblog_blogsy ...
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
line 9, column 11: title should not be blank [help]
    <title></title>
line 9, column 11: Image title doesn't match channel title [help]
    <title></title>
line 11, column 10: Image link doesn't match channel link [help]
    <link></link>

**Comment by fnagel** [comment]
You need to escape all URLs when not using EXT:realurl

**Comment by cleicht** [comment]
Wie kann ich das machen? Ich hab doch nur eine einzige URL die ich als
absRefPrefix = http://www.beyond-history.de/

angeben muss.
Es scheint ja auch die Language nicht zu stimmen?
language must be an ISO-639 language code

Christian

**Comment by fnagel** [comment]
https://docs.typo3.org/typo3cms/extensions/realurl/Realurl/Configuration/Installation/Index.html

Language error seems like a follow-up error. There is no ISO language definition within the RSS template.

**Comment by cleicht** [comment]
And where can i setup this language for the rrs feed?
Where can i setup the Blog Title?
For the Blog i do not use RealURL.

Thanks for Help

**Comment by fnagel** [comment]
Not really needed, but here you go: https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Templates/Post/Rss.xml#L7

Set via TS (see the documentation.) here: https://github.com/fnagel/t3extblog/blob/master/Resources/Private/Templates/Post/Rss.xml#L4

As I said, when not using RealUrl (which is really not recommended) you will need to make sure all links are properly encoded. Not sure what needs to be done, try around with htmlspecialchars or htmlentities ViewHelpers for the links.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please re-open if needed.
