### ISSUE TITLE
EmailService should not depend on FE

### ISSUE THREAD

**Issue by madaxel** [fnagel/t3extblog#98]
Since the EmailService is used in BE the message charset should not be set from TsFe

**Comment by fnagel** [comment]
Seems legit. Using extbase / fluid in BE context is a nightmare.

Is there an error or something? Seems this fails silently.

Not sure how to solve this. Seems there is no easy way to receive the FE charset in BE context. What do you think? I guess a fallback to utf-8 should do the trick?

**Comment by madaxel** [comment]
Just saw it from the last commits and tought it would fail if tsfe is not set. 
I would think a fallback to typo3s default charset for mails should be used, but never had to find out till now. Direct mail for example introduced extra setting for charset afaik

Tommorow I'm on a project where mails are send from scheduler. Maybe I get some more infos there, otherwise utf is fine.

**Comment by fnagel** [comment]
> Direct mail for example introduced extra setting for charset afaik

I guess because they found no good way to do this in BE context, too.

> Tommorow I'm on a project where mails are send from scheduler. 

FYI: current state runs on multiple system without issues. That's why I asked for an error message or something.

I will provide a proposed fix soon.

**Comment by fnagel** [comment]
You know what? It's possible this never failed due to the template is renders first, which calls our ActionViewHelper, which generates a TSFE. 

Upcoming fix make uses of this fact.

**Comment by madaxel** [comment]
Ok, if TSFE is always there, then the issue might be closed.
Would be nicer if no dependency to TSFE.
In my todays project UTF-8 is hardcoded...

**Comment by fnagel** [comment]
Closed for now. Please re-open if needed.

**Comment by fnagel** [comment]
It seems this problem is still an issue, at least in TYPO3 6.2 instances and German umlauts within the templates.
