### ISSUE TITLE
Proper use of translation.typo3.org

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#99]
Questions: 

* Workflow for extensions in general
* Is Pootle TER version aware?
* Do we need to update the templates manually ("update against templates" button)?
* How to deal with changed language keys?
* Do we need de.*.xlf files in `Resources/Private/Language` anymore? How to import in Pootle?

Resolution:

* [x] Release new TER version (update to latest structure)
* [x] Manually copy / paste all `de` localization strings to Pootle
* [x] Remove 1a5befbada4ef65c095336d5bf6b52e2d3c69176 temp fix
* [x] Remove [hints](https://github.com/fnagel/t3extblog/blob/c73a8ad2a0c8f6a0061dd9d41fa1b998cc24e8e6/Documentation/DeveloperGuide/Index.rst) in documentation
* [x] Add info in documentation (Dev guide -> deployment)
* [x] Remove German localizations
  * [x] `de.*.xlf` files from `Resources/Private/Language`
   * [x] Remove German part in  `typo3conf/ext/t3extblog/Resources/Private/Language/locallang_db.xml`
* [x] Release new TER version

**Comment by xperseguers** [comment]
* Is Pootle TER version aware?
** No
* Do we need to update the templates manually
** No
* How to deal with changed language keys
** The latest state in English (templates) is what will be available
* Do we need `de.*.xlf` files...?
** No, they are not read
* How to import them in Pootle
** Import unfortunately is broken in Pootle => manually copy/paste :/

**Comment by fnagel** [comment]
@xperseguers Thanks a lot for this information! Very helpful!

So, let me get this straight: Pootle always uses the code base of all xlf files within `Resources/Private/Language` of the latest TER version. de.*.xlf files are ignored completely (at least in TYPO3 7.x).

Another question: 
Is it possible to use something like [this](https://github.com/fnagel/t3extblog/blob/master/ext_localconf.php#L130-L131) and remove the related language (in this case German) to keep maintaining the localization strings within the xlf file?

**Comment by xperseguers** [comment]
`de.*.xlf` files are ignore *on Pootle*, but not *in TYPO3* (regardless of the version). Meaning those German translations won't be automatically imported, right! but they will be used unless the corresponding "official" translations have been found when importing localization packages from Pootle within your TYPO3 instance.

Regarding the code snippet, sorry I don't get it... Either you wan't to manage on Pootle or you don't, why would you want to do half half? That will be the hell for people to know that they *may* contribute for French or Italian on Pootle but should prepare e.g., pull requests for German... ?!?

**Comment by fnagel** [comment]
Ahh ok, that explains why my local de.*.xlf files won't be loaded since we added an account on Pootle. Which is why I added the code snippet. Seems I missed a language cache when trying to get the local files to work...

I get your point and agree. Having local files and Pootle seems not like a good idea. I've added a todo list in this issue's description.

**Comment by fnagel** [comment]
Thanks for your help!

**Comment by fnagel** [comment]
@xperseguers Sorry to bother you again, but it seems the files for my extension are outdated. When or how are the translation files updated from a new TER version?

**Comment by xperseguers** [comment]
They should be available

**Comment by fnagel** [comment]
@xperseguers Indeed, they are now! Did you trigger some update or just perfect timing? Anyway, thanks again for your help!
